### ISSUE TITLE
Error impersonating user account with service account in Calendar

### ISSUE THREAD

**Issue by stesvis** [googleapis/google-auth-library-nodejs#1001]
Hello,

I am not able to create and get events impersonating a user account with our G Suite service account, however, I can do calendar events CRUD using the servie account + service account email.

When I try to impersonate a user, this is the code:
```cs
var credential = new ServiceAccountCredential(
	new ServiceAccountCredential.Initializer(id: serviceAccountId)
	{
		User = email, // user email or servie account email
		Scopes = new[] { CalendarService.Scope.Calendar }
	}.FromCertificate(certificate));

// Create Google Calendar API service.
service = new CalendarService(new BaseClientService.Initializer()
{
	HttpClientInitializer = credential,
	ApplicationName = ConfigurationSetting.GoogleApiApplicationName,
});

// Define the parameters of the request.
EventsResource.ListRequest request = service.Events.List(calendarId: "primary");

request.SingleEvents = true;
request.TimeMin = timeMin ?? DateTime.Now;
request.TimeMax = timeMax ?? DateTime.Now.AddMonths(months: 1);
request.MaxResults = maxResults ?? 100;

Events myEvents = request.Execute();
```
When `email` is the user that i try to impersonate I get this error all the time:
```json
{
    "Error": "unauthorized_client", 
    "Description": "Client is unauthorized to retrieve access tokens using this method, or client not authorized for any of the scopes requested.", 
    "Uri": ""
}
```

We went thru the delegation process already, but still no luck:
https://developers.google.com/identity/protocols/oauth2/service-account#delegatingauthority

What could the issue be?

We are using .NET EF 6.4.4 and Google.Apis.Calendar.v3 1.48.0.2012

**Comment by sofisl** [comment]
Hi there! Thanks for filing a bug. Before anything, would you mind installing the latest version of googleapis (npm i googleapis@latest)? I noticed you're on an older version - might be a quick fix!

**Comment by stesvis** [comment]
Hi @sofisl I installed the latest version on all and I still get the same error:
![image](https://user-images.githubusercontent.com/6062684/87333946-21bb9b80-c4fb-11ea-9e9b-a8d035de8069.png)

**Comment by stesvis** [comment]
I also tried this other approach, and I still get the same error:
```
//----------------------------------------------
var scopes = new string[] {
	CalendarService.Scope.Calendar,
};
GoogleCredential credential;

using (var stream = new FileStream(
	HttpContext.Current.Server.MapPath("~/google-calendar-credentials.json"),
	FileMode.Open,
	FileAccess.Read))
{
	credential = GoogleCredential
		.FromStream(stream)
		.CreateScoped(scopes)
		.CreateWithUser(CurrentUser.Email);
}
//----------------------------------------------
// Create Google Calendar API service.
service = new CalendarService(new BaseClientService.Initializer()
{
	HttpClientInitializer = credential,
	ApplicationName = ConfigurationSetting.GoogleApiApplicationName,
});
```

**Comment by stesvis** [comment]
Resolved, the email used to test was not under the same G Suite domain.
