### ISSUE TITLE
Missing scope in Credentials interface

### ISSUE THREAD

**Issue by Sytten** [googleapis/google-auth-library-nodejs#1003]
The interface `Credentials` (https://github.com/googleapis/google-auth-library-nodejs/blob/master/src/auth/credentials.ts#L15) is missing the `scope` field which is a `string`.

See this documentation for the typical response: https://developers.google.com/identity/protocols/oauth2/openid-connect#exchangecode

**Comment by JustinBeckwith** [comment]
Good find!  Fix ready over in #1007
