### ISSUE TITLE
Readme improvements

### ISSUE THREAD

**Issue by ile** [googleapis/google-auth-library-nodejs#1006]
- Node.js version: v12.18.0
  - npm version: 6.14.4
  - `google-auth-library` version: 6.0.4

Hi,

I'm not quite sure if I'm using the library correctly, and for that I would suggest some improvements into the README (as the first step).

For example:

- "A complete OAuth2 example" doesn't show how to refresh the tokens/handle token events, so it is not really a **complete** example. Could it be improved to be an actual complete example?

- The section "Handling token events" has this:

```js
const client = await auth.getClient();
```

... but it is unclear what this `auth` object is and where it comes from. Can this be improved?

Thanks.

**Comment by ile** [comment]
Also:

My problem is that this library doesn't seem to refresh the tokens at all. Not automatically, as it claims.

Not sure what I'm doing wrong.That's why I'm asking for the documentations to be improved.

**Comment by JustinBeckwith** [comment]
Greetings, and thanks for the feedback!  Taking these one at a time:

> doesn't show how to refresh the tokens/handle token events
This is explained here, with code:
https://github.com/googleapis/google-auth-library-nodejs#handling-token-events

> Could it be improved to be an actual complete example?
There is a collection of complete examples that run end to end here:
https://github.com/googleapis/google-auth-library-nodejs/tree/master/samples

> it is unclear what this auth object is and where it comes from
In many of the other examples in the README, this is called out:
https://github.com/googleapis/google-auth-library-nodejs#choosing-the-correct-credential-type-automatically

> this library doesn't seem to refresh the tokens at all
I assure, it does 😆  If you're running into issues where token refreshing doesn't seem to be happening, please open an issue specifically on this topic!  Share:
- The exact code you're trying to run
- The version of node.js and `google-auth-library` you're using 
- Any error messages you may be getting 

Including this stuff makes it a ton easier for us to figure out where you're getting tripped up :)
