### ISSUE TITLE
refactor(samples): Consolidate idtoken samples for serverless

### ISSUE THREAD

**Issue by grayside** [googleapis/google-auth-library-nodejs#1019]
## Background

Serverless products in general need two samples for Node.js: minting an identity token to make a request to a service or HTTP function, and validating an identity token on an arbitrary hosting platform receiving an HTTP request from Cloud Tasks or Cloud Scheduler.

## Proposal

1. Rewrite the [idtoken minting sample](https://github.com/googleapis/google-auth-library-nodejs/blob/master/samples/idtokens-cloudrun.js) `google_auth_idtoken_cloudrun` as `google_auth_idtoken_serverless`.
    * Remove Cloud Run from comments or replace with "Cloud Run or Cloud Functions"
    * Simplify the example URL to `https://RUN_OR_FUNCTION_TARGET_URL`
    * Remove "Cloud Run" from info log

2. Wrap in additional region tags for `run_service_to_service_auth` and `functions_bearer_token` for tracking as part of serverless work.

3. Update the [Cloud Run samples index](https://github.com/GoogleCloudPlatform/cloud-run-samples#readme) to reference the auth sample here.

My understanding is @bcoe is fine with this change. @ace-n could you confirm this approach for Cloud Functions?

**Comment by grayside** [comment]
Note: On agreement for this proposal I will undertake these changes.

**Comment by bcoe** [comment]
@grayside this plan sounds great to me 👍
