### ISSUE TITLE
Doc mistake: missing await in code sample + missing details about ID token.

### ISSUE THREAD

**Issue by nicolasdao** [googleapis/google-auth-library-nodejs#1037]
#### Environment details

  - OS: MacOS Catalina (10.15.1)
  - Node.js version: 12.16.3
  - npm version: 6.14.5
  - `google-auth-library` version: 6.0.6

#### Steps to reproduce

1. Browse to https://github.com/googleapis/google-auth-library-nodejs#fetching-id-tokens
2. This snippet is incorrect
```js
const client = auth.getIdTokenClient(url);
const res = await client.request({url});
```
It throws the error ` TypeError: client.request is not a function`. That's because there is a missing `await`. Correct this sample with:
```js
const client = await auth.getIdTokenClient(url);
const res = await client.request({url});
```

**Comment by sofisl** [comment]
Thanks for pointing this out!

Would you mind creating a new issue (can just be copy and paste) for the second question? I think that's more of a question/docs request, and I just want to make sure we capture it accurately. Thanks!

**Comment by nicolasdao** [comment]
No problem @sofisl.

FYI, I've submitted a PR for this update the doc (https://github.com/googleapis/google-auth-library-nodejs/pull/1038).

**Comment by fhinkel** [comment]
Greetings, we're closing this. Looks like the issue got resolved. Thank you for the PR @nicolasdao  Please let us know if the issue needs to be reopened.
