### ISSUE TITLE
Doc: Missing details about explicitly retrieving an ID token

### ISSUE THREAD

**Issue by nicolasdao** [googleapis/google-auth-library-nodejs#1039]
#### Environment details

  - OS: MacOS Catalina (10.15.1)
  - Node.js version: 12.16.3
  - npm version: 6.14.5
  - `google-auth-library` version: 6.0.6

#### Steps to reproduce

1. Browse to https://github.com/googleapis/google-auth-library-nodejs#fetching-id-tokens
2. Missing code sample to retrieve an ID token

The doc explains how to explicitly retrieve an access token. It also explains how to implicitly make requests to protected Cloud Run services that use, behind the scene, the ID token. But it fails to explain how to explicitly acquire that ID token. I need that ID token to make my own HHTP requests to Cloud Run services without relying on the `google-auth-library` HTTP client object.

> I've already submitted a PR https://github.com/googleapis/google-auth-library-nodejs/pull/1038 that suggests how to retrieve an ID token.

**Comment by sofisl** [comment]
@nicolasdao, I don't think we ever clarified why would need that ID token directly as a common use case (see #1038), so I'm going to go ahead and close this issue for now. Thanks for submitting a PR, it sparked a very interesting conversation internally!

**Comment by nicolasdao** [comment]
Thanks, @sofisl.

I needed that id_token to explicitly call a private Cloud Run API. Private CR APIs can be called between them when their respective service accounts are configured with the appropriate role (e.g., cloudrun/invoke), but cannot be called from the internet via the usual access_token in the Authorization header method. Instead, you must use the id_token (which I find weird as this is not the intent of an id_token as far as the OAuth2 spec is concerned). Why would I need to call a private Cloud Run API from the internet would you say? Why don't you make it public then? Well, the good thing about private Cloud Run is that they are secured out-of-the-box, so I don't have to reinvent the wheel or use some boilerplate to secure my API. Also, requests that fail the private CR auth are not billed, while securing a public API manually incurs cost, even if that's very brief.
