### ISSUE TITLE
how can i get access_token from refresh_token OAuth

### ISSUE THREAD

**Issue by BesthaSwapna** [googleapis/google-auth-library-nodejs#1044]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**
 **Describe the solution you'd like**
 **Describe alternatives you've considered**
 **Additional context**

**Comment by sofisl** [comment]
Hi there, would you mind providing your code snippet, what you're getting, and what you're expecting to get or what you're trying to accomplish? Thanks in advance!

**Comment by sofisl** [comment]
Hi @BesthaSwapna, 

Without knowing more information, here is the [documentation](https://developers.google.com/identity/protocols/oauth2) for our OAuth2.0 flow. 

I don't believe you should need to explicitly set a new access_token from a refresh_token to make further requests. You can continue making requests using a refresh token, see [here](https://github.com/googleapis/google-auth-library-nodejs/blob/b4d139d9ee27f886ca8cc5478615c052700fff48/src/auth/googleauth.ts#L82).
