### ISSUE TITLE
Where to find the correct API authentication URLs?

### ISSUE THREAD

**Issue by charlievaughan** [googleapis/google-auth-library-nodejs#1060]
I'm trying to use the code example below taken from the documentation to authenticate a Node app with the Dialogflow API. But I see this appears to be using a URL for the Google DNS API (https://dns.googleapis.com/dns/v1/projects). And I can see from my dashboard I'm making DNS API calls (while not fully authenticating).

Where do I find the correct URL for Dialogflow? 

```
const {JWT} = require('google-auth-library');
const keys = require('./jwt.keys.json');

async function main() {
  const client = new JWT({
    email: keys.client_email,
    key: keys.private_key,
    scopes: ['https://www.googleapis.com/auth/cloud-platform'],
  });
  const url = `https://dns.googleapis.com/dns/v1/projects/${keys.project_id}`;
  const res = await client.request({url});
  console.log(res.data);
}

main().catch(console.error);
```

**Comment by charlievaughan** [comment]
I've continued to work on my problem and successfully managed to set up a local GOOGLE_APPLICATION_CREDENTIALS environment variable in my local bash profile as outlined in "Authenticating as a service account" https://cloud.google.com/docs/authentication/production .

The test samples in this guide as well as "gcloud auth application-default print-access-token": https://cloud.google.com/sdk/gcloud/reference/auth/application-default/print-access-token look like they are successfully being authorised and returning data.

So I don't think I have setup authorisation or keys incorrectly. I just need the specific URL fo the 'url' constant above. I'm trying to use the Dialogflow v2 API.

**Comment by wvanderdeijl** [comment]
Have a look at the reference docs at https://cloud.google.com/dialogflow/es/docs/reference/rest
I hope that is what you’re looking for.

**Comment by sofisl** [comment]
Thanks for stepping in, @wvanderdeijl! @charlievaughan, I think those documents linked above are the ones you are looking for.

I'll close this issue for now, but if you want to point to exactly what you're looking to do with DialogFlow,  I can reopen with a more specific answer/code snippet. 

Thanks!
