### ISSUE TITLE
how to run the oauth script

### ISSUE THREAD

**Issue by ANUBHAV2142** [googleapis/google-auth-library-nodejs#1063]
I want to generate access and refresh token dynamically. I don't know to run this module. I have entered the key.json file in oauth.js in samples and edited the package.json file by adding a "start : node oauth.js". I have also imported the "npm install google-auth-library" in samples and doing npm start next. It is running fine but then I am getting an error at browser "Missing required parameter: client_id" though the key.json file already have the client_id details.
Can anyone help me out and guide me through it, as I can't figure it out from the details given.
Thanks in advance.

**Comment by sofisl** [comment]
Hi @ANUBHAV2142, 

 Can you confirm that the file you're using has OAuth credentials? If you haven't set it up, you can do so by visiting your Cloud Console, then navigating to APIS & Services > Credentials. From there, you should be able to either create or download an OAuth Client ID.

As a side note,  you shouldn't need to add a script to package.json to run this module. Simply go to the samples directory, run `npm i`, and then run `node oauth2.js`. 

Hope this helps! Feel free to reopen if this doesn't resolve the issue.
