### ISSUE TITLE
Get AWS region for AwsClient from environment variable

### ISSUE THREAD

**Issue by wvanderdeijl** [googleapis/google-auth-library-nodejs#1066]
I see @bojeil-google is doing great work in the `byoid` branch to bring Workload Identity Federation to google-auth-library. I've been experimenting with it in a AWS Lambda function and ran into the issue that AwsClient is trying to invoke the AWS metadata service to get the region.

But when running in AWS Lambda, there is no metadata service. For the credentials itself the AwsClient first looks at the environment variables AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY and AWS_SESSION_TOKEN. If these env vars are available (as they are in a Lambda) those will be used instead of calling the metadata service for credentials.

It would be great if the AwsClient also looks at AWS_REGION first before making any call to the metadata service. This env var is available when running in AWS Lambda as can be seen at https://docs.aws.amazon.com/lambda/latest/dg/configuration-envvars.html

I'll submit a PR with the suggested change.

As a quick hacky workaround I created my own subclass:
```
class RegionalGoogleAuth extends GoogleAuth {
    async getClient() {
        let client = await super.getClient();
        if (client instanceof AwsClient) {
            const c = client as any;
            if (!c.__getAwsRegion) {
                c.__getAwsRegion = c.getAwsRegion.bind(c);
                c.getAwsRegion = async () => process.env.AWS_REGION ?? c.__getAwsRegion();
            }
            client = c;
        }
        return client;
    }
}
```

**Comment by wvanderdeijl** [comment]
Another question I have is if the `byoid` branch is close to being merged into master and the next release of this library? We need to have our client (running on AWS) to access our Google Cloud resources and this new workload identity federation is a wonderful way to give them access without the need to exchange service account keys. We are actually postponing the release of our new version until the `byoid` branch is merged and released.

**Comment by bojeil-google** [comment]
Ah, interesting. I was not aware of this edge case in AWS lambda. I think we can check the `AWS_REGION` environment variable for existence first before calling the metadata server. I think that should solve our problem.

Thanks, @wvanderdeijl for trying this out and for your fix recommendation!

Regarding your second question, the feature is code complete but it going through some internal reviews, testing and checks. Hopefully it should be landing in master soon (if everything goes well, possibly end of month). We'll keep you posted. We totally agree with you on the need to avoid using service account keys. This is one of the main driving forces behind this.

**Comment by wvanderdeijl** [comment]
Hopefully the #1067 PR is the way you want to go with the `AWS_REGION` check.

Thanks for the update on the progress and let's hope this lands in a couple of weeks 👍 

Another thing I noticed is that all of the fields in `AwsOptions` are mandatory, but for most of the fields we could use a sensible default (like `subject_token_type`, `token_url`, `credential_source.environment_id`, `credential_source.regional_cred_verification_url`, `credential_source.region_url`, and `credential_source.url`). The last two aren't even used when the `AWS_*` environment variables are used. Would you (@bojeil-google) be interested in me making a PR to default these properties when not supplied in `AwsOptions` ?

**Comment by wvanderdeijl** [comment]
Yes, each Region consists of two or more zones. The metadata service returns the zone (with the extra letter) and the AWS_REGION env var is just the region without the letter. In fact, we’re already using this in our lambda’s by having a package.json dependency directly to the byoid branch

**Comment by bojeil-google** [comment]
Thanks for confirming!

**Comment by wvanderdeijl** [comment]
This was fixed in #1067

**Comment by wvanderdeijl** [comment]
@bojeil-google not sure if you are still following this issue, but is there any update on an expected release date for the workload-identity-federation support? We are ready to have our clients start using this, but having them refer to a branch of this repo in their package.json dependencies doesn’t feel like the way to go 😄 
Would be great if this lands in master soon.

**Comment by bojeil-google** [comment]
Hey @wvanderdeijl we apologize for the delay, we are trying to time it with the following:
- The GA launch for [workload identity pool](https://cloud.google.com/iam/docs/access-resources-aws) federation support.
- Support with other languages, such as [Python](https://github.com/googleapis/google-auth-library-python/tree/byoid), [Java](https://github.com/googleapis/google-auth-library-java/tree/3pi), Go and [gRPC C++](https://github.com/grpc/grpc/commit/bedaeb5265b320182641c7425e7fd6c79e092370).

We may land the Node.js implementation sooner but we are targeting the month of December for the overall launch.
