### ISSUE TITLE
Authenticating with service account inside cloud function

### ISSUE THREAD

**Issue by bhr** [googleapis/google-auth-library-nodejs#1068]
I've been trying to follow the code samples to get an access token from inside a cloud function for a service account. The goal is to pass that access token to another service which can then directly run functions through an ESP.

I've tried the following options without success:

### A
```
    const url = `https://cloud-run1234.a.run.app`;
    const auth = new GoogleAuth();
    const client = await auth.getIdTokenClient(url);
    const result = await client.request({url});
    console.log(result.data);
```

#### Error received in logs
`Error: [object Object] at Gaxios._request (/workspace/node_modules/gaxios/build/src/gaxios.js:89:23) at process._tickCallback (internal/process/next_tick.js:68:7)`

### B
```
    const url = `https://cloud-run1234.a.run.app`;
    const client = new Compute({
      serviceAccountEmail: '<service-account>@<project>.iam.gserviceaccount.com'
    });
    const clientToken = await client.fetchIdToken(url);
    console.log(clientToken);
```

#### Error received in logs
`Could not fetch ID token: Unsuccessful response status code. Request failed with status code 404 at Gaxios._request (/workspace/node_modules/gaxios/build/src/gaxios.js:89:23) at process._tickCallback (internal/process/next_tick.js:68:7)`

### More details

`https://cloud-run1234.a.run.app` is a cloud run instance to which the service account has permissions as Cloud Run Invoker and Cloud Functions Invoker.

I should also mention that I didn't set `GOOGLE_APPLICATION_CREDENTIALS`. If reading the docs correctly, then this should not be required when running inside a cloud function.

**Comment by bhr** [comment]
I eventually got around the issue by storing the service account email and private key in the environment config:

Here's the working example:
```
    const config = functions.config().auth_service_account;

    // transform the key into a json string and then parse it to escape newline characters
    const keyAsJson = JSON.parse(`{ "key" : "${config.private_key}" }`);
    const client = new JWT({
      email: config.client_email,
      key: keyAsJson.key
    });

    const url = config.esp_url;
    const token = await client.fetchIdToken(url);
```

I am still wondering why **B** (using Compute with a service account email) didn't work.

**Comment by sofisl** [comment]
Hi @bhr,

I'm glad you found a workaround, and sorry for the wait!

As for why B wouldn't work, I think it's because the auth library needs more information in order to authenticate your account. Here are some ways to authenticate:

```
export interface GoogleAuthOptions {
  /**
   * Path to a .json, .pem, or .p12 key file
   */
  keyFilename?: string;

  /**
   * Path to a .json, .pem, or .p12 key file
   */
  keyFile?: string;

  /**
   * Object containing client_email and private_key properties
   */
  credentials?: CredentialBody;

  /**
   * Options object passed to the constructor of the client
   */
  clientOptions?: JWTOptions | OAuth2ClientOptions | UserRefreshClientOptions;

  /**
   * Required scopes for the desired API request
   */
  scopes?: string | string[];

  /**
   * Your project ID.
   */
  projectId?: string;
}
``` 

Could you include the tutorial or samples you were following, to see if there's areas to better clarify or update? Thanks in advance!

**Comment by sofisl** [comment]
@bhr, feel free to reopen this issue with that documentation if you want us to address the confusion. Thanks!
