### ISSUE TITLE
Google message business token

### ISSUE THREAD

**Issue by jijoamt** [googleapis/google-auth-library-nodejs#1076]
Can you please let us know how can we obtain a token for google business using the below code
What is the url to be used here. the scope we tried is 'https://www.googleapis.com/auth/businessmessages'

async function main() {
  const client = new JWT({
    email: keys.client_email,
    key: keys.private_key,
    scopes: ['https://www.googleapis.com/auth/businessmessages'],
  });
 const url = '';
  const res = await client.request({url});
}

main().catch(console.error);

**Comment by sofisl** [comment]
Hi there! That scope looks correct, from what I saw. 

Is it possible for you to follow [this sample](https://github.com/googleapis/google-auth-library-nodejs/blob/master/samples/credentials.js) (not sure if you have any constraints using this code):

```
const auth = new GoogleAuth({
    credentials: {
      client_email: clientEmail,
      private_key: privateKey,
    },
    scopes: 'https://www.googleapis.com/auth/cloud-platform',
  });
```

**Comment by sofisl** [comment]
Hi there, I'm going to close this for now, feel free to reopen if you don't have a solution.
