### ISSUE TITLE
fix documentation related to authentication strategy

### ISSUE THREAD

**Issue by sofisl** [googleapis/google-auth-library-nodejs#1085]
Related to #1084 and #983 

How, and in what order of operations, are we authenticating in this library? We have a document describing how environment variables, constructors, etc., operate together, but what about order of operations within the constructor? For example, where do `keyfile`, `credentials`, and`clientOptions` fit in against the wider order of operations for authentication? When should we be trying to get a projectId?

**Comment by danielbankhead** [comment]
The `projectId` part of this request has been partially resolved here (essentially, we'll do a best effort as some APIs do not require it):
- https://github.com/googleapis/google-auth-library-nodejs/pull/1451

For the others, I raised a PR to improve the documentation: #1653
