### ISSUE TITLE
Got invalid_grant within token expiration

### ISSUE THREAD

**Issue by xiaoxia-github** [googleapis/google-auth-library-nodejs#1093]
Hi there,

We are using 'googleapis' (version 43.0.0) & 'google-auth-library' (version 5.10.1) to refresh the token stored in our DB. We know that the expiration time is 1 hour so we'll do the refresh every 50 mins. I understand that it seems the refreshAccessToken() method has been deprecated, but it worked pretty well before the error happened, only recently it would frequently pop up the invalid_grant error for some of our accounts. 

Before the errors happened, all the previous refreshes were successfully conducted right on time (50 mins before this invalid_grant error), so I am not sure why this error would happen before the expiration time. Below are our code snippet, part of the error response, and the last refreshed token object. (credentials removed)

I have the complete response and token object, so if you'll need them or anything else please leave your email here. Really appreciate your patience here and really looking forward to hearing back from you! 

```ts
import { google, gmail_v1 } from 'googleapis';
import { GmailToken, GmailSendEmailResponse } from '../../type';
const gmail = google.gmail('v1');
const OAuth2Google = google.auth.OAuth2;
const authClient = new OAuth2Google(
  process.env.GMAIL_CLIENT_ID,
  process.env.GMAIL_CLIENT_SECRET,
  process.env.GMAIL_REDIRECT_URL
);

export async function refreshGmailToken(token: GmailToken): Promise<any> {
  authClient.setCredentials({
    access_token: token.accessToken,
    refresh_token: token.refreshToken
  });
  try {
    const res = await authClient.refreshAccessToken();
    if (res.credentials) {
      return { newTokenObj: res.credentials };
    } 
  } catch (e) {
    tokenLogger.error(
      `[gmail][refreshGmailToken][${token.emailAddress}] ${JSON.stringify(e)}`
    );
    return { error: e.response.data };
  }
} 
```

```js
{
  "response": {
    "config": {
      "method": "POST",
      "url": "https://oauth2.googleapis.com/token",
      "data": "refresh_token=****&client_id=*****&client_secret=****&grant_type=refresh_token",
      "headers": {
        "Content-Type": "application/x-www-form-urlencoded",
        "User-Agent": "google-api-nodejs-client/5.10.1",
        "x-goog-api-client": "gl-node/9.8.0 auth/5.10.1",
        "Accept": "application/json"
      },
      "params": {},
      "body": "refresh_token=****&client_id=*****&client_secret=****&grant_type=refresh_token",
      "responseType": "json"
    },
    "data": {
      "error": "invalid_grant",
      "error_description": "Token has been expired or revoked."
    },
    "headers": {
      "alt-svc": "h3-Q050=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000,h3-T051=\":443\"; ma=2592000,h3-T050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"",
      "cache-control": "no-cache, no-store, max-age=0, must-revalidate",
      "connection": "close",
      "content-encoding": "gzip",
      "content-type": "application/json; charset=utf-8",
      "date": "Sat, 31 Oct 2020 16:04:36 GMT",
      "expires": "Mon, 01 Jan 1990 00:00:00 GMT",
      "pragma": "no-cache",
      "server": "scaffolding on HTTPServer2",
      "transfer-encoding": "chunked",
      "vary": "Origin, X-Origin, Referer",
      "x-content-type-options": "nosniff",
      "x-frame-options": "SAMEORIGIN",
      "x-xss-protection": "0"
    },
    "status": 400,
    "statusText": "Bad Request",
    "request": {
      "responseURL": "https://oauth2.googleapis.com/token"
    }
  },
  "config": {
    "method": "POST",
    "url": "https://oauth2.googleapis.com/token",
    "data": "refresh_token=****&client_id=*****&client_secret=****&grant_type=refresh_token",
    "headers": {
      "Content-Type": "application/x-www-form-urlencoded",
      "User-Agent": "google-api-nodejs-client/5.10.1",
      "x-goog-api-client": "gl-node/9.8.0 auth/5.10.1",
      "Accept": "application/json"
    },
    "params": {},
    "body": "refresh_token=****&client_id=*****&client_secret=****&grant_type=refresh_token",
    "responseType": "json"
  },
  "code": "400"
}
```

The last refreshed token:

```js
{"access_token":"***","scope":"openid https://www.googleapis.com/auth/gmail.compose https://www.googleapis.com/auth/gmail.readonly https://www.googleapis.com/auth/gmail.modify https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile","token_type":"Bearer","id_token":"*****","expiry_date":1604160876139,"refresh_token":"*****","email_address":"*****"}
```

**Comment by Aymkdn** [comment]
Any updates on that one?

**Comment by bcoe** [comment]
@xiaoxia-github @Aymkdn from the Google APIs OAuth 2.0 page:

> A Google Cloud Platform project with an OAuth consent screen configured for an external user type and a publishing status of "Testing" is issued a refresh token expiring in 7 days.

Do you potentially still have your app set to testing?

**Comment by bcoe** [comment]
@xiaoxia-github also, would you be able to use the latest version of the `googleapis` library? We've fixed a variety of bugs related to refreshing tokens in the past couple years.

**Comment by Aymkdn** [comment]
Yes, indeed, my project is in test (it's for personal use and I'm the only tester). I used the `refreshAccessToken()` and it's working for now... I'll see what will happen in 1 week.

**Comment by bcoe** [comment]
@xiaoxia-github closing this for now, due to inactivity, please let me know if you're continuing to bump into issues:

1. after switching your app to a non-test account.
2. ensuring you're on the latest version of the client.

---

@Aymkdn the refresh token itself expires in 7 days, so you will find that it you stop being able to get an access token after that time. You will need to switch your project off test, even if you're only using this token for yourself.

**Comment by Aymkdn** [comment]
Thanks, @bcoe 👍 

How to switch a project off test without deploying it to all? Is the "alpha" release enough?
![image](https://user-images.githubusercontent.com/946315/116694828-0b19fe80-a9c0-11eb-89f8-2072aa955bc0.png)

If it's something else that needs to be done, I'd appreciate if you can give me a direction?
