### ISSUE TITLE
Mixed Content error when requesting ID token from App Engine

### ISSUE THREAD

**Issue by oscarmon7** [googleapis/google-auth-library-nodejs#1097]
My frontend application is deployed in App Engine and is trying to obtain an ID token to authenticate into a service running in Cloud Run. The following two errors are triggered by method "getIdTokenClient": 

_gaxios.ts:91 Mixed Content: The page at 'https://myapp-dev.nw.r.appspot.com/' was loaded over HTTPS, but requested an insecure resource 'http://169.254.169.254/computeMetadata/v1/instance'. This request has been blocked; the content must be served over HTTPS  
gaxios.ts:91 Mixed Content: The page at 'https://myapp-dev.nw.r.appspot.com/' was loaded over HTTPS, but requested an insecure resource 'http://metadata.google.internal./computeMetadata/v1/instance'. This request has been blocked; the content must be served over HTTPS._ 

#### Environment details

  - OS: App Engine
  - Node.js version: 12
  - npm version: 6.14.8
  - `google-auth-library` version: 6.1.3

#### Following a snippet of my code:

```
const {GoogleAuth} = require('google-auth-library');
const url = 'https://myapp-dev-fvnpywgyfa-nw.a.run.app';
const auth = new GoogleAuth();
const serviceRequestOptions = {
  method: 'GET',
  headers: {
    'Content-Type': 'text/plain',
  },
  timeout: 3000,
};
try {
  // Create a Google Auth client with the Renderer service url as the target audience.
  if (!client) client = await auth.getIdTokenClient(url);
  // Fetch the client request headers and add them to the service request headers.
  // The client request headers include an ID token that authenticates the request.
  const clientHeaders = await client.getRequestHeaders();
  serviceRequestOptions.headers['Authorization'] =
    clientHeaders['Authorization'];
} catch (err) {
  throw Error('could not create an identity token: ', err);
}

```

Is this the right approach to authenticate my frontend in App Engine?

**Comment by oscarmon7** [comment]
Actually, there is a second error generated in this same method invocation:

_Access to manifest at 'https://accounts.google.com/o/oauth2/v2/auth?client_id=622787071-f0r2o-long-url-here-qlyLfsNpDpn1Q9DUMUrg' (redirected from 'https://myapp-dev.nw.r.appspot.com/manifest.json') from origin 'https://myapp-dev.nw.r.appspot.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource._

**Comment by wvanderdeijl** [comment]
I assume this mixed content warning is appearing in your client side browser application. Can you figure out where/why your client code is attempting to use the Google metadata service?
The JavaScript code you posted is running server side in nodejs, I assume? Then I see no way how that would influence your client side code.

Or are you including this google-auth-library in client side code? This module is intended for nodejs (thus server side). If you are interested in client side auth, have a look at Firebase Auth or Google Cloud Identity Platform (which basically is the same as Firebase auth):  https://cloud.google.com/identity-platform/docs/how-to

**Comment by oscarmon7** [comment]
Hi Wilfred, thanks for your response. I am actually quite new to Reacty and node.js and I have used that library wrongly in the frontend. So, I think that's clear wrt to the Mixed content. 
Second problem which I reported here (https://github.com/googleapis/google-auth-library-nodejs/issues/1097#issuecomment-725380646) is actually due to Cloud Run not supporting CORS as tracked by Google here: https://issuetracker.google.com/issues/168707835.

Ticket can be closed from my perspective. Thanks.

**Comment by bcoe** [comment]
@oscarmon7 you cannot connect to the metadata server from the context of your React application, the special metadata server is only available from within the GCP network, whereas your frontend application is running on whatever server your users computer happens to be running on.

---

What I recommend researching is how to configure sessions in a react application, there are many tutorials on the Internet, [like this one](https://javascript.plainenglish.io/secure-react-express-apps-jsonwebtoken-cookie-session-auth0-and-passport-tutorial-e58d6dce6c91).

The basic flow, is that a user will create an account in your system and prove identity, perhaps using Auth0, or [Google 3-legged OAuth](https://support.google.com/a/answer/7037815?hl=en).

Your cloud run application will maintain a session for the user, and make API requests on their behalf.

**Comment by Emre-Arikan** [comment]
@bcoe My Vuejs frontend in Vue und Flask backend are both in GCP network behind IAP. And my frontend needs a google auth token in order to communicate with backend. So what's wrong with that?

**Comment by Emre-Arikan** [comment]
@oscarmon7 how did you solve that problem?, I have a similar case right now:  My Vuejs frontend in Vue und Flask backend are both in GCP network behind IAP. And my frontend needs a google auth token in order to communicate with backend.

**Comment by hebbellwt** [comment]
I have the same problem, my vue is hosted by google cloud run, it should invokes a GCP function. But I got the same error
