### ISSUE TITLE
Mixed content error on Cloud Run when generating Google-signed OAuth ID token

### ISSUE THREAD

**Issue by hom-bahrani** [googleapis/google-auth-library-nodejs#1098]
Hi, I'm following the [Securing Cloud Run services tutorial](https://cloud.google.com/run/docs/tutorials/secure-services), using my own react app deployed to cloud run as the client and chrome is blocking the request to generate an auth token because its expecting the request to be made with HTTPS instead of HTTP. Thanks

**Comment by hom-bahrani** [comment]
I noticed the client in the [example repo](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/tree/master/run/markdown-preview/editor) is using a server rendered node.js express app. I'm guessing this library may not work on client side javascript frameworks like React?

Another part of the cloud run documentation uses a [different approach](metadataServerTokenURL) by making a request to a `metadataServerTokenURL`, I tried this as well but got the same result as its also a HTTP url - here is my code snippet

```javascript
const handleItemSubmit = () => {
    const receivingServiceURL = process.env.REACT_APP_BACKEND_URL;
    const metadataServerTokenURL = `http://metadata/computeMetadata/v1/instance/service-accounts/default/identity?audience=${receivingServiceURL}`;
  
    try {
      fetch(metadataServerTokenURL)
        .then(res => res.text())
        .then(token => {
          fetch(receivingServiceURL, {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json',
              Authorization: `Bearer ${token}`
            },
            body: {
              title: item
            },
        }).then(res => res.json())
          .then(json => console.log(json));
        });
    } catch (error) {
      throw Error('Request failed: ', error);
    }
  }
```

**Comment by hom-bahrani** [comment]
I managed to around this by creating another cloud run service to handle authentication between the React app and the backend API. It would be nice to be able to authenticate directly from the browser though without the added latency
<img width="733" alt="secure" src="https://user-images.githubusercontent.com/8465628/99539056-ac2e7300-29a5-11eb-8f84-1cb47a3e4b3d.png">

**Comment by bcoe** [comment]
@hom-bahrani it should be possible to make things work in a react-app, using webpack or rollup (see: [thread here](https://github.com/googleapis/google-cloud-node/issues/2933)).

This is something we'd like to make easier in the future.

**Comment by hom-bahrani** [comment]
Thanks @bcoe thats looks useful
