### ISSUE TITLE
Webpack support for google-auth-library

### ISSUE THREAD

**Issue by beingminimal** [googleapis/google-auth-library-nodejs#1103]
#### Problem Statement
Hi,

We are trying to setup frontend and backend service communication through
https://cloud.google.com/run/docs/tutorials/secure-services#shipping-frontend. 

In frontend service, we use webpack for transpiling our code. 
When we try to use google-auth-library with webpack bundle we are receiving the below error 

```
ERROR in ./node_modules/google-auth-library/build/src/auth/googleauth.js 17:24-48
Module not found: Error: Can't resolve 'child_process' in '/workspace/node_modules/google-auth-library/build/src/auth'

ERROR in ./node_modules/google-auth-library/build/src/auth/googleauth.js 18:11-24
Module not found: Error: Can't resolve 'fs' in '/workspace/node_modules/google-auth-library/build/src/auth'


ERROR in ./node_modules/google-auth-library/build/src/auth/googleauth.js 20:11-24
Module not found: Error: Can't resolve 'os' in '/workspace/node_modules/google-auth-library/build/src/auth'

same error for stream, crypto, fs, assert, tls packages.
```
Please let us know how can we use OAuth Token-based communication with frontend cloud run service (uses webpack)  and backend cloud run service.

#### Environment details

  - OS: Windows
  - Node.js version: 14.15.0
  - `google-auth-library` version: 6.1.3

#### Steps to reproduce

  1. Setup frontend service with webpack (https://cloud.google.com/run/docs/tutorials/secure-services#shipping-frontend)

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by beingminimal** [comment]
Hi @sofisl ,

Can you please look into this and provide us a solution?

Thanks

**Comment by bcoe** [comment]
@beingminimal our client libraries, at this time, do not fully support usage in a frontend context. We make an effort to make this possible, but we don't run integration tests against webpack, nor do we provide many samples for running our libraries in the browser.

Having said this, we do make an effort to make our libraries function with Webpack when possible. The problem you're bumping into here is that our library requires the Node.js modules `child_process`, `fs`, and `os`. You can eliminate these errors by creating a webpack config that replaces these with alternate resolutions:

https://webpack.js.org/configuration/resolve/

You should be able to make each of these modules resolve `false`, and in turn your project should start building.
