### ISSUE TITLE
[JWT authentication for google photos] 403 - 'Insufficient Permission'

### ISSUE THREAD

**Issue by realestninja** [googleapis/google-auth-library-nodejs#1111]
When running the first example from the JWT part from the README, I keep getting a 403:

```
errors: [
    {
      message: 'Insufficient Permission',
      domain: 'global',
      reason: 'insufficientPermissions'
    }
  ]
```

My code is pretty much the first JWT part in the README with the photos scope:

```
const { JWT } = require('google-auth-library');
const keys = require('./service.json');

async function main() {
  const client = new JWT({
    email: keys.client_email,
    key: keys.private_key,
		scopes: ['https://www.googleapis.com/auth/photoslibrary'],
  });
  const url = `https://dns.googleapis.com/dns/v1/projects/${keys.project_id}`;
  const res = await client.request({url});
  console.log(res.data);
}

main().catch(console.error);

```

I have created a service account and downloaded it's JWT. I tried granting it different roles like "Service Account User" and currently just as "Owner". But in the end I just keep getting the 403. I am not sure if something is wrong with the code or with the permissions or if JWT authentication just doesn't work with the photos scope. 
(The google cloud project should be fine, since OAuth2 has already worked. I was just trying to get JWT to work aswell)

Looking for advice!

**Comment by sofisl** [comment]
Hi @realestninja, 

Can you clarify exactly what you're trying to do (with the photos API)? Normally, you wouldn't call this code sample directly, but instead use the `getClient()` method. See [this](https://github.com/googleapis/google-api-nodejs-client/blob/master/samples/jwt.js) code sample for more details.

**Comment by realestninja** [comment]
I get 

> Hi @realestninja,
> 
> Can you clarify exactly what you're trying to do (with the photos API)? Normally, you wouldn't call this code sample directly, but instead use the `getClient()` method. See [this](https://github.com/googleapis/google-api-nodejs-client/blob/master/samples/jwt.js) code sample for more details.

I want to get the URLs of photos from photo albums. They keep changing every hour or so. The idea is to have a backend api that fetches the requested photo album and serves the image URLs. I can't find anything related to google photos in the jwt samples. Is it even possible?

**Comment by realestninja** [comment]
Nevermind, things seem to have cleared themselves up :)
