### ISSUE TITLE
Library Does not work with User Account Credentials

### ISSUE THREAD

**Issue by jbgrunewald** [googleapis/google-auth-library-nodejs#1113]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

1) Is this a client library issue or a product issue?
No, this is specific to generating authenticated tokens with user account credentials.

2) Did someone already solve this?
  - Search the issues already opened: https://github.com/googleapis/google-auth-library-nodejs/issues
  - Search the issues on our "catch-all" repository: https://github.com/googleapis/google-cloud-node
  - Search or ask on StackOverflow (engineers monitor these tags): http://stackoverflow.com/questions/tagged/google-cloud-platform+node.js
Another person seems to be experiencing a very similar issue, https://stackoverflow.com/questions/61754530/use-user-account-credential-for-reaching-private-cloud-run-cloud-functions

3) Do you have a support contract?
Please create an issue in the [support console](https://cloud.google.com/support/) to ensure a timely response.

If the support paths suggested above still do not result in a resolution, please provide the following details.

#### Environment details

  - OS: macOS Big Sur 11.1
  - Node.js version: v8.15.1
  - npm version: 6.4.1
  - `google-auth-library` version: 6.0.6

#### Steps to reproduce

  1. $ gcloud auth login<email> --project <project>
  2. $ gcloud auth application-default login
  3. Attempt to execute getIdTokenClient()

Example Code:
```
import { GoogleAuth } from "google-auth-library";
const auth = new GoogleAuth();
const aClient = await auth.getIdTokenClient(<iapClientAudience>);
```

This results in an error: 
(node:25566) UnhandledPromiseRejectionWarning: Error: Cannot fetch ID token in this environment, use GCE or set the GOOGLE_APPLICATION_CREDENTIALS environment variable to a service account credentials JSON file.

Setting the GOOGLE_APPLICATION_CREDENTIALS to point to the generated user account credentials does not resolve this.

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by sofisl** [comment]
Hi @jbgrunewald, I think what's going on is that you're authenticating with two different accounts between the first and second step, and they are probably trying to authenticate different accounts from different environments. Read more about the commands [here](https://cloud.google.com/sdk/gcloud/reference/auth/application-default/login) and [here](https://cloud.google.com/sdk/gcloud/reference/auth/login). Try just using the second command before running the script, and see if that works for you.

**Comment by jbgrunewald** [comment]
@sofisl I agree that I was making an error by authenticating twice with two different accounts. I tried each individually and still received the same error. 

I also used the --update-adc  with the option to explicitly overwrite the ADC when running the auth command.

```
gcloud auth login --update-adc
```

Fundamentally, this error doesn't tell me there's a permissions issue. This is telling me that it can't find the format it's expecting for the credentials (i.e. service account credentials). Without looking at the code, I'm only guessing, but it appears that it doesn't try to use the Application Default Credentials at all, or the format is not acceptable for some reason.

**Comment by bshaffer** [comment]
@jbgrunewald the reason we throw this error is that as of a year ago, ID tokens cannot be fetched using `gcloud` credentials.

They CAN be fetched using client credentials, but the use-case there is very fringe: you would be asking an end-user to grant you permission to get ID tokens on their behalf.

**Comment by jbgrunewald** [comment]
Yeah that’s what I’ve gathered. My take away so far is that we are using IAP for service to service communication sometimes, but that’s not really it’s strong suite. 

James Grunewald

**Comment by rob-pomelo** [comment]
In addition, other language libraries (such as java) make this possible without requiring service accounts. 

```
const client = await auth.getIdTokenClient(https://cloud-run-url.app);
const token = await client.idTokenProvider.fetchIdToken(https://cloud-run-url.app);
```
The above lines are what we use to fetch an OIDC to call a gRPC cloud run service. The above only works when the ADC is for a service account, but ideally it would work for an ADC for the user account (as it does for java / go).

**Comment by sydney-sisco** [comment]
It shouldn't be this complicated to just execute a function securely!!!

**Comment by ckrebeca** [comment]
The following worked on our end - tested and validated the token with Axios too.

const {GoogleAuth} = require('google-auth-library'); 
const targetAudience = 'https://my-cloud-run.nn.a.run.app/
const auth = new GoogleAuth();
const client = await auth.getIdTokenClient(targetAudience)
const **accessToken** = await client.idTokenProvider.fetchIdToken(targetAudience);

**Comment by leo-paz** [comment]
@ckrebeca how did you end up authenticating once you had the idToken (`accessToken` in your case)? I am adding it to a header like so 
```
const response = await fetch(url.toString(), {
  method: "POST",
  headers: {
     Accept: "application/json",
     Authorization: `Bearer ${idToken}`
   },
   body: formData
})
      ```
But I continue to get a 403. It was working when i used the standard `idTokenClient.request()` method but this was giving issues when I used FormData

**Comment by kym6464** [comment]
From the [docs](https://cloud.google.com/docs/authentication/provide-credentials-adc#service-account):

> You can use service account impersonation to set up a local Application Default Credentials (ADC) file. Client libraries that support impersonation can use those credentials automatically. 

I confirmed that this works on **google-auth-library v8.9.0 or higher**. But earlier versions don't seem to support impersonation; they throw this error:

```
The incoming JSON object does not contain a client_email field
```
