### ISSUE TITLE
Rely on less npm dependencies

### ISSUE THREAD

**Issue by thernstig** [googleapis/google-auth-library-nodejs#1119]
**Is your feature request related to a problem? Please describe.**
The google auth libs depends on a lot of dependencies. A common pattern in the npm community is to try to rely on less dependencies. Organizations might sometimes have to approve all dependencies from FOSS, which takes a considerable amount of time. Less dependencies can also mean less security holes.

 **Describe the solution you'd like**
It would be nice if could depend on less dependencies. One idea would be to replace [gaxios](https://www.npmjs.com/package/gaxios) with [node-fetch](https://www.npmjs.com/package/node-fetch). Node-fetch is a zero-dependency package mimicing the browser's `fetch`.

Maybe there are more packages that are not necessary, or can be implemented directly in this code.

 **Describe alternatives you've considered**
n/a

 **Additional context**
n/a

**Comment by JustinBeckwith** [comment]
Greetings, and thanks for the feedback!  We've already trimmed the dependency graph in this library down a considerable bit over the last few years, and it's really down to a list of things we *need*.  To the specific `gaxios` question - we actually [make this module](https://github.com/googleapis/gaxios) - it uses `node-fetch` under the hood, and adds a very minimal number of deps to make proxying work, which is a requirement for many folks. 

We actively try to keep the size of the graph as low as we can.  If you have other ideas on things we could trim without removing functionality - we'd love to hear it!

**Comment by JustinBeckwith** [comment]
Also, lol for fun, this is what it looked like a few years ago, with a 200ms load time:
![image](https://user-images.githubusercontent.com/534619/105524789-00e7b600-5c95-11eb-9bc9-aa5850032db5.png)

**Comment by manwithsteelnerves** [comment]
Just adding for reference, we see around 350+ ms for loading the auth library when running on cloud functions(default config)
![Screenshot 2021-05-04 at 10 31 09 AM](https://user-images.githubusercontent.com/5437614/116962591-073df300-acc4-11eb-95c0-675a22435693.png)

Any tips on how to reduce it further? or any minify option of the library available(I'm using this module as a dependency on my server)
Thanks
