### ISSUE TITLE
getRequestHeaders() not returning updated access token

### ISSUE THREAD

**Issue by tbhaxor** [googleapis/google-auth-library-nodejs#1126]
https://github.com/googleapis/google-auth-library-nodejs/blob/79355a7eef3acfca8536f0e6d8aab7c5f67b38fa/src/auth/oauth2client.ts#L700

I guess its marked deprecated by mistake. Actually i tried using getToken and getRequestHeaders they both are returning expired access_token in my case even though I have valid refresh token

**Comment by tbhaxor** [comment]
@bcoe sweet ping :smile:

**Comment by bcoe** [comment]
@tbhaxor what are you attempting to do?

If you're trying to get auth headers, which you could then populate in an HTTP request, I think you want `getRequestHeaders`.

If you just want to make a request to a protected endpoint, I think you might want to use something like this as a starting point:

```js
const {GoogleAuth} = require('google-auth-library');

/**
* Instead of specifying the type of client you'd like to use (JWT, OAuth2, etc)
* this library will automatically choose the right client based on the environment.
*/
async function main() {
  const auth = new GoogleAuth({
    scopes: 'https://www.googleapis.com/auth/cloud-platform'
  });
  const client = await auth.getClient();
  const projectId = await auth.getProjectId();
  const url = `https://dns.googleapis.com/dns/v1/projects/${projectId}`;
  const res = await client.request({ url });
  console.log(res.data);
}

main().catch(console.error);
```

You shouldn't need to be calling `refreshAccessToken` yourself, as it will be called automatically when the token is close to expiring.

**Comment by tbhaxor** [comment]
> @tbhaxor what are you attempting to do?

@bcoe All I want to do is get the access token 

This is the class method I am using for it
```ts
class User implements IUserClass {
  refreshToken(): Promise<void> {
    return new Promise<void>((resolve, reject) => {
      const auth = new OAuth2Client({ clientId: process.env.GOOGLE_CLIENT_ID, clientSecret: process.env.GOOGLE_SECRET_ID });

      auth.setCredentials({
        //@ts-ignore
        access_token: this.access_token,
        //@ts-ignore
        refresh_token: this.refresh_token
      });

      // @ts-ignore
      auth
        .refreshAccessToken()
        .then(({ credentials: tok }) => {
          // @ts-ignore
          this.access_token = tok.access_token;
          // @ts-ignore
          this.save()
            .then(resolve)
            .catch((e: Error) => reject(e));
        })
        .catch((e: Error) => reject(e));
    });
  }
}
```

**Comment by tbhaxor** [comment]
> I think you want `getRequestHeaders`.

Previously I have this function only, but I realised that it is not refreshing token As after 1hr of granting time, When I run `getRequestHeaders` I get same expired token

**Comment by bcoe** [comment]
@tbhaxor `getRequestHeaders`, as far as I know, should be refreshing the access token. This sounds like a bug.

**Comment by tbhaxor** [comment]
So will it get fixed soon?

**Comment by tbhaxor** [comment]
@bcoe sweet ping 😄

**Comment by bcoe** [comment]
@tbhaxor my colleague and I were just discussing issues like this today.

@sofisl was able to fetch and use the `refresh_token` using an approach [like this](https://github.com/googleapis/google-api-nodejs-client/issues/2330#issuecomment-778531366).

Have you tried this approach of listening on `tokens` events?

**Comment by tbhaxor** [comment]
@bcoe Awesome. 

I didnt know about this event. Will try and let you know

**Comment by bcoe** [comment]
@tbhaxor our intention is to spend a few days this quarter making sure that token refresh logic is as intuitive as possible (regardless of the approach you're using).

But, I'm hoping `tokens` can unblock you for now.

**Comment by bcoe** [comment]
@tbhaxor were you able to confirm that listening on the `tokens` event returns the tokens for you?

**Comment by tbhaxor** [comment]
The issue is solved with getRequestHeader.

**Comment by asit-prakash** [comment]
I am getting  No refresh token is set. error while using `getRequestHeader`, can anyone help. I did execute `oauth2Client.setCredentials(tokens);`

**Comment by bcoe** [comment]
@asit-prakash could you please open an issue that describes your problem in detail, with an example of the code you're writing.

**Comment by MihirLathiya510** [comment]
while using the `getRequestHandler` i'm getting the error `No access, refresh token, API key or refresh handler callback is set.`  

all i want to do is refresh my token if it's expired
