### ISSUE TITLE
Use IAM client SDK for externalclient-setup script

### ISSUE THREAD

**Issue by bojeil-google** [googleapis/google-auth-library-nodejs#1132]
Action item from: https://github.com/googleapis/google-auth-library-nodejs/pull/1131

We need to switch to using IAM client SDK once v1 API has all the v1beta changes.

https://cloud.google.com/iam/docs/reference/rest/v1beta/projects.locations.workloadIdentityPools
https://github.com/googleapis/google-api-nodejs-client/tree/master/src/apis/iam

This is used to setup workload identity pools for external client integration tests in `samples`.

**Comment by danielbankhead** [comment]
Looks like this has been previously completed.
