### ISSUE TITLE
Auth: Export AuthClient

### ISSUE THREAD

**Issue by leandro-manifesto** [googleapis/google-auth-library-nodejs#1145]
My code uses `GoogleAuth.getClient()` to return a client to authorize requests to Google APIs.

This is the current implementation:
```typescript
import { GoogleAuth, OAuth2Client } from 'google-auth-library';

const googleAuth = new GoogleAuth();

export async function getAuth(): Promise<OAuth2Client> {
    return googleAuth.getClient();
}
```

After upgrading to `7.0.0` it became a compile error because the return type of `getClient()` changed to `Compute | JWT | UserRefreshClient | BaseExternalAccountClient` when `cachedCredentials` was changed to `JSONClient | Compute | null` in #1052.

The fixed implemention should be:
```typescript
import { AuthClient, GoogleAuth } from 'google-auth-library';

const googleAuth = new GoogleAuth();

export async function getAuth(): Promise<AuthClient> {
    return googleAuth.getClient();
}
```

But `AuthClient` is not exported by the package.
`BaseExternalAccountClient` was eventually exported in `7.0.2`, but `AuthClient` is still missing.

**Comment by sofisl** [comment]
Thanks for the report, @leandro-manifesto.

@bcoe, sounds like we can work on this issue during our auth fixit in March.

**Comment by bcoe** [comment]
@leandro-manifesto I'm curious why you can't just use `googleAuth.getClient();` directly, vs., wrapping it in a helper?

**Comment by leandro-manifesto** [comment]
One of our scripts uses cached global clients for different identities/scopes.
Some are ID token clients as well.

I don't think it's the best approach, but that's what we had at the time.

**Comment by danielbankhead** [comment]
Apologies for the delay. Added via https://github.com/googleapis/google-auth-library-nodejs/pull/1361
