### ISSUE TITLE
Combining axios with JWT instead of using gaxios

### ISSUE THREAD

**Issue by zawnk** [googleapis/google-auth-library-nodejs#1152]
I'm planning on doing a request class that optionally takes the JWT as a parameter. If it is omitted, the request will be a regular http request via axios. If the JWT is given, I want to still use regular axios but add the authentication from the JWT to it. Is it enough in this case to just use `.getRequestHeaders()` on the JWT or is there a better way to do it? Or will I run into problems doing it this way?

**Comment by JustinBeckwith** [comment]
Yes!  The `getRequestHeaders()` method will give you a property bag that includes the authorization header.  From there, you are free to use whichever HTTP request client you like :)  Let us know if you run into any issues!
