### ISSUE TITLE
Missing sourcemaps

### ISSUE THREAD

**Issue by Rigidoont** [googleapis/google-auth-library-nodejs#1154]
At the end of every `.js` file there is a URL to their source maps, but there are no sourcemaps present in the installed package directory.  

For example, at the end of the file  `node_modules\google-auth-library\build\src\auth\authclient.js` there is a row:
`//# sourceMappingURL=authclient.js.map`

That `sourceMappingURL` is pointing to a non-existent file. Chrome devtools' console is complaining about it a lot, it shows ~25 messages of missing sourcemaps for the files of this library.

**Comment by danielbankhead** [comment]
We've removed source maps in our other libraries to keep the deliverables small (same with others, like nodejs-storage):
- https://github.com/googleapis/nodejs-storage/pull/2240

I've created a PR to remove the broken source maps.
