### ISSUE TITLE
How to refresh an expired token?

### ISSUE THREAD

**Issue by TLKG** [googleapis/google-auth-library-nodejs#1195]
I'm using Node `google-auth-library` package to verify idToken at my API server according to [Google][1]:

    await googlelib.verifyIdToken(
                    {
                        idToken: myToken,
                        audience: myGoogleClientID, 
                    }, 
                    (e, pass) => {...}

`verifyIdToken()` does not auto-refresh an expired token, for example I got `Error: Token used too late, 1623708107.76 > 1623701458`. I've searched the document, `OAuth2Client` class has `refreshAccessToken()`, no `refreshIdToken()`. How to refresh an idToken? 

Note, the only Google API I'm using is the Authentication.

  [1]: https://developers.google.com/identity/sign-in/web/backend-auth

**Comment by TLKG** [comment]
After hours of research, believe the solution is to manage our own session.

**Comment by ahuangege** [comment]
Hello,I meet the same problem.  Manage our own session? I don't understand.

**Comment by TLKG** [comment]
@ahuangege Yes
