### ISSUE TITLE
How to access CodeChallengeMethod enum from TypeScript?

### ISSUE THREAD

**Issue by kkomelin** [googleapis/google-auth-library-nodejs#1209]
Hi there,

I'm using `"googleapis": "^81.0.0"` with TypeScript to generate an auth url this way:

```typescript
import { google } from 'googleapis';
const client = new google.auth.OAuth2(...);

client.generateAuthUrl({
    access_type: 'offline',
    scope: scopes,
    code_challenge_method: google.auth.OAuth2.CodeChallengeMethod.S256,
    code_challenge: process.env.GOOGLE_CLIENT_CODE_CHALLENGE || '',
});
```
I can't find the namespace where **CodeChallengeMethod** enum is located. I guessed it was **google.auth.OAuth2.CodeChallengeMethod.S256** but I received:
> TypeError: Cannot read property 'S256' of undefined

Could you please tell me where I can import **CodeChallengeMethod** enum from? 
Thanks in advance.

For reference: 
https://googleapis.dev/nodejs/google-auth-library/5.6.0/miscellaneous/enumerations.html#CodeChallengeMethod
https://github.com/googleapis/google-auth-library-nodejs/blob/master/src/auth/oauth2client.ts#L61

**Update 2021-07-13:**
Import from the [top level](https://github.com/googleapis/google-auth-library-nodejs/issues/1209#issuecomment-878775433) doesn't work too.

**Comment by kkomelin** [comment]
For those who stumbled upon the same issue, I fixed it by declaring the enum locally:
```typescript
enum CodeChallengeMethod {
  Plain = 'plain',
  S256 = 'S256',
}
```
But I still would appreciate a proper fix from the package maintainers.

**Comment by tmatsuo** [comment]
It's defined here:
https://github.com/googleapis/google-auth-library-nodejs/blob/faa6677fe72c8fc671a2190abe45897ac58cc42e/src/auth/oauth2client.ts#L61

It's also exported in the top level index.ts:
https://github.com/googleapis/google-auth-library-nodejs/blob/faa6677fe72c8fc671a2190abe45897ac58cc42e/src/index.ts#L32

I think you can import it from the top level.

**Comment by tmatsuo** [comment]
Closing, but feel free to reopen.

**Comment by kkomelin** [comment]
Hi @tmatsuo,
Thanks for your answer.

I wish I could import it from the top level or any other level but I can't.

The following doesn't work for some reason and that's why I'm here:
```
import { google, CodeChallengeMethod } from 'googleapis';
```
I receive:
> TypeError: Cannot read property 'S256' of undefined

**Comment by kkomelin** [comment]
> Closing, but feel free to reopen.
@tmatsuo I don't have permissions to reopen the issue, so I would ask you to reopen.

**Comment by tmatsuo** [comment]
@kkomelin Can you do the following?

```typescript
import {CodeChallengeMethod} from 'google-auth-library';
```

**Comment by kkomelin** [comment]
Thanks @tmatsuo,

Yes, importing `CodeChallengeMethod` from `google-auth-library` works but then I need to add `google-auth-library` to my dependency list to be safe.

What's the difference between `googleapis` and `google-auth-library`? Why can't I use the officially recommended way with `googleapis`?

**Comment by tmatsuo** [comment]
@kkomelin 

I don't think you need to have `google-auth-library` in your package.json because `googleapis` depends on `google-auth-library`.
