### ISSUE TITLE
Allow setting authentication client for google-cloud libraries

### ISSUE THREAD

**Issue by salrashid123** [googleapis/google-auth-library-nodejs#1210]
PR [1207](https://github.com/googleapis/google-auth-library-nodejs/pull/1207) will implement the capability to impersonate a service account.  That is given a set of source credentials, the implementation will derive a new set of credentials which are eventually intended to call an underlying GCP API.

The implementation there surfaces an object which can be used to make direct REST api calls  (see [28->51](https://gist.github.com/salrashid123/ac54c655b8f8ef1e3da84d71f510c9cd#file-main-js-L28-L51).  However, there isn't an easy way to inject this type of a client into any existing google-cloud-* library set.

The only way to do that now is to create a placeholder client (see [57->72](https://gist.github.com/salrashid123/ac54c655b8f8ef1e3da84d71f510c9cd#file-main-js-L57-L72) and set that into a library which internally extracts the raw client fromthe placeholder/wraper object

Also, this workaround with the wrapped client will work for _some_ google apis (eg, it will not work for `Storage` )

---

This FR is to

Construct a uniform surface to allow injecting authenticated clients into google-cloud-* libraries.  Essentially, it shoud not be necessary to setup the intermediate placeholder/wrapper for the client and also the same final mechanism should work for all libraries (Storage)

---

Finally there are several flavors of 'clients':

  - [DownscopedClient](https://googleapis.dev/nodejs/google-auth-library/latest/classes/DownscopedClient.html)
  - [ImpersonatedClient](https://github.com/googleapis/google-auth-library-nodejs/pull/1207)

which actually differ in the classes it using:

  ```javascript
  export class DownscopedClient extends AuthClient {
  export class OAuth2Client extends AuthClient {
  export class Impersonated extends OAuth2Client {      
  ```

which means the usage of these clients diverges  (eg, i probably can't use a downscoped client into a google-cloud library even after this FR is done)

**Comment by tmatsuo** [comment]
Assigning @bcoe for triage.

**Comment by salrashid123** [comment]
here is the tmp workaround for impersonated+gcs which was shown to me yesterday:
  https://gist.github.com/salrashid123/e5fc03761f62ef6ff213ac3b29661967

note, i manually added in the `sign()` method to `node_modules/google-auth-library/build/src/auth/impersonated.js` just to allow impersonated_credentials to issue signedurls

**Comment by danielbankhead** [comment]
This should be supported as of v7.14.0: https://github.com/googleapis/google-auth-library-nodejs/pull/1372

`GoogleAuth` now accepts `AuthClient`: https://github.com/googleapis/google-auth-library-nodejs/blob/b48254490768799e465a8fa4aae13296ddceea53/src/auth/googleauth.ts#L74-L78

Sample: https://github.com/googleapis/google-auth-library-nodejs/blob/main/samples/downscopedclient.js
