### ISSUE TITLE
Mismatched signature when signing with impersonated credentials 

### ISSUE THREAD

**Issue by JesseLovelace** [googleapis/google-auth-library-nodejs#1239]
A user of the cloud storage node library has reported an [issue](https://github.com/googleapis/nodejs-storage/issues/1550) when trying to sign URLs using Workload Identity Federation. The sign url feature of the library ultimately uses GoogleAuth.sign(), so in this case I think it should be resolving to the [recently implemented](https://github.com/googleapis/google-auth-library-nodejs/pull/1227/files) case for signing with impersonated credentials. Evidently, it *does* sign, it just produces a different signature than when the credentials and private key are used directly. Possibly some issue where the wrong email ends up getting used?

**Comment by andrewmcoupe** [comment]
> Are you sure they are using the expected service account for impersonation (the one they use in workload identity federation)? (the same one that has the necessary permission on the resource)

I can confirm I am using the expected service account, yes 👍

**Comment by andrewmcoupe** [comment]
Any update on this yet?

**Comment by bojeil-google** [comment]
Not yet. Will keep you posted.

**Comment by mattmelgard** [comment]
Is this something limited to Workload Identity Federation? I seem to be getting a 403 when generating a signed URL using "normal" Workload Identity as well:

```
{"level":"error","time":1634781291172,"pid":1,"hostname":"ovr-api-8698496c66-s7zwj","name":"ovr-api","name":"SigningError","stack":"Error: Unsuccessful response status code. Request failed with status code 403\n    at Gaxios._request (/app/node_modules/gaxios/build/src/gaxios.js:129:23)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async metadataAccessor (/app/node_modules/gcp-metadata/build/src/index.js:68:21)\n    at async GoogleAuth.getCredentialsAsync (/app/node_modules/google-auth-library/build/src/auth/googleauth.js:531:22)\n    at async GoogleAuth.sign (/app/node_modules/google-auth-library/build/src/auth/googleauth.js:646:23)\n    at async sign (/app/node_modules/@google-cloud/storage/build/src/signer.js:97:35)","type":"Error","msg":"Unsuccessful response status code. Request failed with status code 403"}
```
The versions I'm using are:

```
google-auth-library@7.6.2
@google-cloud/storage@5.13.0
```

**Comment by shaffeeullah** [comment]
@bojeil-google do you have an estimated timeline for this work?

**Comment by bojeil-google** [comment]
FYI @lsirac
