### ISSUE TITLE
Token used too late, 1632537218.865 > 1632491019:

### ISSUE THREAD

**Issue by ahuangege** [googleapis/google-auth-library-nodejs#1297]
```
const client = new OAuth2Client(CLIENT_ID);
async function verify() {
  const ticket = await client.verifyIdToken({
      idToken: token,
      audience: CLIENT_ID,  // Specify the CLIENT_ID of the app that accesses the backend
      // Or, if multiple clients access the backend:
      //[CLIENT_ID_1, CLIENT_ID_2, CLIENT_ID_3]
  });
  const payload = ticket.getPayload();
  const userid = payload['sub'];
  // If request specified a G Suite domain:
  // const domain = payload['hd'];
}
verify().catch(console.error);
```
I use this just like what google says. however, it returns error: Token used too late.  
Does anyone know how to solve?

**Comment by ahuangege** [comment]
```
const now = new Date().getTime() / 1000;


if (exp >= now + maxExpiry) {
    throw new Error('Expiration time too far in future: ' + JSON.stringify(payload));
}
const earliest = iat - OAuth2Client.CLOCK_SKEW_SECS_;
const latest = exp + OAuth2Client.CLOCK_SKEW_SECS_;
if (now < earliest) {
    throw new Error('Token used too early, ' +
        now +
        ' < ' +
        earliest +
        ': ' +
        JSON.stringify(payload));
}
if (now > latest) {
    throw new Error('Token used too late, ' +
        now +
        ' > ' +
        latest +
        ': ' +
        JSON.stringify(payload));
}
```
I see the source code.  `const now = new Date().getTime() / 1000;`   ，The reason is the time zone?

**Comment by shlomizadok** [comment]
Any resolution on this one?

**Comment by ahuangege** [comment]
Comment out the relevant code. But,&nbsp;It seems not for this reason.&nbsp;Later it seemed to be okay




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "googleapis/google-auth-library-nodejs"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月27日(星期一) 凌晨2:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [googleapis/google-auth-library-nodejs] Token used too late, 1632537218.865 &gt; 1632491019: (#1297)





 
Any resolution on this one?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by bcoe** [comment]
@shlomizadok @ahuangege `getTime()` should be timezone independent, my guess would be that it could actually be clock skew on the machine that was making the request, or perhaps just a hiccup.

@shlomizadok if you're continuing to bump into issues, check what your your time on the computer making the request, and see if it is slightly off?
