### ISSUE TITLE
Feature Request: AWS SDK v3 credentials support

### ISSUE THREAD

**Issue by LumaKernel** [googleapis/google-auth-library-nodejs#1320]
**Is your feature request related to a problem? Please describe.**
The AWS's new version of SDK `@aws-sdk/*` [![](https://img.shields.io/badge/-aws%2Faws--sdk--js--v3-%23000000?style=flat&logo=github)](https://github.com/aws/aws-sdk-js-v3) has new feature about credentials, `@aws-sdk/credentials-provider` [![](https://img.shields.io/badge/-doc-%23232F3E?style=flat&logo=amazon-aws)](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/modules/_aws_sdk_credential_providers.html) [![](https://img.shields.io/badge/npm-@aws--sdk%2Fcredential--providers-%23cb0000?style=flat&logo=npm)](https://www.npmjs.com/package/@aws-sdk/credential-providers).

This is providing credentials in consistent interface (`Credentials | CredentialsProvider`) for any authentication method. For example, if we want to use Workload Identity Federation in AWS Container (like ECS) environment, we cannot use `AwsClient` because there is no metadata endpoint. It's also the case for AWS Lambda.

Definition of `Credentials`:

https://github.com/aws/aws-sdk-js-v3/blob/main/packages/types/src/credentials.ts#L3-L27

Definition of `CredentialProvider`:

https://github.com/aws/aws-sdk-js-v3/blob/842e39638d994b518d6580dd979031c8be738017/packages/types/src/credentials.ts#L29

Definition of `Provider<T>`:

https://github.com/aws/aws-sdk-js-v3/blob/842e39638d994b518d6580dd979031c8be738017/packages/types/src/util.ts#L34-L43

 **Describe the solution you'd like**
I made a patch to support `Credentials | CredentialsProvider`. #1321
This is a refined version of [our quick implementation](https://github.com/violet-ts/violet/blob/main/pkg/api/src/service/firebase-admin/from-container-credentials.ts) (open source) for connecting from container credentials to firebase-admin through google-auth-library. It's working code in our preview environment. (It's open, if you need more detailed information about this, we can provide. )

 **Describe alternatives you've considered**
N/A

 **Additional context**
N/A

**Comment by bojeil-google** [comment]
He @LumaKernel, the library supports AWS environment variables for environments where the metadata server is not available: `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY`, `AWS_SESSION_TOKEN`, etc.

**Comment by bcoe** [comment]
@LumaKernel please let us know if @bojeil-google's suggestion doesn't work for you :ok_hand:

**Comment by clhuang** [comment]
I'd like to reopen this -- the suggestion to use AWS environment variables works in lambda, but it does not work in ECS or EKS environments. 

From the comments on #1321:
> We also have plans to support pluggable auth where you can have an external plugin provide AWS credentials for the libraries

is there any timeline on when this might be implemented?

**Comment by omerlh** [comment]
Hey @bcoe and @bojeil-google  I am trying something similar on EKS with [IRSA](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html), I did the following to plug-in AWS auth:

```javascript
import type { AwsSecurityCredentials, AwsSecurityCredentialsSupplier, ExternalAccountSupplierContext } from 'google-auth-library';
import { fromNodeProviderChain } from '@aws-sdk/credential-providers';

export const getAwsSecurityCredentialsSupplier = (): AwsSecurityCredentialsSupplier => ({
  getAwsRegion: async (_: ExternalAccountSupplierContext): Promise<string> => 'us-east-1',

  getAwsSecurityCredentials: async (_: ExternalAccountSupplierContext): Promise<AwsSecurityCredentials> => {
    const credentialsProvider = fromNodeProviderChain({});

    const credentials = await credentialsProvider();
    return credentials;
  },
});
```

But I am getting error I have no idea how to solve

Error code invalid_grant: Received invalid AWS response of type InvalidClientTokenId with error message: The security token included in the request is invalid

Can you please help me figure this out?

**Comment by guyelia** [comment]
> Hey [@bcoe](https://github.com/bcoe) and [@bojeil-google](https://github.com/bojeil-google) I am trying something similar on EKS with [IRSA](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html), I did the following to plug-in AWS auth:
> 
> import type { AwsSecurityCredentials, AwsSecurityCredentialsSupplier, ExternalAccountSupplierContext } from 'google-auth-library';
> import { fromNodeProviderChain } from '@aws-sdk/credential-providers';
> 
> export const getAwsSecurityCredentialsSupplier = (): AwsSecurityCredentialsSupplier => ({
>   getAwsRegion: async (_: ExternalAccountSupplierContext): Promise<string> => 'us-east-1',
> 
>   getAwsSecurityCredentials: async (_: ExternalAccountSupplierContext): Promise<AwsSecurityCredentials> => {
>     const credentialsProvider = fromNodeProviderChain({});
> 
>     const credentials = await credentialsProvider();
>     return credentials;
>   },
> });
> But I am getting error I have no idea how to solve
> 
> Error code invalid_grant: Received invalid AWS response of type InvalidClientTokenId with error message: The security token included in the request is invalid
> 
> Can you please help me figure this out?

Same here, same setup with the same issue @bcoe
