### ISSUE TITLE
await for emit('tokens')

### ISSUE THREAD

**Issue by tripodsan** [googleapis/google-auth-library-nodejs#1323]
**Is your feature request related to a problem? Please describe.**

when implementing a token cache, using the `on('tokens')` event is great. unfortunately, this does not work for async caches, because the `emit()` call is not awaited.

 **Describe the solution you'd like**

ideally, the code would `await` the call:

```
await this.emit('tokens', tokens);
```

here:

- https://github.com/googleapis/google-auth-library-nodejs/blob/5ed910513451c82e2551777a3e2212964799ef8e/src/auth/oauth2client.ts#L642
- https://github.com/googleapis/google-auth-library-nodejs/blob/5ed910513451c82e2551777a3e2212964799ef8e/src/auth/oauth2client.ts#L705

 **Describe alternatives you've considered**

we can hack around by overriding the internal methods that alter the refreshtoken, or proxy all methods and see if the `tokens` event was emitted. but this is a bit hack.

**Comment by bcoe** [comment]
Closing based on discussion in PR, thanks for your work digging into this @tripodsan.
