### ISSUE TITLE
Web server application vs. Server to Server application – core difference ?

### ISSUE THREAD

**Issue by projektorius96** [googleapis/google-auth-library-nodejs#1331]
Hi, whilst reading [this](https://developers.google.com/identity/protocols/oauth2#libraries) I've came up with **A) & B)**
Can someone explain the core difference between **A)** [Web Server Applications](https://developers.google.com/identity/protocols/oauth2/web-server) & **B)** [Server to Server Applications](https://developers.google.com/identity/protocols/oauth2/service-account) as for OAuth2 ? Both refer to this repo . I need to know the core difference so to know which documentation consume as a guidance . Thanks in advance !

**Comment by sofisl** [comment]
@projektorius96, the main difference is that A uses oAuth2 sequence, including obtaining a code, and trading that code for an auth token. B does not use oAuth interaction, just a premade service account.

I think, if I were to put it more succinctly, A would be best for end-user situations, whereas B is helpful where you have an actor acting as a service account (i.e., not an end user).

Thanks @alexander-fenster for the information!

**Comment by projektorius96** [comment]
Hey . @sofisl & @alexander-fenster thanks a lot ! ♥
