### ISSUE TITLE
how to auto renew access token

### ISSUE THREAD

**Issue by chaowenGUO** [googleapis/google-auth-library-nodejs#1332]
**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Hi:

From https://www.npmjs.com/package/google-auth-library, I use the following example:

```
const {auth} = require('google-auth-library'); // load the environment variable with our keys 
const keysEnvVar = process.env['CREDS']; 
if (!keysEnvVar) { 
  throw new Error('The $CREDS environment variable was not found!'); 
}
const keys = JSON.parse(keysEnvVar);
async function main() {
  // load the JWT or UserRefreshClient from the keys 
  const client = auth.fromJSON(keys);
  client.scopes = ['https://www.googleapis.com/auth/cloud-platform'];
  const url = `https://dns.googleapis.com/dns/v1/projects/${keys.project_id}`;
  const res = await client.request({url});
}
```

the problem is client.credentials.access_token will expire in 1 hour. 

I also see:

Handling token events
This library will automatically obtain an access_token, and automatically refresh the access_token if a refresh_token is present. The refresh_token is only returned on the first authorization, so if you want to make sure you store it safely. An easy way to make sure you always store the most recent tokens is to use the tokens event:

```
const client = await auth.getClient();
client.on('tokens', (tokens) => {
  if (tokens.refresh_token) {
    // store the refresh_token in my database!
    console.log(tokens.refresh_token);
  }
  console.log(tokens.access_token);

});
const url = `https://dns.googleapis.com/dns/v1/projects/${projectId}`;
const res = await client.request({ url }); // The `tokens` event would now be raised if this was the first request
```

But how to combine these two examples together to let client.credentials.access_token auto reflesh?

I try to ask the question in Google Cloud Developers <google-cloud-dev@googlegroups.com>, but they tell me to ask question here.

**Comment by chingor13** [comment]
Most built-in auth types know how to refresh their own tokens before expiry - the exception being direct access tokens. If the credentials loaded via JSON in the first example are service account key or user credentials (with refresh token), it should automatically refresh.

**Comment by chaowenGUO** [comment]
I use the first case and service account key and use them in an application. The application will call gcloud api in every 5 minutes. In the first hour, it works ok. But when one hour pass, it shows:

401 ***
  error: ***

node:internal/process/esm_loader:94
    internalBinding('errors').triggerUncaughtException(
    code: 401,
                              ^
    message: 'Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.',
true
    status: 'UNAUTHENTICATED',
(Use `node --trace-uncaught ...` to show where the exception was thrown)
    details: [ [Object] ]

  ***

**Comment by chaowenGUO** [comment]
Any idea how to deal with my case?

**Comment by chingor13** [comment]
Your code in `main.js` is fetching a token once (because it's making an API call https://github.com/chaowenGUOorg/audio/blob/0cd43fd26cfb1062c38142fa0856ca80fa2ac632/main.js#L8) and then re-using that token for the rest of the requests.

If you use your auth client to make the request, it will refresh its token. Can you try making the [subsequent requests](https://github.com/chaowenGUOorg/audio/blob/0cd43fd26cfb1062c38142fa0856ca80fa2ac632/main.js#L15) with [`client.request`](https://cloud.google.com/nodejs/docs/reference/google-auth-library/latest/google-auth-library/oauth2client#google_auth_library_OAuth2Client_request_member_1_) rather than `fetch`?

**Comment by chaowenGUO** [comment]
Thank you problem solved
