### ISSUE TITLE
Revoking Access Credentials for a particular scope is affecting other scopes

### ISSUE THREAD

**Issue by hashweather** [googleapis/google-auth-library-nodejs#1338]
My app is requesting for two different scopes separately.

The first set of scopes is this:
 ```
const scopes = [
            'https://www.googleapis.com/auth/youtube',
            'https://www.googleapis.com/auth/youtube.upload',
            'https://www.googleapis.com/auth/youtube.force-ssl',
            'https://www.googleapis.com/auth/userinfo.profile'
        ];
```
Which was requested for separately on click of a button and the returned token saved separately.

Then on click of another button, I requested for another separate scopes below:
```
 const scopes = [
            'https://www.googleapis.com/auth/business.manage',
            'https://www.googleapis.com/auth/userinfo.profile'
        ];
```

Which returned token was also saved separately.

Now when I revoke credentials for YouTube scopes using the code below
```
       const youTubeAccessToken = ///Previously saved token Retrieved from database;
       let oauth2Client = new google.auth.OAuth2(
            process.env.GOOGLE_APP_CLIENT_ID,
            process.env.GOOGLE_APP_CLIENT_SECRET,
            redirectUri
        );
        oauth2Client.setCredentials(youTubeAccessToken );
        await oauth2Client.revokeCredentials(); //This seems to also automatically revoke other scopes other than Youtube. Weird!

```

I noticed that even Google My Business access token was revoked and becomes invalid.

Which leaves me with the question, does Google merge the scopes and uses only one access token whenever new scopes are requested or is there a workaround this?

**Comment by chingor13** [comment]
It looks like this is how Google's auth server handles "incremental authorization". More info can be found at: https://developers.google.com/identity/protocols/oauth2/web-server#incrementalAuth

Specifically:

> If you revoke a token that represents a combined authorization, access to all of that authorization's scopes on behalf of the associated user are revoked simultaneously.
