### ISSUE TITLE
Auth library serverless example is misleading in the documentation for cloud functions authentication

### ISSUE THREAD

**Issue by guibirow** [googleapis/google-auth-library-nodejs#1339]
The [cloud functions documentation ](https://cloud.google.com/functions/docs/securing/authenticating) uses the nodejs [auth library serverless example](https://github.com/googleapis/google-auth-library-nodejs/blob/7b6c04185088b028af31a22c88ad5d78e9f6f2fb/samples/idtokens-serverless.js#L42) to demonstrate how to authenticate when invoking a function with an IdToken.

Unfortunately this causes a lot of confusion because the example is not interchangeable.

Cloud functions audience requires the function name to be present when generating the token, but the example uses only the host name, which is only valid for cloud run.

Every single week I provide support to engineers struggling to authenticate with cloud functions and the I can guarantee majority of the issues is because they are using this misleading example, causing a lot of pain for them (and for me 😆).

To make things worse, some of them are adamant to believe us when we say the documentation is wrong.

The example below:
```
  // Example: https://my-cloud-run-service.run.app/
  const targetAudience = 'https://TARGET_HOSTNAME/';  // <-- wrong example
  const {GoogleAuth} = require('google-auth-library');
  const auth = new GoogleAuth();

  async function request() {
    console.info(`request ${url} with target audience ${targetAudience}`);
    const client = await auth.getIdTokenClient(targetAudience);
    const res = await client.request({url});
    console.info(res.data);
  }
```

should be as follow for cloud functions

```
  // Example: https://project-region-projectid.cloudfunctions.net/myFunction
  const targetAudience = 'https://TARGET_HOSTNAME/function-name';  // <-- right example for cloud functions
  const {GoogleAuth} = require('google-auth-library');
  const auth = new GoogleAuth();

  async function request() {
    console.info(`request ${url} with target audience ${targetAudience}`);
    const client = await auth.getIdTokenClient(targetAudience);
    const res = await client.request({url});
    console.info(res.data);
  }
```

**Comment by guibirow** [comment]
That was quick. Thanks for the quick resolution.

One last question, is there anything needed to update the docs?
I see it still showing the old example.

**Comment by averikitsch** [comment]
The docs page is now updated. Thanks!
