### ISSUE TITLE
`g_csrf_token` is not transmitted over subdomains for Google Sign In library

### ISSUE THREAD

**Issue by SheaBelsky** [googleapis/google-auth-library-nodejs#1345]
1) Is this a client library issue or a product issue?
This is the client library for `google-auth-library`. If my frontend is on `https://website.com` and my backend is hosted on `https://api.website.com`, the `g_csrf_token` cookie is not transmitted to my backend because of the `HostOnly` aspect of the cookie. As defined by the documentation at [this page](https://developers.google.com/identity/gsi/web/reference/html-reference#data-state_cookie_domain), the `state_cookie_domain` parameter does not allow this to work across subdomains when the cookie is actually transmitted to the backend. I am using the `redirect` flow in this case.

2) Did someone already solve this?
No. An identical issue was posted but was closed: https://github.com/googleapis/google-auth-library-nodejs/issues/1241. One person solved it by modifying their web server's proxy, but this is not a long-term solution when the Google libraries should support this use case out of the box.

3) Do you have a support contract?
I do not have a support contact.

#### Environment details

  - OS: macOS 12.1
  - Node.js version: 14.15.3
  - npm version: 6.14.9
  - `google-auth-library` version: 7.11

#### Steps to reproduce

  1. Set up Google Sign In, following the steps described [here](https://developers.google.com/identity/gsi/web/guides/overview), and using the `redirect` flow to redirect a user to a backend service after authorization in Google
  2. Deploy the frontend (`https://example.com`)
  3. Set up a separate backend service, on a subdomain , to handle the Google Sign In response (`https://api.example.com`)
  4. Attempt to sign into `example.com` with Google Sign In
  5. Observe how the `g_csrf_token` property is missing from cookies in the request

**Comment by thurdev** [comment]
This still happening 😭 on new google auth library.

Thank you for letting me now by your title "g_csrf_token is not transmitted over subdomains for Google Sign In library"

**Comment by visitjk** [comment]
Any update on this?

**Comment by wandersonlimasc** [comment]
I'm facing it just on mobile, in desktop it came well.

// doing over desktop in chrome
req.cookie = {
  myCustomCookie: 'myValue',
  g_csrf_token: '4bdf0695c6786eb2'
}

// doing over mobile using chrome as well
req.cookie = [Object: null prototype] {}

**Comment by visitjk** [comment]
If you're using passport in your proxy to authenticate the client.
You can try this option on the server `verifyCsrfToken` .

```
passport.use(
  new GoogleOneTapStrategy(
    {
      clientID: GOOGLE_CLIENT_ID, 
      clientSecret: GOOGLE_CLIENT_SECRET,
      verifyCsrfToken: false, // whether to validate the csrf token or not
    },
    function (profile, done) {

    }
  )
);

````

**Comment by danielbankhead** [comment]
Hey folks, the issue reported is for the [Sign In With Google](https://developers.google.com/identity/gsi/web/guides/overview) API, which is a different library. I would suggest filling a **detailed** request via the Send Feedback button [here](https://developers.google.com/identity/gsi/web/reference/html-reference).

I wish I were more familiar with that particular library to help.
