### ISSUE TITLE
refreshAccessToken deprecated in favor of getRequestHeaders - mistake?

### ISSUE THREAD

**Issue by tjwudi** [googleapis/google-auth-library-nodejs#1355]
https://github.com/googleapis/google-auth-library-nodejs/blob/c23ae13863f38d43d575b8a930fa701720fcdc88/src/auth/oauth2client.ts#L710-L714

The code documentation shows that `refreshAccessToken` is deprecated in favor of `getRequestHeaders`. These two methods don't look seemingly related. Was this deprecation a mistake?

**Comment by bcoe** [comment]
@tjwudi using `getRequestHeaders` will automatically refresh the access token, I believe this note is probably for implementers like `gRPC` where they call `getRequestHeaders` to populate the access token on a request -- just a note that the upstream implementer need no longer call this method.

**Comment by tjwudi** [comment]
Thanks @bcoe. The implicit behavior of `getRequestHeaders` can be quite confusing to API consumers who wants to store updated access token.

Proposal: I found out that `getAccessTokenAsync` does the actual work that refreshes access token. It updates `client.credentials` with the new tokens when refreshed. Should it be the alternative to `refreshAccessToken` as it seems more relevant and straightforward?

https://github.com/googleapis/google-auth-library-nodejs/blob/main/src/auth/oauth2client.ts#L758-L785

**Comment by bcoe** [comment]
@tjwudi I think if you want to store tokens, your best bet is:

```
client.on('tokens', (tokens) => {
  if (tokens.refresh_token) {
    // store the refresh_token in my database!
    console.log(tokens.refresh_token);
  }
  console.log(tokens.access_token);
});
```

This should emit an event whenever the token is refreshed, could this work for you?

**Comment by bcoe** [comment]
@tjwudi let us know if there are any issues using the `client.on('tokens')` functionality to detect and store an updated token. If there are bugs with this interface you're bumping into, we can fix them -- but, going forward this is the preferred interface for detcting a new token has been emitted.
