### ISSUE TITLE
Missing dependencies when installing with Node 16

### ISSUE THREAD

**Issue by sizlo** [googleapis/google-auth-library-nodejs#1360]
When trying to use google-auth-library for a react app I am getting lots of errors that indicate missing dependencies. The errors are in the following format:

```
Module not found: Error: Can't resolve 'buffer' in '/private/tmp/minimal-example/node_modules/buffer-equal-constant-time'
```

The error messages include details on how to add a polyfill, but after going through each of these and adding the suggested polyfill the library still does not work, outputting the following error to the console:

```
GET http://metadata.google.internal./computeMetadata/v1/instance net::ERR_NAME_NOT_RESOLVED
```

#### Environment details

  - OS: macOs 12.0
  - Node.js version: 16.13.2
  - npm version: 8.1.2
  - `google-auth-library` version: 7.11.0

#### Steps to reproduce

  1. Install Node 16.13.2
  2. Create a react app `npx create-react-app minimal-example`
  3. Enter directory for the created project `cd minimal-example`
  4. Install google-auth-library `npm install google-auth-library --save`
  5. Add the following code to `./src/App.js`
    `const {GoogleAuth} = require('google-auth-library');`
  6. Start the development server `npm start`
  7. Observe errors

**Comment by bcoe** [comment]
closing in favor of our catch all issue:

https://github.com/googleapis/google-cloud-node/issues/2933

---

We do not at this time support the browser without some manual work on the user's part (discussed in the issue above). We are, however, looking at adding this functionality.

May I ask what APIs you're hoping to interact with from the frontend?
