### ISSUE TITLE
Implement Retryable interface for token endpoint requests

### ISSUE THREAD

**Issue by TimurSadykov** [googleapis/google-auth-library-nodejs#1366]
Currently, clients do not have a good way to distinguish retryable errors and implement custom retry strategies. Sometimes this causes infinite retries like here: https://github.com/nwbirnie/gapic-oauth-invalid-hangs. Please prioritize the fix if similar infinite retry is repro here as well.

More details in the doc: go/auth-correct-retry

**Comment by TimurSadykov** [comment]
@danielbankhead is it still open or fixed with the attached PR?

**Comment by danielbankhead** [comment]
@TimurSadykov Still open, made some progress in the other PR
