### ISSUE TITLE
Retire LRU dependency

### ISSUE THREAD

**Issue by bcoe** [googleapis/google-auth-library-nodejs#1368]
The LRU dependency API surface has changed signficnatly between v6 and v7, is it worth migrating to a new version or should we try to implement similar behavior ourselves?

https://github.com/googleapis/google-auth-library-nodejs/pull/1359

**Comment by danielbankhead** [comment]
Opted to roll our own LRU cache:
- https://github.com/googleapis/google-auth-library-nodejs/pull/1659
