### ISSUE TITLE
Error in google-gax/build/src/clientInterface.d.ts 7.13.0

### ISSUE THREAD

**Issue by fjrdguez** [googleapis/google-auth-library-nodejs#1370]
interface ClientOptions exteds by GrpcClientOptions and GoogleAuthOptions.

GrpcClientOptions has a optional  property auth of type GoogleAuth
but
GootleAuthOptions has a optional property auth of type AuthClient

when transpile crash:

node_modules/google-gax/build/src/clientInterface.d.ts:7:18 - error TS2320: Interface 'ClientOptions' cannot simultaneously extend types 'GrpcClientOptions' and 'GoogleAuthOptions'.
  Named property 'auth' of types 'GrpcClientOptions' and 'GoogleAuthOptions' are not identical.

7 export interface ClientOptions extends GrpcClientOptions, GoogleAuthOptions, ClientStubOptions {
                   ~~~~~~~~~~~~~

node_modules/google-gax/build/src/grpc.d.ts:24:18 - error TS2430: Interface 'GrpcClientOptions' incorrectly extends interface 'GoogleAuthOptions'.
  Types of property 'auth' are incompatible.
    Type 'GoogleAuth' is missing the following properties from type 'AuthClient': on, credentials, eagerRefreshThresholdMillis, forceRefreshOnFailure, and 16 more.

24 export interface GrpcClientOptions extends GoogleAuthOptions {
                    ~~~~~~~~~~~~~~~~~

[20:46:22] Found 2 errors. Watching for file changes.

best regards, Paco Rodriguez

**Comment by dimavedenyapin** [comment]
This part of code is breaking my build. 10 hours ago the build stopped working.
I am using the following packages:
```
		"@google-cloud/bigquery": "^5.9.3",
		"@google-cloud/firestore": "5.0.1",
		"@google-cloud/functions-framework": "2.1.0",
		"@google-cloud/pubsub": "^2.12.0",
		"@google-cloud/secret-manager": "3.10.1",
		"@google-cloud/storage": "^5.16.1",
```

Error that I am getting:
```
node_modules/@google-cloud/pubsub/node_modules/google-gax/build/src/clientInterface.d.ts:7:18 - error TS2320: Interface 'ClientOptions' cannot simultaneously extend types 'GrpcClientOptions' and 'GoogleAuthOptions'.
  Named property 'auth' of types 'GrpcClientOptions' and 'GoogleAuthOptions' are not identical.

7 export interface ClientOptions extends GrpcClientOptions, GoogleAuthOptions, ClientStubOptions {
                   ~~~~~~~~~~~~~

node_modules/@google-cloud/pubsub/node_modules/google-gax/build/src/grpc.d.ts:24:18 - error TS2430: Interface 'GrpcClientOptions' incorrectly extends interface 'GoogleAuthOptions'.
  Types of property 'auth' are incompatible.
    Type 'GoogleAuth | undefined' is not assignable to type 'AuthClient | undefined'.
      Type 'GoogleAuth' is missing the following properties from type 'AuthClient': on, credentials, eagerRefreshThresholdMillis, forceRefreshOnFailure, and 16 more.

24 export interface GrpcClientOptions extends GoogleAuthOptions {
                    ~~~~~~~~~~~~~~~~~

node_modules/google-gax/build/src/clientInterface.d.ts:7:18 - error TS2320: Interface 'ClientOptions' cannot simultaneously extend types 'GrpcClientOptions' and 'GoogleAuthOptions'.
  Named property 'auth' of types 'GrpcClientOptions' and 'GoogleAuthOptions' are not identical.

7 export interface ClientOptions extends GrpcClientOptions, GoogleAuthOptions, ClientStubOptions {
                   ~~~~~~~~~~~~~

node_modules/google-gax/build/src/grpc.d.ts:24:18 - error TS2430: Interface 'GrpcClientOptions' incorrectly extends interface 'GoogleAuthOptions'.
  Types of property 'auth' are incompatible.
    Type 'GoogleAuth | undefined' is not assignable to type 'AuthClient | undefined'.

24 export interface GrpcClientOptions extends GoogleAuthOptions {

```

Another related issue:
https://github.com/firebase/firebase-tools/issues/4181

**Comment by fjrdguez** [comment]
I have been provisionally solved by changing the package.json, forcing a previous version, if you imply it, it Elemina the package-lock.json and performs an NPM i again.

    "google-auth-library": "7.11.0",
    "firebase-admin": "10.0.1",

If you did not have Google-Auth-Library at the package.json, include it with version 7.11.0 to force that it does not charge the ultra update that is the one that carries the error

**Comment by bcoe** [comment]
@fjrdguez @dimavedenyapin @fjrdguez `7.13.0` was briefly released with a type issue, and then rolled back to `7.12.0`.

If you install `7.12.0`, it will correct the issue for you.

**Comment by mjohnsonengr** [comment]
This appears to happen in 7.14.0 as well.  Reverting to 7.12.0 fixed it for me.

Looks like 7.14.0 was released by a bot. Has the underlying issue been fixed?
