### ISSUE TITLE
Add sample + sample integration test for auth library's most common consumers

### ISSUE THREAD

**Issue by bcoe** [googleapis/google-auth-library-nodejs#1373]
Add an integration test for some of `google-auth-library`'s most important downstream consumers:

* nodejs-googleapis-common.
* nodejs-common.
* gax.

## Open question

If we do intend to take a breaking change, how can we do so without ignoring these broken integration tests (🐔  or 🥚  problem).

**Comment by danielbankhead** [comment]
[Internal]

The root issue for this request will be resolved via the resolution of: go/nodejs-mono-repo

Closing this for now.
