### ISSUE TITLE
Support ADC json when impersonating service user

### ISSUE THREAD

**Issue by bailer** [googleapis/google-auth-library-nodejs#1382]
**Is your feature request related to a problem? Please describe.**
When generating an ADC json you are able to impersonate a service user which outputs a JSON file that is not currently handled.
e.g. 
```
gcloud auth application-default login --impersonate-service-account=server@example.iam.gserviceaccount.com
```
Which generates the following JSON format: 
```
{
  "delegates": [],
  "service_account_impersonation_url": "https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/server@example.iam.gserviceaccount.com:generateAccessToken",
  "source_credentials": {
    "client_id": "1234567890.apps.googleusercontent.com",
    "client_secret": "<secret>",
    "refresh_token": "<refrest_token>",
    "type": "authorized_user"
  },
  "type": "impersonated_service_account"
}
```
Currently the library throws the following error when doing this:
`The incoming JSON object does not contain a client_email field`
 **Describe the solution you'd like**
I'd like the library to detect this format and handle it correctly
 **Describe alternatives you've considered**
I can manually alter the file by putting the contents of `source_credentials` at the top level of the JSON (though unsure if this has any side-effect). I can also generate a key for the service user but since it's not recommended, impersonating the service user and using ADC would be preferred.
 **Additional context**
I'm very new to GCP and authentication in that regard and was trying to set up local development without generating keys but still using a service user. I found that you can impersonate a service user while generating the ADC JSON but it's not working with this library. I found that e.g. `google-auth-library-python` supports this format so I'm thinking the node library also should.

**Comment by imathews** [comment]
Just a friendly +1 on this — I'm running into the same issue with `google-auth-node`, which is preventing us from utilizing impersonated service accounts in our local dev environment.
