### ISSUE TITLE
Invoking a google cloud function from an app engine 

### ISSUE THREAD

**Issue by Pixelatex** [googleapis/google-auth-library-nodejs#1432]
- What you're trying to do
My app engine running a nodeJS application should be able to send a GET request to my google cloud function.

- What code you've already tried

```javascript
const url = process.env.SERVICE_ACCOUNT;
const audience = process.env.FUNCTION_GETREPORT_URI;

const { GoogleAuth } = require("google-auth-library");
const auth = new GoogleAuth();

async function getGoogleIdToken() {
  try {
    const client = await auth.getIdTokenClient(audience);
    const res = await client.request({ url });
    console.log(res.data);
    return res.data;
  } catch (e) {
    console.log(e, "?");
    return null;
  }
}

  const ID_TOKEN = await getGoogleIdToken();

    const file = axios
      .get(
        `${process.env.FUNCTION_GETREPORT_URI}?start=${start}&end=${end}&brand=${projectID}`,
        {
          responseType: "arraybuffer",
          Authorization: `Bearer ${ID_TOKEN}`,
        }
      )

```

- Any error messages you're getting
I keep getting 403 forbiddens that I'm not allowed to fetch an id token for that service. I did give my app engine default service account the cloud invoker role and it's been added in the permissions tab of the function.

At this point, I'm not sure what's going on and I'm confused what the issue is.

**Comment by danielbankhead** [comment]
Hey @Pixelatex, are you still experiencing this issue?

We've recently updated the id token sample:

https://github.com/googleapis/google-auth-library-nodejs/blob/00d6135f35a1aa193d50fad6b3ec28a7fda9df66/samples/idtokens-serverless.js#L33-L72

Let me know if this helps.

**Comment by mheripsos** [comment]
I've been struggling with this library too and going to post a separate issue that I think is unrelated to this one. But I wanted to drop in and recommend that you may need to add `Service Account Token Creator` role to your service account.
