### ISSUE TITLE
`Impersonated` credentials should implement `sign()` capability

### ISSUE THREAD

**Issue by salrashid123** [googleapis/google-auth-library-nodejs#1443]
`Impersonated` client does not have any way to generate signedurl or to signbytes.

This credential type uses the IAM api to perform acquire various token types like `generateAccessToken`,  `generateIdToken` (ref: https://github.com/googleapis/google-auth-library-nodejs/issues/1318), 

The ability to sign on behalf of the impersonated svc account through the iam api would use the [signBlob](https://cloud.google.com/iam/docs/reference/credentials/rest/v1/projects.serviceAccounts/signBlob) API.

This feaure request is to surface a `sign` interface such that it can be used standalone or though a client such as `storage` and allow generation of signedURLs.

Essentially this flow will allow
*  `user -> impersonate svc1 --> generate signedurl as svc1` 

---

if it helps, I have a sample working below but i had to make some edits 

`A)` https://github.com/googleapis/google-auth-library-nodejs/blob/main/src/auth/googleauth.ts#L814

```node
async getCredentialsAsync() {
    const client = await this.getClient();

    if (client instanceof impersonated_1.Impersonated) {
        // not really used.  Impersonated uses the service accounts email
        // it got initialized with
        return { client_email: client.targetPrincipal }
    }
  // ...
  // ...
}
```

`B)` https://github.com/googleapis/google-auth-library-nodejs/blob/main/src/auth/googleauth.ts#L946

```node
async sign(data) {
    const client = await this.getClient();
    
    if (client instanceof impersonated_1.Impersonated) {
        return client.sign(data);
    }
  // ...
  // ...
}
```

`C)` https://github.com/googleapis/google-auth-library-nodejs/blob/main/src/auth/impersonated.ts

```node
/**
 * Signs some bytes.
 * @param blobToSign Sign bytes.
 */
     async sign(blobToSign) {

        try {
            await this.sourceClient.getAccessToken();
            const name = `projects/-/serviceAccounts/${this.targetPrincipal}`;
            const u = `${this.endpoint}/v1/${name}:signBlob`;
            const body = {
                delegates: this.delegates,
                payload: Buffer.from(blobToSign).toString('base64')
            };
            const res = await this.sourceClient.request({
                url: u,
                data: body,
                method: 'POST',
            });
            const tokenResponse = res.data;
            return tokenResponse.signedBlob
        }
        catch (error) {

        }
    }    
```

##### Usage

```node
const { GoogleAuth, Impersonated } = require('google-auth-library');
const { Storage } = require('@google-cloud/storage');

async function main() {
  const scopes = 'https://www.googleapis.com/auth/cloud-platform'
  // get source credentials
  const auth = new GoogleAuth({
    scopes: scopes
  });
  const client = await auth.getClient();

  // First impersonate
  let targetPrincipal = 'target-serviceaccount@fabled-ray-104117.iam.gserviceaccount.com'
  let targetClient = new Impersonated({
    sourceClient: client,
    targetPrincipal: targetPrincipal,
    lifetime: 30,
    delegates: [],
    targetScopes: [scopes]
  });

  // test sign
  //console.log(await targetClient.sign("foo"));

  let projectId = 'fabled-ray-104117'
  let bucketName = 'fabled-ray-104117-test'

  // use the impersonated creds to bootstrap a storage client
  const storageOptions = {
    projectId,
    authClient: targetClient,
  };
  const storage = new Storage(storageOptions);

  // ####### GCS SignedURL
  const signOptions = {
    version: 'v4',
    action: 'read',
    expires: Date.now() + 15 * 60 * 1000, // 15 minutes
  };

  const  su = await storage
    .bucket(bucketName)
    .file('foo.txt')
    .getSignedUrl(signOptions);
  console.log(su);
}
main().catch(console.error);
```

---

ref https://github.com/googleapis/google-auth-library-nodejs/issues/1210
[ Google Cloud Storage SignedURL with Cloud Run, Cloud Functions and GCE VMs](https://blog.salrashid.dev/articles/2021/cloud_sdk_missing_manual/gcs_signedurl/)

@danielbankhead, @FrodoTheTrue, @m0ar

**Comment by TheXienator** [comment]
I am having the same issue as salrashid and I have tried the fixes he suggests and it does make the signedUrls work with an impersonated client

**Comment by howlettga** [comment]
This seems like an important limitation of the google auth library. I need to impersonate a service account to develop locally for servers I will deploy on the google cloud platform. Modifying and complicating the source code in order to authenticate locally when the production environment should function for signing isn't an approach I want to be forced into.

**Comment by williamatpaper** [comment]
Would also love to see this implemented, I'm in the same situation as @howlettga.

**Comment by lox** [comment]
After some experimentation, I was able to get V4 signatures working using impersonated credentials. 

I wanted to be able to use my regular non-impersonated ADC credentials and then impersonate at runtime. 

I took created the JSON structure and set it in a temp file in GOOGLE_APPLICATION_DEFAULT:

```
{
    delegates: [],
    service_account_impersonation_url: 'https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/${serviceAccount}:generateAccessToken',
    source_credentials: {
       .. dynamically loaded from ~/.config/gcloud/application_default_credentials.json
    },
    client_email: ${serviceAccount},
    type: 'impersonated_service_account'
  }
```

Seems to work with Storage.
