### ISSUE TITLE
Addmessage endpoint gives error in message type 

### ISSUE THREAD

**Issue by Eleftheria-99** [googleapis/google-auth-library-nodejs#1445]
Hello,
I am trying to use this endpoint : https://developers.google.com/wallet/tickets/events/rest/v1/eventticketobject/addmessage, in order to send a message to the user that has added the pass ij the GPay. I am building the message body like this :

```
 let add_message_body = {};
    add_message_body = {
        message: {
            kind: "walletobjects#walletObjectMessage",
            header: header,
            body: body,
            id: message_id,
            messageType: { type: "string", enum: ["TEXT"] }
        }
    }

```
 and I am always getting this error :

```
  code: 400,
   errors: [
     {
         message: "Invalid value at 'add_message_request.message' (message_type), Starting an object on a scalar field",
         reason: 'invalid'
     }
  ]
``` 
Is there an other way to use enum in json ?

**Comment by danielbankhead** [comment]
Hey @Eleftheria-99, although this isn't an Auth-related issue, the `message` property should be `messages` - an array of objects: https://developers.google.com/wallet/tickets/events/rest/v1/eventticketobject#resource:-eventticketobject
