### ISSUE TITLE
Type inconsistency

### ISSUE THREAD

**Issue by chaim0m** [googleapis/google-auth-library-nodejs#1483]
https://github.com/googleapis/google-auth-library-nodejs/blob/89daaac8e1230935ed80733ac9c2cd89079e2f04/samples/idTokenFromServiceAccount.js#L47

The type does not contain this fuction something seems to be incorrect here.

**Comment by danielbankhead** [comment]
Thanks for raising this issue @chaim0m, I will provide a fix shortly.
