### ISSUE TITLE
Unable to get ID Token from ID Token Client due to 404 error

### ISSUE THREAD

**Issue by davebenson** [googleapis/google-auth-library-nodejs#1492]
1) Is this a client library issue or a product issue?
This is the client library for google-auth-library-nodejs. We will only be able to assist with issues that pertain to the behaviors of this library. If the issue you're experiencing is due to the behavior of the product itself, please visit the [ Support page]() to reach the most relevant engineers.

If the support paths suggested above still do not result in a resolution, please provide the following details.

#### Environment details

  - OS: mac, linux
  - Node.js version: 16.14.2
  - npm version: 8.19.2
  - `google-auth-library` version: 7.14.1

#### Steps to reproduce
The following program gives me a 404 error trying to get an identity token:

```
import {GoogleAuth} from 'google-auth-library';
import util from 'node:util';

const credentials = {private JSON (Service-Account Key)};

async function main() {
  const url = 'https://XXX-wl.a.run.app';
  const auth = new GoogleAuth({credentials});
  const client = await auth.getIdTokenClient(url);
  // The next line fails with a 404 error
  const res = await client.request({url});
  console.log(`res = ${res}`);
  console.log(res.data);
}

main().catch(console.error);
```
it seems to be almost identity to the example.  How can i debug this?
  1. ?
  2. ?

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by danielbankhead** [comment]
Hey @davebenson, I've verified the `getIdTokenClient` functionality is working fine. It looks like you're using Cloud Run, here's how the target audience and URLs should be set:

https://github.com/googleapis/google-auth-library-nodejs/blob/22de7040690fd11dca32b6a46585404c97233ff6/samples/idtokens-serverless.js#L39-L45
