### ISSUE TITLE
difference between OAuth2Client(CLIENT_ID) vs. OAuth2Client()?

### ISSUE THREAD

**Issue by rollerman111** [googleapis/google-auth-library-nodejs#1497]
I use this library to verify id token for google login (the only thing I'm using it for). I followed this documentation for the backend auth 
https://developers.google.com/identity/sign-in/web/backend-auth
This is the code snippet given on the webpage:
```
const {OAuth2Client} = require('google-auth-library');
const client = new OAuth2Client(CLIENT_ID);
async function verify() {
  const ticket = await client.verifyIdToken({
      idToken: token,
      audience: CLIENT_ID,  // Specify the CLIENT_ID of the app that accesses the backend
      // Or, if multiple clients access the backend:
      //[CLIENT_ID_1, CLIENT_ID_2, CLIENT_ID_3]
  });
  const payload = ticket.getPayload();
}
```

I have an hybrid app (web, ios, android) that share the same backend, so in my code I set the audience `[CLIENT_ID_1, CLIENT_ID_2, CLIENT_ID_3]` where 1 is my webapp, 2 is ios, and 3 is android. 

What client_id is suppose to be in this line in that case? Does it matter?

    const client = new OAuth2Client(CLIENT_ID);

This is my full code:

```
const { OAuth2Client } = require('google-auth-library');
const client = new OAuth2Client();
async function verify(token) {
  const ticket = await client.verifyIdToken({
    idToken: token,
    audience: [process.env.CLIENT_ID_1, process.env.CLIENT_ID_2, process.env.CLIENT_ID_3]
  });
  const payload = ticket.getPayload();
  return payload;
}
```

There is no error and everything works by the way. I'm just making sure if I need to specify a client id for OAuth2Client or not? Also, I'm not using the google refresh token instead using our own jwt, we're just validating if the google id token is correct then creating account based on payload values.

**Comment by fjavierv** [comment]
I  had exactly the same question.

**Comment by danielbankhead** [comment]
> What client_id is suppose to be in this line in that case? Does it matter?
> 
> ```
> const client = new OAuth2Client(CLIENT_ID);
> ```

It doesn't matter in this case - it's not used in the `verifyIdToken` flow. Additionally, the constructor defines it as optional:

https://github.com/googleapis/google-auth-library-nodejs/blob/20b375b65d5bfa460303785e933e713f84b03d60/src/auth/oauth2client.ts#L459-L460

Additionally, I'll work on fixing the sample on this page: https://developers.google.com/identity/sign-in/web/backend-auth#using-a-google-api-client-library
