### ISSUE TITLE
getAccessToken includes trailing dots padded to 1024 characters

### ISSUE THREAD

**Issue by sethvargo** [googleapis/google-auth-library-nodejs#1499]
1) Is this a client library issue or a product issue?

> This is an issue with the google-auth-library for Node.js, but it only reproduces in some environments.

2) Did someone already solve this?

> I was unable to find any reports of this issue, but [I've been able to reproduce it](https://github.com/sethvargo/google-auth-periods-repro) as have [other users](https://github.com/google-github-actions/setup-gcloud/issues/595#issuecomment-1329861834)

3) Do you have a support contract?

> I am a Googler.

#### Environment details

  - OS: ubuntu 20.04
  - Node.js version: 16
  - npm version: 8.19.3
  - `google-auth-library` version: 8.7.0

#### Steps to reproduce

I have a [reproduction repo here](https://github.com/sethvargo/google-auth-periods-repro). Create a service account key and run the following code in the offial Node.js Docker container:

```ts
import { GoogleAuth } from 'google-auth-library';
import { promises as fs } from 'fs';

async function main() {
  const auth = new GoogleAuth({
    scopes: ['https://www.googleapis.com/auth/cloud-platform'],
  });

  const token = await auth.getAccessToken();
  if (!token) {
    throw new Error('Failed to get token');
  }

  // Print to console
  console.log({ token });

  // Write to file
  await fs.writeFile('token.txt', token);
}

main();
```

It creates a `GoogleAuth` client with some default scopes and creates an access token. The resulting access token is padded with periods (".") up to 1024 characters:

```text
ya29.c.b0Aa9VdynqEhA6LfA0rFWLxqh8oU5lA66gwzcNeP80r4z2pueTDGJgD_4J5hUbqnUfe8iZAZ9gety-TeVynJ01WGVoBWsrNmtlHmw9v4W-owpiOP8VtUu-Dk9qSjElYp0zZEG7fY3y28gPXZ2H3kKhSxdZAp7yWVEBOFFLj-vKcMD8lPgk9HNckDRAM7_Af18h8yWiggNEwZKMhOxDSyJEUl_yFKlHruo........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
```

Some GCP APIs actually accept this token as valid, but others reject it.

Warning: Running this GitHub Action will print an access token in plaintext. Try reproducing in a private environment or with a service account that has no permissions.

Note: The tokens provided in this GitHub issue have either been revoked or correspond to a service account which has no permissions.

**Comment by jpriollaud** [comment]
Seeing the same issue in Ruby.

**Comment by sethvargo** [comment]
After discussion, I think this is working as intended. This is to prepare clients for the larger tokens coming in the future.

**Comment by danielbankhead** [comment]
A bit of background for those that are interested: https://github.com/googleapis/google-api-nodejs-client/issues/2839#issuecomment-1142263264
