### ISSUE TITLE
Improve the documentation on how to directly get a bearer token in a framework-agnostic way

### ISSUE THREAD

**Issue by jakubjafra** [googleapis/google-auth-library-nodejs#1501]
Hey,

The [docs](https://cloud.google.com/run/docs/authenticating/service-to-service#acquire-token) mentions the `Authorization: Bearer ID_TOKEN` but the provided Node.js code sample does not use the `ID_TOKEN` explicitly. Instead, it uses a `request`-like API (which uses the `ID_TOKEN` internally), which is confusing. `request` lib is [deprecated](https://www.npmjs.com/package/request) as of Feb 11th 2020.

Other examples do use obtained `ID_TOKEN` directly.

I think [this line](https://github.com/googleapis/google-auth-library-nodejs/blob/fb40dd7be53dbeb34a10521050fb14e4cc44e6e9/samples/idtokens-serverless.js?utm_source=cloud.google.com&utm_medium=referral#L65) could be changed to get the `ID_TOKEN`, for example:
```ts
const idToken = (await client.getRequestHeaders())['Authorization'];
```
(Is there a better way, by the way?)

And then the example could use the obtained `idToken` using a `fetch` or any other framework not coming from a `client`.

**Comment by danielbankhead** [comment]
@jakubjafra To clarify, the `.request` in our clients do not use the deprecated `request` library.

In the sample, one can use the `IdTokenClient`'s `.idTokenProvider.fetchIdToken` method to retrieve an `idToken`.
