### ISSUE TITLE
Improve local user experience for User Credentials

### ISSUE THREAD

**Issue by TimurSadykov** [googleapis/google-auth-library-nodejs#1525]
This is part of the bigger work [go/simplified-local-adc](http://goto.google.com/simplified-local-adc)

User Credentials are now recommended for local development per [go/mitigating-cloud-auth-risk](https://goto.google.com/mitigating-cloud-auth-risk)

However, some errors and warnings still refer to service accounts (see section 1.2 of the [go/simplified-local-adc](http://goto.google.com/simplified-local-adc)):

1. When user does not have credential setup, we do not recommend setting up service account, rather we redirect to a new ADC setup page.
2. (if applicable) We show warning about user credentials only if production environment is detected
Reference Java fix: https://github.com/googleapis/google-auth-library-java/pull/1172

**Comment by danielbankhead** [comment]
Today, we don't offer suggestions in the code suggesting service accounts or not (neither in docs, comments, or error messages). Here's how the missing ADC message looks like today:

https://github.com/googleapis/google-auth-library-nodejs/blob/85f2c9393f64b97290a0698d3ac6754fa9bc951a/src/auth/googleauth.ts#L367-L370

As for the second case:
- we've previously introduced this functionality in #399
- updated in #402 
- then ultimately reverted in #905

I'm happy to revert #905 if the telemetry determines this provides a better user experience.

Let me know if anything else, closing for now.
