### ISSUE TITLE
Code Challenge Method Type Error

### ISSUE THREAD

**Issue by Rmutek** [googleapis/google-auth-library-nodejs#1533]
Hi there,

When attempting to set `code_challenge_method: 'S256',` I am getting the following error "Type '"S256"' is not assignable to type 'CodeChallengeMethod | undefined'.ts(2322)"

'S256' is an accepted value according to CodeChallengeMethod but when I pass that string in I get a type error

Seems like something is off with the type that is expected to be passed in. If I do this, `code_challenge_method: <any>'S256'`, it works fine. 

This is how I have this block set-up.

```
  const authorizeUrl = oAuth2Client.generateAuthUrl({
    access_type: 'offline',
    scope: 'https://www.googleapis.com/auth/gmail.compose https://www.googleapis.com/auth/gmail.send https://www.googleapis.com/auth/gmail.modify https://mail.google.com/',
    code_challenge_method: 'S256',
    code_challenge: codes.codeChallenge,
  });
```

#### Environment details

  - OS: macOS Monterey 12.6
  - Node.js version: 16.16
  - yarn version: v1.22.18
  - `google-auth-library` version: 8.7.0

#### Steps to reproduce

  1. Using typescript attempt to set code_challenge_method to 'S256' and get a type error

Thanks!

**Comment by sofisl** [comment]
Hi @Rmutek! This field is an enum, so you'll have to do the following in your code:

`import {CodeChallengeMethod, OAuth2Client} from 'google-auth-library';` 

then in the `generateAuthUrl` method, you'll write:

```
code_challenge_method: CodeChallengeMethod.S256,
```

And that should work. Feel free to reopen if this doesn't work for you!
