### ISSUE TITLE
Request to add nonce param to GenerateAuthUrlOpts interface

### ISSUE THREAD

**Issue by atsushii** [googleapis/google-auth-library-nodejs#1542]
`GenerateAuthUrlOpts` interface does not have nonce param.

I think setting nonce to the auth URL is quite a common use case

This feature request is to add a nonce to  GenerateAuthUrlOpts interface.

If it is appropriate please look at my PR https://github.com/googleapis/google-auth-library-nodejs/pull/1541 already created otherwise will close.

**Comment by sofisl** [comment]
Hi @atsushii, you should be able to add it as a user-defined parameter, this allows you to define a [key-value pair](https://github.com/googleapis/google-auth-library-nodejs/blob/cb8c9452bc6b5af48a791a2b212a6db4b19186dd/src/auth/oauth2client.ts#L315). Would this work for you?

**Comment by atsushii** [comment]
Hi @sofisl, Yes, it will work. Thanks!
I will close my PR.
