### ISSUE TITLE
Stop using buffer-equal-constant-time

### ISSUE THREAD

**Issue by idoshamun** [googleapis/google-auth-library-nodejs#1544]
I noticed you use `buffer-equal-constant-time` indirectly through `jws` and `gtoken`.
`buffer-equal-constant-time` is a legacy and unsupported package since 2017. ([Deprecation notice](https://github.com/salesforce/buffer-equal-constant-time/issues/6))
It causes some issues in combination with docker and some other environments.
I'd appreciate if you can consider switching it.
A solid alternative for jwt purposes is [fast-jwt](https://github.com/nearform/fast-jwt).

I have already switched `jws` here: https://github.com/idoshamun/google-auth-library-nodejs/tree/update-jwt-lib
But it's not enough as we also need to update gtoken

**Comment by danielbankhead** [comment]
Thanks for reporting - we'll replace `jws` with another library.

Here's a tracking issue:
- https://github.com/googleapis/google-auth-library-nodejs/issues/1650
