### ISSUE TITLE
remove dep on fast-text-encoder

### ISSUE THREAD

**Issue by jimmywarting** [googleapis/google-auth-library-nodejs#1546]
You only load this when needed.
https://github.com/googleapis/google-auth-library-nodejs/blob/85f2c9393f64b97290a0698d3ac6754fa9bc951a/package.json#L23

But i also see that you have a requirement on NodeJS v12+

https://github.com/googleapis/google-auth-library-nodejs/blob/85f2c9393f64b97290a0698d3ac6754fa9bc951a/package.json#L6-L8

therefore this npm package could be removed, cuz text encoder/decoder is available globally since NodeJS v11

Also supporting NodeJS v12 is a bit outdated, think you should target LTS and update to something newer such as v16 that is the current LTS right now

So also think you should do:
```json
 "engines": { 
   "node": ">=16" 
 }, 
```

**Comment by jimmywarting** [comment]
any reason for not going with v16 as LTS?
v14 is no longer supported by nodejs

**Comment by ddelgrosso1** [comment]
There are a variety of issues with jumping from 12->16. We try to look at metrics on what version customers are currently using and a large percentage are still on 14. While we create a new major version when we bump the minimum version, jumping 12->16 is likely to leave a large portion of the user base unable or unwilling to upgrade. Additionally, we try and make sure we are supporting similar versions with other Cloud products, i.e. Cloud Functions.

**Comment by sofisl** [comment]
Removed in https://github.com/googleapis/google-auth-library-nodejs/commit/d736da3fa5536650ae6a3aebbcae408254ebd035
