### ISSUE TITLE
Relation to https://accounts.google.com/gsi/client

### ISSUE THREAD

**Issue by christhegrand** [googleapis/google-auth-library-nodejs#1559]
Is this the same library as https://accounts.google.com/gsi/client? Or are these different JS auth libraries?

**Comment by sofisl** [comment]
I think this is different, but I can't tell because that link is just minified code. Can you share a link to the code for that library?

**Comment by christhegrand** [comment]
I got the link from here: https://developers.google.com/identity/gsi/web/guides/client-library

I was also trying to find the unminified code. I also think it's for a different library.

**Comment by danielbankhead** [comment]
Yes, these are different auth libraries. In short, that auth libraries is for end users while this library is for APIs/local development.

**Comment by christhegrand** [comment]
Is the source code for that library available anywhere?

**Comment by danielbankhead** [comment]
Kind of, per [this doc](https://developers.google.com/identity/oauth2/web/guides/migration-to-gis) it depends on which functionality is needed. Here's the source for one of the libraries: https://github.com/google/google-api-javascript-client

**Comment by danielbankhead** [comment]
I think we can do a better job at linking the source for that product - I'll share some feedback!

**Comment by christhegrand** [comment]
Thank you!
