### ISSUE TITLE
createSubscription method throws if oidcToken is being set

### ISSUE THREAD

**Issue by ochoacabriles** [googleapis/google-auth-library-nodejs#1560]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

1) Is this a client library issue or a product issue?
Client library issue

2) Did someone already solve this?
This user faced something similar with Python and was solved by changing the Python version.
https://github.com/googleapis/python-pubsub/issues/480

3) Do you have a support contract?
No

If the support paths suggested above still do not result in a resolution, please provide the following details.

#### Environment details

  - OS: Mac OS Monterey 12.6 (also happens in firebase cloud functions environment)
  - Node.js version: 16.13.1 (also happens with node 14 and node 12)
  - npm version: 8.1.2
  - `@google-cloud/pubsub` version: 3.2.0

#### Steps to reproduce

  1. Create a topic.
`await pubSubClient.createTopic(topicName)`

  2. Create a subscription for the topic, setting OIDC token (either in pushConfig or in the root object as admitted by the sdk).
```
await pubSubClient.createSubscription(item.topicName, item.subscriptionName, {
        pushConfig: {
           pushEndpoint: item.endpoint,
           oidcToken: {
              serviceAccountEmail,
              audience: projectId,
        },
      },
      expirationPolicy: {
        ttl: null,
      },
      retryPolicy: {
        minimumBackoff: {
          seconds: 10,
        },
        maximumBackoff: {
          seconds: 60,
        },
      },
    });
  }));
  ```

This also fails:
```
await pubSubClient.createSubscription(item.topicName, item.subscriptionName, {
        pushEndpoint: item.endpoint,
        oidcToken: {
          serviceAccountEmail,
          audience: projectId,
        },
      expirationPolicy: {
        ttl: null,
      },
      retryPolicy: {
        minimumBackoff: {
          seconds: 10,
        },
        maximumBackoff: {
          seconds: 60,
        },
      },
    });
  }));
```

This was working properly, we found the first error on Sep 29th 2022.
Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by danielbankhead** [comment]
@ochoacabriles are you still facing this issue?

**Comment by ochoacabriles** [comment]
@danielbankhead We ended by changing the implementation. We changed all of our functions to use Pub/Sub triggers, which takes care of creating the topic and the subscription under the hood, so we didn't follow this up.

Thanks!
