### ISSUE TITLE
Unable to configure Gaxios options for common AuthClients

### ISSUE THREAD

**Issue by benasher44** [googleapis/google-auth-library-nodejs#1621]
**Is your feature request related to a problem? Please describe.**
For OAuth2Client for example, there's no way to configure the agent to make use of keep alive.

 **Describe the solution you'd like**
Ideally, the constructor for all AuthClient sub-classes accept options that would be passed to gaxios, which would allow setting the agent

 **Describe alternatives you've considered**
I think one could maybe overwrite the transporter ivar with one that is sub-classes to set an agent, but that feels bad.

 **Additional context**
Nearly all of the API wrappers in https://github.com/googleapis/google-api-nodejs-client use a similar constructor pattern, wherein all of the constructor options are a subset of gaxios options.

**Comment by benasher44** [comment]
For some reason, the JWT class does this, but OAuth2Client doesn't. I think this also means that if JWT isn't overriding everything and you set gaxios options, behavior will be inconsistent, when calling non-overridden methods.

**Comment by danielbankhead** [comment]
Hey @benasher44,

Today, we offer a few options for setting `keepAlive`:

- 1: On a per-request basis
https://github.com/googleapis/google-auth-library-nodejs/blob/dd04fbdeb17e457a09b06a4abc2aedf511f355ea/samples/keepalive.js#L41-L44

- 2: You can assign your own `Transporter` to the `AuthClient`
https://github.com/googleapis/google-auth-library-nodejs/blob/dd04fbdeb17e457a09b06a4abc2aedf511f355ea/src/transporters.ts#L29-L31
https://github.com/googleapis/google-auth-library-nodejs/blob/dd04fbdeb17e457a09b06a4abc2aedf511f355ea/src/auth/authclient.ts#L87-L96

> **Describe the solution you'd like**
> Ideally, the constructor for all AuthClient sub-classes accept options that would be passed to gaxios, which would allow setting the agent

This is a worthwhile feature request, we'll explore this as an option.

**Comment by danielbankhead** [comment]
Exposing this as a new option via:
- https://github.com/googleapis/google-auth-library-nodejs/pull/1663

Now all AuthClients can accept a `gaxios`, custom transporter instance, or set default properties for the transporter.

Additionally, it can be set for any AuthClient that would be instantiated via:
```ts
new GoogleAuth({
  clientOptions: {
    transporterOptions: {} // `GaxiosOptions`
  }
})
```
