### ISSUE TITLE
Refresh token usage for multiple users

### ISSUE THREAD

**Issue by GiantPineappleStatue** [googleapis/google-auth-library-nodejs#1630]
[According to another issue here](https://github.com/googleapis/google-api-nodejs-client/issues/2080), the "correct" way to use the auth library is to hold multiple authenticated oauth2Client instances in memory? Is this correct or can someone clarify the proper way to use stored refresh and access tokens to retain access to Google APIs?

Current setup:

auth callback endpoint: exchange code for tokens => save the tokens and expiry_date to db.

test endpoint: initialize new oauth2Client => setCredentials with stored tokens => access Google APIs.

The access token would stop working after one hour so.
Same question was asked [here](https://github.com/googleapis/google-api-nodejs-client/issues/2675) with code samples. The suggestion is the same as the first link, which is to create and hold auth client objects.

**Comment by GiantPineappleStatue** [comment]
For reference, this is the oAuth2Client object after setting credentials
`{
_events: { },
_eventsCount: 1,
transporter: { },
credentials: {
access_token: "ya29.blahblah",
refresh_token: "1//0blah blah",
expiry_date: 1691608112,
forceRefreshOnFailure: true
},
eagerRefreshThresholdMillis: 300000,
forceRefreshOnFailure: false,
certificateCache: { },
certificateExpiry: null,
certificateCacheFormat: "PEM",
refreshTokenPromises: { },
redirectUri: "http://localhost:3000/api/auth/callback/"
}
`
does it look correct?

**Comment by danielbankhead** [comment]
Hey @GiantPineappleStatue, this looks correct - the OAuth2 client should use the provided `refresh_token` to automatically request and use an access token. You can also listen to the [`tokens` event](https://github.com/googleapis/google-auth-library-nodejs/blob/bf23bad915cae8994b2953b406d04112848c5224/src/auth/oauth2client.ts#L650) and capture/store that way as well:

```js
oauth2client.on('tokens', token => {
  // store token
});
```

**Comment by GiantPineappleStatue** [comment]
@danielbankhead Hey Daniel, thanks for getting back to me and I appreciated you replying to my email.
I'm unable to continue to use the access token after an hour and I've yet to suss out how to use the refresh token to get a new access token. The docs implies that the action would be done automatically(at which point I'm assuming the auth2client.on() listener would kick on.

Two questions/issue I have regarding the setup:
Where does the .on listener go? I currently initiate an oauth client object in a shared util file:
`import {google} from "googleapis";

export const oauth2Client = new google.auth.OAuth2(
    process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID,
    process.env.NEXT_PUBLIC_GOOGLE_SECRET,
    "http://localhost:3000/api/auth/callback/",
);
`
Does the listener go here? I did test putting it in both the util file and in an api where the client is used, neither returns an event at during my log-in process when tokens are exchanged and saved.
---
The token refresh process does not happen after the access token expires. Both the calendar api and oauth2client.getRefreshToken() returns invalid client. I've tried giving the client just the refresh token, refresh token+expiry, and refresh+access token. None of these worked to continue to allow access or grant a new access token. I'd love a clarification.

Thank you in advance!

**Comment by danielbankhead** [comment]
> I'm unable to continue to use the access token after an hour and I've yet to suss out how to use the refresh token to get a new access token. The docs implies that the action would be done automatically(at which point I'm assuming the auth2client.on() listener would kick on.

It should automatically do it when `oauth2Client.request` is called. To add a bit of context, the client itself should handle any requests on your behalf. You can also use `oauth2Client.getRequestHeaders` if you'd like to use your own auth library.

> Does the listener go here? I did test putting it in both the util file and in an api where the client is used, neither returns an event at during my log-in process when tokens are exchanged and saved.

The listener would be on `oauth2Client` and should look like this: https://github.com/googleapis/google-auth-library-nodejs#handling-token-events

> The token refresh process does not happen after the access token expires. Both the calendar api and oauth2client.getRefreshToken() returns invalid client. I've tried giving the client just the refresh token, refresh token+expiry, and refresh+access token. None of these worked to continue to allow access or grant a new access token. I'd love a clarification.

No problem, if you have existing credentials you would like to use you can set them via:

```js
oauth2Client.credentials = {};
```

Here's what the `Credentials` object/interface looks like:

https://github.com/googleapis/google-auth-library-nodejs/blob/bf23bad915cae8994b2953b406d04112848c5224/src/auth/credentials.ts#L15-L40

**Comment by danielbankhead** [comment]
Also, this PR will make this easier/cleaner to do:
- https://github.com/googleapis/google-auth-library-nodejs/pull/1652
