### ISSUE TITLE
has error on execute request

### ISSUE THREAD

**Issue by ChristopherMarim** [googleapis/google-auth-library-nodejs#1641]
https://github.com/googleapis/google-auth-library-nodejs/blame/6543e0f3da95dcf5aa4e6fc4155757a1a6c32a46/samples/jwt.js#L40

TypeError: callback is not a function

**Comment by ddelgrosso1** [comment]
Hi @ChristopherMarim can you provide some further details. What version of the library are you using? Are you saying the linked line is throwing an error? Can you provide some code that illustrates how to reproduce the issue?
