### ISSUE TITLE
ID Token From Metadata Server Incorrect

### ISSUE THREAD

**Issue by tgoodsell-tempus** [googleapis/google-auth-library-nodejs#1645]
https://github.com/googleapis/google-auth-library-nodejs/blob/49a5aec62ff5dddf38c55fd1f3c9502068e4e4e5/samples/idTokenFromMetadataServer.js#L38C1-L38C1

Based on the return values of the `client`, it doesn't have the `fetchIdToken` function which is mentioned in this code.

**Comment by yehudamakarov** [comment]
I have the same issue, and the lack of straightforwardness in the docs is becoming a nightmare. I just need to call a cloud run service from another cloud run service, and this is taking a LOT of frustrating effort

**Comment by danielbankhead** [comment]
Thanks for the feedback - I agree, we can improve the documentation here.

Raised a PR: #1651

**Comment by yehudamakarov** [comment]
@danielbankhead, stellar and kind response. Thank you!
