### ISSUE TITLE
Ignore google account chooser if the user already authenticated.

### ISSUE THREAD

**Issue by askarmus** [googleapis/google-auth-library-nodejs#1661]
In my Angular application, when I sign out and then attempt to log back in with Google authentication, it consistently displays the Google account selector. This happens even when Google has already authorized access to various Google services such as Gmail and YouTube. 

How can I avoid the account selector if Google has already granted authorization and the user is able to access Google services like Gmail and YouTube?

**Comment by danielbankhead** [comment]
This inquiry sounds related to [Sign In with Google](https://developers.google.com/identity/gsi/web/guides/overview) rather than this library. Please review the documentation for that product here:
- https://developers.google.com/identity/gsi/web/reference/js-reference
