### ISSUE TITLE
Request for web platform library

### ISSUE THREAD

**Issue by gkiely** [googleapis/google-auth-library-nodejs#1711]
**Is your feature request related to a problem? Please describe.**
There are a number of web platform runtimes that do not rely on node.js apis (deno, workers, bun) and there is no officially supported Google auth library for them. See https://wintercg.org.

 **Describe the solution you'd like**
An officially supported library for web platform runtimes.

 **Describe alternatives you've considered**
Libraries from the community, enabling node compatibility

**Comment by danielbankhead** [comment]
Thanks @gkiely, we're currently tracking supporting alternate runtimes here:
- https://github.com/googleapis/google-auth-library-nodejs/issues/1638
