### ISSUE TITLE
Error when import library

### ISSUE THREAD

**Issue by Zoe-997** [googleapis/google-auth-library-nodejs#1731]
Does this library support clients?
I just created a new reactjs app and it's empty, I want to use google-spreadsheet and google-auth-library but when I install it using npm it gives me an error when I import the library and it doesn't do anything.

thì is my code:
![image](https://github.com/googleapis/google-auth-library-nodejs/assets/57448131/f524628b-ab57-4b8a-9e4e-b9410651db09)

And this is error after:
![image](https://github.com/googleapis/google-auth-library-nodejs/assets/57448131/6bb9cda5-734d-45b5-b4b9-b01027933fe5)

**Comment by danielbankhead** [comment]
This library currently does not work in the browser. The functionality can be tracked here:
- https://github.com/googleapis/google-auth-library-nodejs/issues/1638


In the meantime, it appears these two options may suit your needs:
- https://developers.google.com/identity/oauth2/web/guides/overview
- https://developers.google.com/identity/gsi/web/guides/overview
