### ISSUE TITLE
Version 9.6.1 breaks @google-cloud/pubsub's emulator mode

### ISSUE THREAD

**Issue by alexanderczigler** [googleapis/google-auth-library-nodejs#1747]
#### Environment details

  - OS: linux
  - Node.js version: 18
  - npm version: 9
  - `google-auth-library` version: 9.6.1

#### Steps to reproduce

1. Use @google-cloud/pubsub in a project
2. Run the project with PUBSUB_EMULATOR_HOST set (this tells the pubsub library it is connecting to an emulator, see https://cloud.google.com/pubsub/docs/emulator)
3. Note that the pubsub library fails with `Error publishing to Pub/Sub Error: Could not load the default credentials.`
4. Add `"google-auth-library": "<9.6.1"` to resolutions in package.json
5. Note that pusbusb now works together with the emulator as intended

#### Notes

The changes in [9.6.1](https://github.com/googleapis/google-auth-library-nodejs/commit/a4f9f9c65853a37e6e83861c5d22533dba774037) seem to have something to do with this.

**Comment by danielbankhead** [comment]
Thanks for reporting - I'll get this resolved for you:
- https://github.com/googleapis/google-auth-library-nodejs/pull/1748
