### ISSUE TITLE
Retrieving User Account MFA Flags

### ISSUE THREAD

**Issue by havoanhnguyen** [googleapis/google-auth-library-nodejs#1759]
I'm trying to check if the user has enabled MFA/2FA,
I couldn't find any documentation allowing me to check that flag,
Does 'google-auth-library' currently support checking this? If so, could you assist me in checking it officially?
Thanks for your support,

**Comment by danielbankhead** [comment]
We don't offer such functionality in this library - are you using the the auth library for the web or backend?

Loosely related:
- #1638

**Comment by havoanhnguyen** [comment]
We using this library for backend site, We using for authenticate GG user
If you don't offer such functionality, Does you have plan to support this functionality in the future?
Or Does any way to check user has enable MFA/2FA via GG user's account?
Thanks for your support and feedback,

**Comment by danielbankhead** [comment]
We don't have it on the roadmap for this library at the moment, however it may be present in the following web auth libraries:
- https://cloud.google.com/identity-platform/docs/web/mfa

Related discussion:
- https://www.googlecloudcommunity.com/gc/Apigee/How-to-check-if-a-Google-user-have-MFA-enabled/m-p/607444#M75713

As an additional note, in case all of the end users are a within a Google Workspace org, MFA could be enforced on that level:
- https://support.google.com/a/answer/175197?hl=en

**Comment by havoanhnguyen** [comment]
Okie, thank for your support,
