### ISSUE TITLE
Occasional timeout when requesting Google ID Token Verify

### ISSUE THREAD

**Issue by KIMBEOBWOO** [googleapis/google-auth-library-nodejs#1764]
#### Environment details

  - OS: Linux/UNIX
  - Node.js version: 
  - npm version: 18
  - `google-auth-library` version: 9.6.3

#### Steps to reproduce
[referred to that](https://developers.google.com/identity/gsi/web/guides/verify-google-id-token?hl=ko#using-a-google-api-client-library)

```typescript
const client = new OAuth2Client();
const ticket = await client.verifyIdToken({
  idToken: idToken,
  audience: <<client_id>> // Specify the CLIENT_ID of the app that accesses the backend
});
const payload: TokenPayload | undefined = ticket.getPayload();
```

Once a timeout occurs, it does not resolve naturally, and if the server IP address is replaced, it will operate normally again for a certain period of time.

**Comment by danielbankhead** [comment]
Thanks, this could be related to:
- https://github.com/googleapis/google-auth-library-nodejs/issues/1756

**Comment by danielbankhead** [comment]
We’ll keep this tracked in the other issue - and resolve soon.
