### ISSUE TITLE
GaxiosError: Failed to retrieve verification certificates: request to https://www.googleapis.com/oauth2/v1/certs failed

### ISSUE THREAD

**Issue by sanjacob** [googleapis/google-auth-library-nodejs#1769]
Today out of the blue my login endpoint stopped working, and it seemingly never returned.
After a few minutes of debugging, I realised the `verifyIdToken` method was still running.
For some reason, the library tries to fetch certificates without any sort of warning or timeout for this, assuming the server will always be able to respond.

Then, I finally got this error:

> GaxiosError: Failed to retrieve verification certificates: request to https://www.googleapis.com/oauth2/v1/certs failed

It is pretty much the same as  googleapis/google-api-nodejs-client#3028.

I don't think it would be that hard to set a timeout on things like this, but maybe there's a reason for it? Who knows

#### Environment details

  - OS:
  - Node.js version:
  - npm version:
  - `google-auth-library` version: 9.6.3

#### Steps to reproduce

  1. Call `client.verifyIdToken()`

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by jaybe78** [comment]
Is there any news on this ?

My signin google feature suddenly stopped working with error 
```
errorType: 'Failed to retrieve verification certificates: request to https://www.googleapis.com/oauth2/v1/certs failed, reason: certificate has expired'
```

I have a flutter app that sends the idtoken to the backend for verification.
It used to work until this morning

```
const client = auth.fromAPIKey(GOOGLE_CLIENT_ID);
      console.log(idToken)
      console.log("verify id token ")
      const loginTicket = await client.verifyIdToken({ idToken });
 ```
