### ISSUE TITLE
How to handle google auth with react and node js api

### ISSUE THREAD

**Issue by startthecode** [googleapis/google-auth-library-nodejs#1792]
After clicking on "Login with Google", the user is redirected to the Google login page. Once the user selects their account, they are redirected back to the callback page where the server receives their information. However, it's not clear how the user will be notified that their account has been successfully created. Also, it's important to ensure that this whole process is handled professionally.

**Comment by danielbankhead** [comment]
> However, it's not clear how the user will be notified that their account has been successfully created

That's up to you as a developer - we do not handle account creations for third-party applications through this library.
