### ISSUE TITLE
ToC for Reference Documentation is broken

### ISSUE THREAD

**Issue by teksal** [googleapis/google-auth-library-nodejs#1798]
When I visit the [reference documentation](https://cloud.google.com/nodejs/docs/reference/google-auth-library/latest) there appears two `common` sections in ToC on the left, **Overview** page appears under second `common`, unselected, other headings irrelevant to this project are all selected, and the `google-auth-library` section is not expanded at all. Apparently something is mixed there, can you fix this issue please?

**Comment by danielbankhead** [comment]
Thanks for the feedback! I'll pass this information along to the relevant team to fix. For now, I'll close this public issue as I cannot transfer it to an internal team.
