### ISSUE TITLE
delegate credential using google script or javascript

### ISSUE THREAD

**Issue by bertranddelcroix** [googleapis/google-auth-library-nodejs#1831]
I found a tutorial article in the [site internet ](https://skaaptjop.medium.com/access-gsuite-apis-on-your-domain-using-a-service-account-e2a8dbda287c)  for a delegate credential .

Here, I don't know the language in PHP. Is there a way to convert from this language to google script (GAS) or javascript ? otherwise how to do it?

Here is the small function in php (?) below

/----

from googleapiclient import discovery
from httplib2 import Http
from oauth2client import file, client, tools
from google.oauth2 import service_account

SCOPES = ['https://www.googleapis.com/auth/gmail.settings.basic']
SERVICE_ACCOUNT_FILE = 'the-downloaded-keyfile.json'

// # The user we want to "impersonate"
USER_EMAIL = "someone@yourdomain.com"

credentials = service_account.Credentials.\
    from_service_account_file(SERVICE_ACCOUNT_FILE, scopes=SCOPES)
delegated_credentials = credentials.with_subject(USER_EMAIL)

service = discovery.build('gmail', 'v1', credentials=delegated_credentials)

send_as_addresses = service.users().settings().sendAs().\
    list(userId=USER_EMAIL, fields="sendAs(isPrimary,sendAsEmail)")

addresses = send_as_addresses.execute().get("sendAs", [])

/----

**Comment by danielbankhead** [comment]
This sample should help:
- https://github.com/googleapis/google-api-nodejs-client/blob/main/samples/gmail/send.js#L22-L66

**Comment by bertranddelcroix** [comment]
hi daniel,

First of all, please forgive me for my late response...

Regarding your message, I sincerely thank you. It works very well following
my attempt to test it. great, thank you. !

Best regards

Le ven. 12 juil. 2024 à 20:15, Daniel Bankhead ***@***.***> a
écrit :
