### ISSUE TITLE
Object prototype may only be an Object or null: undefined

### ISSUE THREAD

**Issue by SasunHakobyan1** [googleapis/google-auth-library-nodejs#1853]
Environment details
- OS: Linux Ubuntu
- Node.js version: v20.14
- npm version: 9.4
- google-auth-library version: 9.14.0

Trying to use google-auth-library in my nuxt3 app.

Error:
Status Code: 500
Message: Object prototype may only be an Object or null: undefined

Steps to reproduce:
import { OAuth2Client } from 'google-auth-library'

**Comment by danielbankhead** [comment]
This library is not officially compatible with web frameworks. Please follow the following for support updates:
- https://github.com/googleapis/google-auth-library-nodejs/issues/1638
