### ISSUE TITLE
cannot use it from a Google Cloud Function ( Firebase function)

### ISSUE THREAD

**Issue by erwin16** [googleapis/google-auth-library-nodejs#359]
I am trying to use it from a firebase function .. but the path of the json service Account credentials must be save in the GOOGLE_APPLICATION_CREDENTIALS environment variable ( uppercase )
Firebase function env variables should be set this way 

    `firebase functions:config:set GOOGLE_APPLICATION_CREDENTIALS="service-key.json"`

BUT uppercase are NOT accepted ...

**Comment by wbattel4607** [comment]
Any update on this? I'm trying to use this in Firebase Cloud Functions but I can't set the GOOGLE_APPLICATION_CREDENTIALS environment config- if that even is the correct way to set it. I can't really find any decent docs on how to implement it in Cloud Functions.

**Comment by HeckMarques** [comment]
> Any update on this? I'm trying to use this in Firebase Cloud Functions but I can't set the GOOGLE_APPLICATION_CREDENTIALS environment config- if that even is the correct way to set it. I can't really find any decent docs on how to implement it in Cloud Functions.

Yes, You can edit as environment variables directly in the Google Cloud Computing console, in Edit Function this option appears.
