### ISSUE TITLE
Make the projectId optional for signing with IAM

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/google-auth-library-nodejs#421]
###### Copied from original issue: https://github.com/stephenplusplus/google-auto-auth/issues/53

<a href="/hiranya911"><img src="https://avatars2.githubusercontent.com/u/2375201?s=88&v=4" height=44 width=44 align=left></a>@hiranya911<br>July 10, 2018 11:27 PM

The signWithApi method currently requires a `projectId` field:

```
_signWithApi (data, callback) {
    if (!this.projectId) {
      callback(new Error('Cannot sign data without a project ID.'));
      return;
    }
    ...
}
```

However, IAM's [signBlob endpoint](https://cloud.google.com/iam/reference/rest/v1/projects.serviceAccounts/signBlob) can be called without a `projectId` if necessary (using `-` as a wildcard):

```
/projects/-/serviceAccounts/${clientEmail}
```

Can we modify the implementation to default to `-` wildcard when a `projectId` is not given explicitly? This will greatly simplify the usage of the library in some high-level applications, such as [`firebase-admin`](https://github.com/firebase/firebase-admin-node/blob/master/package.json).

**Comment by stephenplusplus** [comment]
Thanks for the tip, @hiranya911! We are actually going to deprecate google-auto-auth, so this will live on as a feature request for `google-auth-library.

**Comment by JustinBeckwith** [comment]
@hiranya911 if there is no `projectId` available, I'm guessing that also means there's no `email` available.  They would both come from the service account credentials either via a JSON file, or via the Compute metadata service.  If someone wants to use the API like this - they would also have to provide the credential email for the service account, right?

**Comment by JustinBeckwith** [comment]
@hiranya911 *gentle ping*

**Comment by hiranya911** [comment]
Sorry for the delay. In the context I'm thinking of (Firebase server-side SDKs), a developer can provide a service account ID (i.e. client email) out of band. I'm not sure if there's a way to plumb that parameter down to this level though.

**Comment by hiranya911** [comment]
I think this can also help with issues like https://github.com/googleapis/nodejs-storage/issues/244

**Comment by danielbankhead** [comment]
Hey @hiranya911 - I'll pick this up for you (a few years after the fact 😅). You are correct, `projectId` is not required for this request (in fact, adding a project id would be [invalid according to the documentation](https://cloud.google.com/iam/docs/reference/credentials/rest/v1/projects.serviceAccounts/signBlob#path-parameters)). I'll create a PR shortly.
