### ISSUE TITLE
child_process Error

### ISSUE THREAD

**Issue by lokeshbansal1993** [googleapis/google-auth-library-nodejs#449]
This dependency was not found:

* child_process in ./node_modules/google-auth-library/build/src/auth/googleauth.js

To install it, you can run: npm install --save child_process
> Listening at http://localhost:8080

when use google-auth-library library for google-cloud/vision ..please help me for resolved this error in vuejs

**Comment by JustinBeckwith** [comment]
Greetings!  Are you trying to use this library with webpack by chance?  That doesn't work quite yet, but is being tracked over in #371 :)

**Comment by Tristan-D-19** [comment]
Hey I am getting this same issue using nextjs and webpack. Any lucks on fixes for this break?

**Comment by justincrich** [comment]
> Hey I am getting this same issue using nextjs and webpack. Any lucks on fixes for this break?

I'm also experiencing this in nextjs and would appreciate any suggestions

**Comment by JustinBeckwith** [comment]
Greetings folks!  Please file a new issue, and include as many instructions on how to reproduce as possible.  Sometimes these are tricky, because it depends on the module bundler getting used.
