### ISSUE TITLE
getDefaultServiceProjectId() takes too much time

### ISSUE THREAD

**Issue by JulieLorin** [googleapis/google-auth-library-nodejs#484]
getDefaultServiceProjectId() uses `gcloud config config-helper --format json` to retrieve projectId. 
It takes about a minute to retrieve the projectId

#### Environment details

  - OS: Ubuntu 18.04
  - Node.js version: v10.11.0
  - npm version: 6.4.1
  - `google-auth-library` version: 2.0.0

#### Steps to reproduce

  1. run gcloud config config-helper --format json in your console.
  2. or call getDefaultServiceProjectId() of auth/googleauth

**Comment by JustinBeckwith** [comment]
Oh gosh... that absolutely should not be happening. This command is lightning fast on my machine:

```
real	0m0.354s
user	0m0.209s
sys	0m0.134s
```

Is there anything weird about your setup?  Do you have a remote drive or something mapped to `$HOME`?

**Comment by JulieLorin** [comment]
No remote drive, I don't think there is anything weird. I just did a gcloud init to set up the CLI. People working with me have exactly the same issue with this command.

It is only the first time that this command takes some time, I think it is the time the retrieve the token (that lasts an hour, so after that, the command will be fast for an hour). I just tried, and it took 2min and 10s so run the command.

**Comment by JulieLorin** [comment]
And just in case, I also made a PR for this #485

**Comment by JustinBeckwith** [comment]
So you're saying if you:
1. Perform a clean install of the Cloud SDK
2. Run `gcloud init`
3. Run `gcloud config config-helper --format json`

That takes 60 seconds?

**Comment by JulieLorin** [comment]
That's what I'm saying.
But after some investigations, it may be linked to network issues ( https://groups.google.com/forum/#!topic/google-cloud-sdk/YuCY7JQlDUc ), and that would explain why people working with me have the same. 
I don't know if my PR is still relevant

**Comment by JustinBeckwith** [comment]
👋 @JulieLorin do y'all have this figured out, or are you still having issues?

**Comment by JulieLorin** [comment]
@JustinBeckwith Sorry for the delay. The command was taking a long time because of network rules and we found a workaround. Thanks :)
