### ISSUE TITLE
Can OAuth2Client.verifyIdToken() really return null?

### ISSUE THREAD

**Issue by gitgrimbo** [googleapis/google-auth-library-nodejs#487]
The docs:

https://googleapis.github.io/google-auth-library-nodejs/classes/_auth_oauth2client_.oauth2client.html#verifyidtoken

say `verifyIdToken()` can return `null` in the returned `Promise`:

`Promise<LoginTicket | null>`

but that doesn't seem possible.

This is causing (incorrect?) warnings in my TypeScript project.

---

The method:

https://github.com/googleapis/google-auth-library-nodejs/blob/fba56623726e20815557df2b8e2b20a66dbf2524/src/auth/oauth2client.ts#L832

supposedly can return `null` in the `Promise`.

The `verifyIdToken()` method calls:

https://github.com/googleapis/google-auth-library-nodejs/blob/fba56623726e20815557df2b8e2b20a66dbf2524/src/auth/oauth2client.ts#L862

which calls the following code (JSDoc shown) (no mention of `null` in the JSDoc, and also seemingly no way for the method to return `null`):

https://github.com/googleapis/google-auth-library-nodejs/blob/fba56623726e20815557df2b8e2b20a66dbf2524/src/auth/oauth2client.ts#L951

**Comment by JustinBeckwith** [comment]
Fair point!  That should never return null.  Fix is over at #488
