### ISSUE TITLE
Add a test case in test.compute.js to handle 5xx, such as 502, demonstrating behavior

### ISSUE THREAD

**Issue by crwilcox** [googleapis/google-auth-library-nodejs#518]
While looking at the test coverage for https://github.com/googleapis/google-auth-library-nodejs/blob/610ab17ad4623373d0bd5df683ddd12f4802bc1c/test/test.compute.js I noticed there is no test for 5xx errors. Could one be added to demonstrate the library handles 5xx errors?

**Comment by JustinBeckwith** [comment]
Please do let me know if I'm off base here, but it seems like you're asking for a test of 5xx responses from the GCP Metadata service - right?

If that's the case - this is WAI.  We use the [gcp-metadata](https://github.com/googleapis/gcp-metadata) npm module to handle all of our interactions with the GCE metadata service.  The `compute.ts` file has 100% test coverage, and we test the interaction with 5xx results here:
https://github.com/googleapis/gcp-metadata/blob/master/test/index.test.ts#L134

Please do let me know if I misunderstood :)
