### ISSUE TITLE
google-auth-library leaks memory when it is imported

### ISSUE THREAD

**Issue by pvatterott** [googleapis/google-auth-library-nodejs#525]
Whenever `google-auth-library` is imported in our codebase, our test suites start crashing with `FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory` 

I was able to isolate this to an issue with a downstream dependency, `agent-base`, which has an open issue: https://github.com/TooTallNate/node-agent-base/issues/22

#### Environment details

  - OS: Ubuntu 18.04.1
  - Node.js version: `10.13.0`
  - npm version: `yarn 1.7.0`
  - `google-auth-library` version: 2.0.0

#### Steps to reproduce
You can reproduce using `jest --detectLeaks`, like in the linked issue:

```
const auth = require("google-auth-library");

describe("google-auth-library", () => {
    it(`should not leak`, async () => {
        expect(auth).toBeTruthy();
    });
});
```

```
jest --detectLeaks
tests/auth-library.spec.ts
  ● Test suite failed to run

    EXPERIMENTAL FEATURE!
    Your test suite is leaking memory. Please ensure all references are cleaned.

    There is a number of things that can leak memory:
      - Async operations that have not finished (e.g. fs.readFile).
      - Timers not properly mocked (e.g. setInterval, setTimeout).
      - Keeping references to the global scope.

      at node_modules/jest-cli/build/TestScheduler.js:275:22

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.653s
```

**Comment by JustinBeckwith** [comment]
Greetings! We now load `https-proxy-agent` only when you're specifically asking for a proxy.  Unless you're doing that, hopefully this isn't a problem :)

**Comment by pvatterott** [comment]
Great! That's perfect, thanks for the help
