### ISSUE TITLE
Update deprecated methods from README

### ISSUE THREAD

**Issue by lpellegr** [googleapis/google-auth-library-nodejs#570]
Version 2 of the library has deprecated several methods. 

The README is still showing some examples based on deprecated methods. It would be really convenient to have them replaced by their new equivalent. One example is `refreshAccessToken`.

**Comment by JustinBeckwith** [comment]
Greetings!  Happy to clean up the README.  In the interim - I would like to know more about your usage of the `refreshAccessToken` method.  This is something that should just happen automatically when you call `getRequestHeaders`, or `request`.  Is there a scenario where you want to manually refresh the token?
