### ISSUE TITLE
HTTPS_PROXY support does not work with an HTTP proxy

### ISSUE THREAD

**Issue by hiranya911** [googleapis/google-auth-library-nodejs#571]
#### Environment details

  - OS: Ubuntu 16.04
  - Node.js version: v8.11.1
  - npm version: 5.6.0
  - `google-auth-library` version: 2.0.1

#### Steps to reproduce

I have a simple Squid forwarding proxy running on port 3128.

  1. `export HTTPS_PROXY=http://localhost:3128`
  2. Try the following code.

```
const {auth} = require('google-auth-library');

async function main() {
  const client = await auth.getClient({
    scopes: 'https://www.googleapis.com/auth/cloud-platform'
  });
  const token = await client.getAccessToken();
  console.log(token);
}

main().catch(console.error);
```

This results in the following error:
```
{ Error: write EPROTO 140028758259520:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

    at _errnoException (util.js:1022:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:880:14)
  code: 'EPROTO',
  errno: 'EPROTO',
  syscall: 'write',
  config: 
   { adapter: [Function: httpAdapter],
     transformRequest: { '0': [Function: transformRequest] },
     transformResponse: { '0': [Function: transformResponse] },
     timeout: 0,
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus],
     headers: 
      { Accept: 'application/json, text/plain, */*',
        'Content-Type': 'application/x-www-form-urlencoded',
        'User-Agent': 'axios/0.18.0',
        'Content-Length': 735,
        host: 'www.googleapis.com' },
     method: 'post',
     url: 'https://www.googleapis.com/oauth2/v4/token',
```

This prevents using libraries like Firestore and Cloud Storage from behind a proxy as well (since they depend on this library to authorize requests -- see https://github.com/googleapis/nodejs-firestore/issues/493).

Access log at the Squid proxy:

```
1544928657.277      0 172.17.0.1 TAG_NONE/400 4390 NONE error:invalid-request - HIER_NONE/- text/html
```

The problem seems to be that `google-auth-library` is not handling SSL tunneling correctly when going through an HTTP proxy. This is supported by GCP libraries in other languages (so far verified in Java, Python and Go), and it will be great if Node.js support can be fixed accordingly.

**Comment by JustinBeckwith** [comment]
Greetings, and thanks for the report!  We're aware of this, and @stephenplusplus is actively working on a solution :) We are using #352 to track this all up, so I'm closing this one out as a dup.

**Comment by stephenplusplus** [comment]
I believe @ajaaym [found a solution](https://github.com/googleapis/nodejs-logging/issues/350#issuecomment-466108461):

> can you please try setting both env variable https_proxy & HTTPS_PROXY GRPC uses https_proxy and authentication which goes through normal node request uses HTTPS_PROXY.

**Comment by josephwong13** [comment]
Not sure if useful to anyone still having this issue in 2020, if you are using http proxy over a https resources,
You could try adding 443 port to the request url (e.g. https://www.googleapis.com:443/auth/cloud-platform)
It should force the request to use https instead of http
