### ISSUE TITLE
"Invalid response from the metadata service" from in a Google Cloud Build

### ISSUE THREAD

**Issue by acchou** [googleapis/google-auth-library-nodejs#574]
When using Google Cloud Build, trying to use auth.getClient results in the following error:

Step #2: (node:16) UnhandledPromiseRejectionWarning: Error: Unexpected error determining execution environment: Invalid response from the metadata service
Step #2: at AuthPlus.<anonymous> (/workspace/node_modules/google-auth-library/build/src/auth/googleauth.js:163:23)
Step #2: at Generator.throw (<anonymous>)
Step #2: at rejected (/workspace/node_modules/google-auth-library/build/src/auth/googleauth.js:20:65)
Step #2: at <anonymous>
Step #2: at process._tickCallback (internal/process/next_tick.js:189:7)

This public repository contains example code and a cloudbuild.json file to setup Cloud Build: https://github.com/acchou/cloudbuild-example

To reproduce, use Google Cloud Build to create a Cloud Build trigger on the GitHub repository above, then specify /cloudbuild.json as the configuration file.

According to package-lock.json these are the library versions being used:
google-auth-library: 2.0.1
googleapis: 36.0.0
googleapis-common: 0.4.0
gcp-metadata: 0.7.0

**Comment by acchou** [comment]
I should also mention that this issue occurs even if I add Project Owner permissions to the Cloud Build service account ####@cloudbuild.gserviceaccount.com

**Comment by paulwoelfelcpl** [comment]
I got the same issue trying to schedule a Cloud Task in cloud build via node.js

```javascript
const response = await client.createTask(request);
```

**Comment by MaxLans** [comment]
@paulwoelfelcpl is your problem solved?

**Comment by paulwoelfelcpl** [comment]
@maxlens solved with what? Is there a new release, which fixes the bug?

**Comment by MaxLans** [comment]
Well,

I was wondering if other people also faced this message and know what to do with it, as I also faced this message ( coming from _isGCE check output )

—
Met vriendelijke groet,
Max Lans

Levarne BV
Mail: max@levarne.nl
Mobile: 0681775408
Website: http://www.levarne.com

Notitie: verzonden vanaf mijn iPhone

**Comment by JustinBeckwith** [comment]
Greetings folks!  I can confirm this is a legit bug.  This library relies on `gcp-metadata`, which looks for a GCE Metadata service that works like this:
https://cloud.google.com/compute/docs/storing-retrieving-metadata

After some investigation, it looks like the GCE Metadata service in Google Cloud Build is inconsistent with the metadata service available in App Engine, Kubernetes Engine, and Compute Engine.  I've filed an internal bug, and we'll follow up with the cloud build team to get to the bottom of things. 

Apologies for the trouble!

**Comment by MaxLans** [comment]
Hi @JustinBeckwith, cheers for letting us know!
I've noticed the priority of the bug as assigned is: p2. 
Can we track progress on the planning / roadmap and when this bug can be fixed somewhere?

Will be looking forward to your answer.

**Comment by JustinBeckwith** [comment]
Greetings folks!  Special thanks to @philmod for making this happen :) Everything here is working now!  Keep in mind - the service account that Cloud Build uses to perform builds is pretty limited in scope.  You may need to add additional roles to the service account to do what y'all wanna do.  Let us know if you have any other problems!
