### ISSUE TITLE
How to send back the user information to the front end apps ?

### ISSUE THREAD

**Issue by jejesh26** [googleapis/google-auth-library-nodejs#591]
Dears,

assuming : 
- the front end website (in react) is calling the server (node/express) - Just a A HREF link in a button
- Then the servers calls the Google oAuth2 api
- Then the server callbackURL manages the user info, authorization,... based on the code returns by Google Api.

How to send back these user info to the initial URL of front end ? res.redirect() is not working as the res in the callbackURL is related to the google req/res and not the initial req/res from the front end

Thks

**Comment by JustinBeckwith** [comment]
Greetings!  If you're looking for an end to end solution of doing OAuth2 with flows with a user, this is a great guide:
https://github.com/googleapis/google-api-nodejs-client/blob/master/samples/sampleclient.js

If that doesn't help - it would be super helpful if you could post the code you're trying today, what's working, what's not working, and which parts we can help with :) 

Let us know if you're still having issues!
