### ISSUE TITLE
oauth2client duplicative execution of callback in catch code

### ISSUE THREAD

**Issue by jon-freed** [googleapis/google-auth-library-nodejs#600]
In oauth2client.ts, [the request code at line 809](https://github.com/googleapis/google-auth-library-nodejs/blob/1c014d8ffc7eedba13bbdc06790bc22c32b2cf93/src/auth/oauth2client.ts#L809) is executing the callback upon catching an error in the callback.  It should not be executing the callback in the catch code, right?  Seems that second call in the catch code has created a problem similar to what is described here:  [https://joseoncode.com/2013/12/27/case-of-double-callbacks/](https://joseoncode.com/2013/12/27/case-of-double-callbacks/)

#### Steps to reproduce

  1. Do the Node.js quickstart at [https://developers.google.com/sheets/api/quickstart/nodejs](https://developers.google.com/sheets/api/quickstart/nodejs)
  2. Insert a new line 97:       throw "watch this get executed twice";
  3. Debug your now-customized quickstart, and watch as the callback gets executed twice.

The oauth2client code is also executing the callback in catch code for [the getToken code around line 502](https://github.com/googleapis/google-auth-library-nodejs/blob/1c014d8ffc7eedba13bbdc06790bc22c32b2cf93/src/auth/oauth2client.ts#L502).

**Comment by JustinBeckwith** [comment]
Greetings!  It's hard to tell without more info, but I'm pretty sure everything here is working as intended.  Let me explain why!  

The code in `google-auth-library` that wraps promises looks mostly like this:
```js
this.requestAsync<T>(opts).then(
  r => callback(null, r), 
  e => callback(e, e.response);
);
```
The `resolve` method of the promise calls the callback if the promise succeeds, and the `reject` parameter calls the callback with the error.  Only one of the `resolve` or `reject` handlers will ever be called, so there should be no issues of the double callback there.

Now - if we *also* did a `.catch` on the end of this, and called a callback with that error - we would be in trouble.  As a matter of fact, I wouldn't surprised if older versions of the library (or older versions of googleapis) made this mistake (we all learn...).  

I would suggest updating to the latest version of googleapis, the latest version of `google-auth-library`, and seeing if you still have this issue.  In the event that you do... please do let me know!
