### ISSUE TITLE
Example code not working on google compute engine, returns Forbidden message

### ISSUE THREAD

**Issue by victorbadila** [googleapis/google-auth-library-nodejs#601]
#### Environment details

  - OS: Debian 9
  - Node.js version: 10150
  - npm version: 6.6.0
  - `google-auth-library` version: 3.0.1

#### Steps to reproduce

  1. Create a compute engine in one of your gcloud projects with the above configuration.
  2. Put in the example code from `README.md`:
```
const {auth} = require('google-auth-library');

/**
 * Instead of specifying the type of client you'd like to use (JWT, OAuth2, etc)
 * this library will automatically choose the right client based on the environment.
 */
async function main() {
    const client = await auth.getClient({
        scopes: 'https://www.googleapis.com/auth/cloud-platform'
    });
    const projectId = await auth.getProjectId();
    const url = `https://www.googleapis.com/dns/v1/projects/${projectId}`;
    const res = await client.request({ url });
    console.log(res.data);
}

main().catch(console.error);
```
3. Run the code `node <filename>`
4. Instead of the API working the code throws an error:
```
{ Error: A Forbidden error was returned while attempting to retrieve an access token for the Compute Engine built-in service account. This may be because the Compute Engine instance does not have the correct permission scopes specified. Request had insufficient authentication scopes.
    at Gaxios.<anonymous> (/home/victor/test-iam/node_modules/gaxios/build/src/gaxios.js:64:27)
    at Generator.next (<anonymous>)
    at fulfilled (/home/victor/test-iam/node_modules/gaxios/build/src/gaxios.js:16:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by JustinBeckwith** [comment]
Greetings!  This sample only works when it's running on Compute Engine :) Are you running this on compute engine or locally?

**Comment by victorbadila** [comment]
Hi Justin. I ran it on a Compute Engine instance in Google Cloud.

**Comment by victorbadila** [comment]
I looked into it some more. It seems like the basic rights associated with a Compute Engine does not allow it to execute the API call in the example. The instance needs to be stopped, permissions need to be adjusted (and I have not found any Compute Engine permissions for reading the project, I was only able to make other API calls) and then the machine restarted along with the node script / app.
Either something is incomplete in the documentation (and the example url is bad) or there's really some problem in this auth package.

**Comment by JustinBeckwith** [comment]
Great to hear things are working for you.  Assigning the right permissions to the GCE service account for the VM sounds like the right thing to do.  There's not a lot we can do with this lib to improve that experience.  We just read the service accounts the metadata service gives us :)

If there's something still broken here - let us know!
