### ISSUE TITLE
Where's the code coverage?

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/google-auth-library-nodejs#607]
For reasons I can't wrap my head around, code coverage is failing to report for this repository.  I can't see anything here we're doing different, so I'm left to guess that it's some issue in kokoro.

**Comment by kinwa91** [comment]
It looks like our codecov.io master token has been invalidated by them somehow, so it's not just this repository. @chingor13 was originally the person who created the token, perhaps his permissions got changed? I'll start a email and ask @theacodes to help us generate the token on a team account.

**Comment by JustinBeckwith** [comment]
This appears to be fixed 🥂
