### ISSUE TITLE
getProjectId ignores keyFilename

### ISSUE THREAD

**Issue by callmehiphop** [googleapis/google-auth-library-nodejs#614]
I'm not sure if this is a bug or it is intended, but it looks like if no env vars are set and one only provides a `keyFilename` to the `GoogleAuth` constructor it fails to retrieve a `projectId` unless `getClient` is called first.

```js
const auth = new GoogleAuth({
  keyFilename: '/path/to/my/file.json'
});

let projectId = await auth.getProjectIdAsync(); // will be null

await auth.getClient();
projectId = await auth.getProjectIdAsync(); // will be pulled from cached creds
```

It seems like we'd want to check for the `keyFilename` inside of the [`getFileProjectId`](https://github.com/googleapis/google-auth-library-nodejs/blob/master/src/auth/googleauth.ts#L600) method, but it is pretty unclear to me if this is intentional or not. I'd be happy to put together a PR if this is something we want.

**Comment by stephenplusplus** [comment]
Seems like an oversight. I say do it!

**Comment by callmehiphop** [comment]
@stephenplusplus haha, I'm actually curious why we don't just load the key file immediately when provided

**Comment by JustinBeckwith** [comment]
Yeah, I'm leaning towards bug on this one.  I don't have cycles today to touch this though - mind tossing a PR?
