### ISSUE TITLE
Promise returned by getToken fails to reject when getToken passed invalid authorization code

### ISSUE THREAD

**Issue by cpcallen** [googleapis/google-auth-library-nodejs#636]
#### Environment details

  - OS: macOS 10.13.6
  - Node.js version: v8.11.3
  - npm version: 6.7.0
  - `googleapis` version: 20.2.0
  - `google-auth-library` version: 0.10.0

#### Steps to reproduce

Run the following program:

```JS
'use strict';

const fs = require('fs');
const google = require('googleapis');
const oauth2Client = new google.auth.OAuth2(/* [VALID CREDENTIALS REDACTED ] */);

(async function() {
  // Case 1: fails to throw.
  try {
    const tokens = await oauth2Client.getToken('invalid');
  } catch (err) {
    console.log('ERROR1:', err);  // Never invoked.
  }

  // Case 2: calls callback with truthy err value, as expected.
  oauth2Client.getToken('invalid', (err, tokens) => {
    if (err) {
      console.log('ERROR2:', err);  // Invoked.
    }
  });
})();
```

Both calls to `getToken` fail because the authorization code is invalid.  The second one correctly results in `console.log('ERROR2:'…` being invoked, but the first one fails to call `console.log('ERROR1:'…`.

**Comment by JustinBeckwith** [comment]
Greetings @cpcallen!  I am having trouble reproducing this one.  Just to give a more complete script, this is what I'm trying:

```js
'use strict';

const {OAuth2Client} = require('google-auth-library');
const keys = require('./oauth2.keys.json');
const client = new OAuth2Client(
  keys.web.client_id,
  keys.web.client_secret,
  keys.web.redirect_uris[0]
);

async function main() {
  const tokens = await client.getToken('rubbish');
  console.log(tokens);
}

main().catch(console.error);
```

I get an exception like this:
```
{ Error: invalid_grant
    at Gaxios.<anonymous> (/Users/beckwith/Code/ttt/node_modules/gaxios/build/src/gaxios.js:72:27)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/beckwith/Code/ttt/node_modules/gaxios/build/src/gaxios.js:16:58)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
  response:
   { config:
      { method: 'POST',
        url: 'https://oauth2.googleapis.com/token',
        data:
   ...
``` 

Can you try this with the latest `googleapis` and latest `google-auth-library` and see what happens?

**Comment by cpcallen** [comment]
O.K., it appears that this was fixed sometime between 20.2.0 and 39.1.0, and I've wasted your time with an outdated bug report despite my best efforts because, contrary to expectations `npm upgrade` doesn't actually do what it says on the tin.  TIL but WTF.

**Comment by JustinBeckwith** [comment]
All good :) Happy to hear it's working!

**Comment by cpcallen** [comment]
Not sure why this has been assigned to me now.  As I noted almost two years ago, it appears to have been previously fixed.

I'm unassigning this for now, but feel free to reassign it to me (with an explanation) if there is some reason it really does need my attention.
