### ISSUE TITLE
GoogleAuth#getClient ignores user set project ID

### ISSUE THREAD

**Issue by callmehiphop** [googleapis/google-auth-library-nodejs#654]
Re: https://github.com/googleapis/nodejs-kms/issues/140

In some cases of `GoogleAuth#getClient` getting called any user supplied project IDs are ignored and the project ID set within the credentials is used instead.

For some additional context: when google-gax creates a gRPC client it will create the credentials via `getClient` which returns the credentials without taking `projectId` into consideration. While fixing just `getClient` might do the trick here, there are actually several methods that return the `cachedCredentials` object.

**Comment by bcoe** [comment]
I believe this is addressed by https://github.com/googleapis/google-auth-library-nodejs/pull/749, I've made an effort to change the API signature to prevent clients being returned that are half from cache, and half from options a user provides.
