### ISSUE TITLE
Title link to https://googleapis.github.io/google-auth-library-nodejs/ returns 404

### ISSUE THREAD

**Issue by mdstaff** [googleapis/google-auth-library-nodejs#657]
### Description

The short description for this repo entitled "🔑 Google Auth Library for Node.js https://googleapis.github.io/google-a…" is a link to a page that returns a 404.

#### Environment details

  - OS: Mac OSX
  - Browser: Google Chrome

#### Steps to reproduce

  1. Visit https://googleapis.github.io/google-auth-library-nodejs/
  2. Note 404 response

**Comment by JustinBeckwith** [comment]
🤦‍♂️  I fixed this by deleting the link from the repository.
