### ISSUE TITLE
`redirect_uri_mismatch` error even though URIs are the same

### ISSUE THREAD

**Issue by ianp** [googleapis/google-auth-library-nodejs#662]
#### Environment details

  - OS: macOS 10.14.3
  - Node.js version: v11.12.0
  - npm version: 6.9.0
  - `google-auth-library` version: 3.1.2

#### Steps to reproduce

  1. grab the SSCCE from https://gist.github.com/53d9ba98b9e065720aa26650b0083888
  2. create a project in the GCP console and a set of OAuth 2.0 client credentials
  3. make sure you add `http://localhost:3000/verify` to the list of redirect URIs
  4. save the resulting JSON file as `client_secret.json`
  5. run `npm start`
  6. navigate to http://localhost:3000
  7. attempt to sign in

The in-browser part of the handshake all seems to work OK, but when it passed the `code` back to the (express) server for verification and conversion into an offline access token it fails when it gets to `client.getToken()`.

<img width="623" alt="Screenshot 2019-04-03 at 15 29 32" src="https://user-images.githubusercontent.com/103420/55491639-c4654900-562d-11e9-9e7f-6649fca7ceaa.png">

The configuration in my project is shown above, and I can see in the console that it is `using redirect http://localhost:8000/verify` which is clearly in the list of redirect URIs; even so, the (Google) server responds with `Error: redirect_uri_mismatch`.

Let me know if I can provide any more info.

Thanks!

**Comment by ianp** [comment]
Some more information: if I alter my app so that it redirects to the index page again, and then use the code that is set in the fragment to send to my server, then this works. **But:** if I do this then the google client **is not** signed in (i.e. `gapi.auth2.getAuthInstance().isSignedIn.get()` returns `false`, also this means using the redirect UX mode instead of the popup, but I can live with that if I have to).

I seem to be faced with the choice of either having a signed in app in the browser with no offline access on the server, **or** having offline access on the server but having the browser unable to sign in, and I need both.

**Comment by zbot473** [comment]
A workaround is to delete and re-add; but that is far less than optimal.

**Comment by SaizFerri** [comment]
We are having the same issue

**Comment by bcoe** [comment]
out of curiosity, what if you use `127.0.0.1`, rather than `localhost`? In some cases I know browsers apply slightly different rules to `localhost`.

**Comment by SaizFerri** [comment]
In my case I don't have an issue with localhost. I can sign in on development and get redirected where I want within localhost eventhough localhost is not an authorised redirect URI. When we deploy it to production we get the error eventhough the URL is on the authorised redirect URI list. localhost and the production URL are on the authorised origins list

**Comment by blarralde** [comment]
For anyone having this same issue, here's the solution: https://stackoverflow.com/a/48121098/1389981

**Comment by fhinkel** [comment]
Greetings, we're closing this. Looks like the issue got resolved. Please let us know if the issue needs to be reopened.
