### ISSUE TITLE
URL is not a Constructor

### ISSUE THREAD

**Issue by dorman99** [googleapis/google-auth-library-nodejs#666]
Please Help, im trying to get access token that will be use for firebase dynamic link rest.
the probel that i got is :

before iam using google.auth.JWT
it get me an error URL is not custructor message.
now iam using google auth library to give me the access token.

const client = new JWT(
    serviceAccount.client_email,
    null,
    serviceAccount.private_key,
    scopes
);

but it still give me the same response like before, any suggestion?
#### Environment details

  - OS:
  - Node.js version: 9.0.0
  - npm version: 5.5.1
  - `google-auth-library` version: latest `one`
Thanks!

**Comment by JustinBeckwith** [comment]
Greetings!  Node.js `9.x` is not gonna be a supported version.  Can you try this with the latest version of `10`?

**Comment by dorman99** [comment]
> Greetings! Node.js `9.x` is not gonna be a supported version. Can you try this with the latest version of `10`?

it work now, thanks

**Comment by dorman99** [comment]
ok this issue has been solved, thanks for the response justin
