### ISSUE TITLE
How to set ofl, when generate deeplink

### ISSUE THREAD

**Issue by dorman99** [googleapis/google-auth-library-nodejs#669]
Hello , iam currently developing deep link for my services, it work when i use it on mobile, buat currently, when i open on my desktop, it still giving me the url for the mobile, not the ofl one

how do i set ofl properly,  iam using dynamicLinkInfo pattern

**Comment by JustinBeckwith** [comment]
Greetings, and thanks for the issue!  Sadly, I'm not 100% sure what you're asking :) Can you share:
- The code you're trying to use
- Any errors you're getting
- What version of nodejs and the google-auth-library module you're using?

Thanks!

**Comment by dorman99** [comment]
> Greetings, and thanks for the issue! Sadly, I'm not 100% sure what you're asking :) Can you share:
> 
> * The code you're trying to use
> * Any errors you're getting
> * What version of nodejs and the google-auth-library module you're using?
> 
> Thanks!

iam trying to create dynamic link with REST
as shown on this one: https://firebase.google.com/docs/reference/dynamic-links/link-shortener
i want to use dynamicLinkInfo object either using longDynamicLink parameters.

besides, when iam using the dynamicLinkInfo, i cant set ofl params to handle when the link accessed from non - mobile platfrom.

where i should put the ofl params ?

this my longDynamicLink 
: `${self._domainUriPrefix}/?link=https://mobile.link.com/&ofl=https://myweb.com/&apn=${self._androidPackage}&ibi=${self._iosPackage}`; => this one works, i can handle both from desktop or mobile

but i dont want to use the longDynamicLink method. i want to use the dynamicLinkInfo

the only errors that i got from now, i cant open the dynamic link url for the desktop, it gave me the link that only can be handle on mobile application

**Comment by JustinBeckwith** [comment]
Apologies - it doesn't look like this has anything to do with the `google-auth-library` npm module.  If you have a question specifically about the Firebase API, I would suggest posting here:
https://support.google.com/firebase/contact/support?page=bug_or_feature

Or posting here:
https://stackoverflow.com/questions/tagged/firebase-dynamic-links

Hope this helps!
