### ISSUE TITLE
Is there possible approach with node 6.x ?

### ISSUE THREAD

**Issue by dorman99** [googleapis/google-auth-library-nodejs#676]
Greetings..

currently im developing my backend using node ver 6.
and i cant change the version to the latest one (10) at this current state.
i want to use JWT package from google-auth-library to get access token.

is there any possible approach to this case?

**Comment by dorman99** [comment]
any kind of solutions ? iam getting stuck here, cuz i cant afford to update my node to the latest one for now, due to others depedencies.

**Comment by JustinBeckwith** [comment]
Greetings!  Thank s module supports Nodejs 6 as of today.  Is it not working for you?  Are you getting some kind of error?  

Version 4.0 (coming next week) will drop 6 support, so you're going to have to stay on 3 untipnyou get that sorted out :)

**Comment by dorman99** [comment]
> Greetings! This module supports Nodejs 6 as of today. Is it not working for you? Are you getting some kind of error?
> 
> Version 4.0 (coming next week) will drop 6 support, so you're going to have to stay on 3 untipnyou get that sorted out :)

thanks for your reply, cant wait for the next version to be released
