### ISSUE TITLE
Manually select node vs browser when creating OAuth2Client

### ISSUE THREAD

**Issue by sourabhv** [googleapis/google-auth-library-nodejs#725]
**Is your feature request related to a problem? Please describe.**
I'm working on a nodejs backend which defines `global.window` object. `verifyIdToken` throws  error `SubtleCrypto not found. Make sure it's an https:// website.` because isBrowser returns `true`.  A way to define environment when create an OAuth2Client would be nice.

 **Describe the solution you'd like**

Maybe a constructor like 
```
constructor(clientId?: string, clientSecret?: string, redirectUri?: string, environment?: string);
```

or 
```
constructor(clientId?: string, clientSecret?: string, redirectUri?: string, isNode?: boolean);
```

which can fallback to `global.window` based implementation?

 **Describe alternatives you've considered**

Currently I am using [this hack](https://github.com/googleapis/google-auth-library-nodejs/issues/682#issuecomment-487633181) which works but is not the cleanest way of solving this :)

**Comment by JustinBeckwith** [comment]
On having a manual switch - I would *really* like to avoid that. I am like 90% sure we fixed this in #738 :)  We switched up the code to check for the existence of `window.crypto.subtle` before assuming it would be available, so this should be a little more airtight.  We will have a release out tomorrow :)
