### ISSUE TITLE
Environment detection does not work on GCF nodejs10

### ISSUE THREAD

**Issue by ofrobots** [googleapis/google-auth-library-nodejs#747]
Originally reported by @hdp617 on https://github.com/googleapis/google-auth-library-nodejs/pull/429

> FUNCTION_NAME is no longer set in Google Cloud Functions for Node.js10 and subsequent runtimes. Could we update this?
https://cloud.google.com/functions/docs/env-var#environment_variables_set_automatically
It looks like K_SERVICE is the replacement.

**Comment by ofrobots** [comment]
`K_SERVICE` is also defined on Cloud Run and other knative based runtime environments. Unfortunately environment variable based environment detect will no longer work.

The right fix here would be to use the metadata service to inspect the monitored resource type instance attribute - `http://metadata.google.internal/computeMetadata/v1/instance/attributes/resource_type` - once this is fully supported by Cloud Run, GCF et. al.

**Comment by ofrobots** [comment]
More details on internal bug b/131353611.

**Comment by JustinBeckwith** [comment]
Since all we were doing here was trying to figure out if we're in GCF, the `FUNCTION_TARGET` env var should work fine, no?

**Comment by ofrobots** [comment]
A function running on Cloud Run should not be detected as 'GCF' but rather as 'Cloud Run'.
