### ISSUE TITLE
How to use user account credentials for multiple projects

### ISSUE THREAD

**Issue by amv93** [googleapis/google-auth-library-nodejs#764]
I have a project from which I want to copy few container images to another project using a node application. I use container-image-builder module for the same. 
The copying works with service account credentials,but I want to use user account credentials. The Oauth credentials allow only copying of images within the project but not across multiple projects as OAuth credentials restricts to a single project per application.
Is there any other solution that would allow me to use user account credentials?

**Comment by JustinBeckwith** [comment]
I am not 100%, but I don't think the user credentials (which I assume you're getting from a 3 legged OAuth2 flow) have to be projects specific.  You should be able to add a user to two different projects, give that user permissions on both images/registries, and then use that user account to do stuff :)

Where are you running into trouble?  Can you share any code, or error messages you're getting while trying to do it?

**Comment by amv93** [comment]
Yes, you are right, I am using the 3 legged OAuth2 flow. And it seems to be project specific.
The user has been given the owner permission for the two projects. So, there goes the question of this failing due to lack of permission. I know it is failing as OAuth2 is project specific.
But is there any other way to use the user account and copy the images to multiple projects?
I know this is possible when I use docker commands and run a script for a user account which has been given storage permissions. So, is this not possible using APIs?

My code is as follows:
`async function imageCopy(){
  var imgName = 'gcr.io/myProj/hello-world';
  var trgtImg = 'gcr.io/targetProj/hello-world';
  const image = new authParam.Image(imgName,trgtImg,{'gcr.io':{
     credentials:tokens // tokens is obtained from OAuth mechanism
    }
  });
    const result = await image.save(['dev-latest']);
    console.log(result);
}`
I get 403 Forbidden with the following error even though  ContainerRegistry API is enabled in both the projects:
`Error: unexpected status code 403 from docker registry (https://gcr.io/v2/myProj/hello-world/manifests/latest , and auth?: true)  response {"errors":[{"code":"DENIED","message":"Please enable or contact project owners to enable the Google Container Registry API in Cloud Console at https://console.cloud.google.com/apis/api/containerregistry.googleapis.com/overview?project=targetProj before performing this operation."}]}`

If this cannot be achieved using OAuth, is there anyother way to achieve this image copy to multiple projects using user account?

**Comment by amv93** [comment]
@JustinBeckwith ,
Do you have any suggestions or advice on this issue?

**Comment by bcoe** [comment]
@amv93 what's your use-case? I wonder if you could potentially use `gcloud` to perform this operation, and follow [this tutorial](https://cloud.google.com/container-registry/docs/managing#copying_images_to_a_new_registry) if it's an operation that a user initiates, or if it's a migration you only have to perform once.

**Comment by bcoe** [comment]
@amv93 did you manage to find an approach that worked for you?

**Comment by fhinkel** [comment]
Greetings, we're closing this. Looks like the issue got resolved. Please let us know if the issue needs to be reopened.
