### ISSUE TITLE
UserRefreshClient constructor should set credentials.refresh_token

### ISSUE THREAD

**Issue by MaksimKiselev** [googleapis/google-auth-library-nodejs#770]
When I create UserRefreshClient by constructor, I've get error:
```
Error: No access, refresh token or API key is set.
```

But when I load credentials by calling `fromJSON` method, all works correctly.

I looked at source code and find difference between this two ways:
`fromJSON` method set `credentials.refresh_token` property, but constructor don't:
https://github.com/googleapis/google-auth-library-nodejs/blob/v5.1.1/src/auth/refreshclient.ts#L111

**Comment by bcoe** [comment]
@MaksimKiselev thanks for the bug report :+1: sounds like you have a work around for the time being?

**Comment by MaksimKiselev** [comment]
@bcoe yes:

```
const client = new BigQuery({
  projectId
})

const credentials = {
  type: 'authorized_user',
  client_id: clientId,
  client_secret: clientSecret,
  access_token: acessToken,
  refresh_token: refreshToken
}

const refreshClient = new UserRefreshClient()
refreshClient.fromJSON(credentials)

client.authClient.cachedCredential = refreshClient

```

**Comment by bcoe** [comment]
@MaksimKiselev just landed a fix, please note that you should provide refresh_token to the constructor as `refreshToken`, access_token as `accessToken`, etc.

Thank you for the bug report.
