### ISSUE TITLE
Does it work with React.js? 

### ISSUE THREAD

**Issue by cindy100295** [googleapis/google-auth-library-nodejs#775]
Hi I just want to get a token so that my React app can send POST request to a app deployed on app engine. My code is here: 
```
  const { GoogleAuth } = require('google-auth-library');
  async function getauth() {
      console.log('get token')
      const auth = new GoogleAuth({
          scopes: 'https://www.googleapis.com/auth/cloud-platform'
      });
      console.log('auth: ', auth)
      const client = await auth.getClient();
      const projectId = await auth.getProjectId();
      const url = `https://www.googleapis.com/dns/v1/projects/${projectId}`;
      const res = await client.request({ url });
      console.log("res: ", res)
      let access_token = res.config.headers['Authorization'];
      console.log('access_token: ', access_token)
  }
  getauth().catch(console.error);
```

But I got error: 
```
gaxios.js:83 GET http://metadata.google.internal./computeMetadata/v1/instance net::ERR_NAME_NOT_RESOLVED
request @ gaxios.js:83
request @ index.js:37
metadataAccessor @ index.js:65
isAvailable @ index.js:120
_checkIsGCE @ googleauth.js:217
getApplicationDefaultAsync @ googleauth.js:187
async function (async)
getApplicationDefaultAsync @ googleauth.js:152
getClient @ googleauth.js:590
main @ App.js:11
App @ App.js:18
renderWithHooks @ react-dom.development.js:15821
mountIndeterminateComponent @ react-dom.development.js:18141
beginWork$1 @ react-dom.development.js:19357
beginWork$$1 @ react-dom.development.js:24548
performUnitOfWork @ react-dom.development.js:23502
workLoopSync @ react-dom.development.js:23480
renderRoot @ react-dom.development.js:23155
scheduleUpdateOnFiber @ react-dom.development.js:22653
scheduleRootUpdate @ react-dom.development.js:25686
updateContainerAtExpirationTime @ react-dom.development.js:25712
updateContainer @ react-dom.development.js:25812
(anonymous) @ react-dom.development.js:26370
unbatchedUpdates @ react-dom.development.js:22952
legacyRenderSubtreeIntoContainer @ react-dom.development.js:26369
render @ react-dom.development.js:26460
./src/index.js @ index.js:7
__webpack_require__ @ bootstrap:785
fn @ bootstrap:150
0 @ serviceWorker.js:135
__webpack_require__ @ bootstrap:785
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.chunk.js:1
```

I tried it in node express and it works. 
Is it because it does not work with React?

**Comment by JustinBeckwith** [comment]
Greetings!  The approach you're trying to take here is using "Application Default Credentials", where it mostly assumes you're working from a server.  This library *should* work from React, in very targeted scenarios (3 legged oauth).

Can you describe what you're trying to do?  

Which API are you trying to use?

Do you expect users to authenticate as themselves?  

Or do you expect to authenticate with a single service account, and always use that identity?

**Comment by cindy100295** [comment]
Hi thanks for the quick response! 

Actually the task is very simple. I want to send a POST http request to a flask app deployed on App Engine and want to send with Authorization. In another way, I want to get a token in React instead of type in command line `gcloud auth print-access-token` every time. 

```
fetch("API of Agg Engine", {
            method: 'POST',
            headers: {
                'Accept': 'application/json',
                'Authorization': access_token //  <-------- this is what I want
            },
            body: JSON.stringify({
                  text: 'some text',
            })
        })
```

Thanks! 

It is okay to send to the App Engine without a token, just because it is more secure.

**Comment by JustinBeckwith** [comment]
So if your app is running in App Engine, and you're trying to use a cloud API, that should "just work" ™️.  The App Engine environment uses Application Default Credentials, which let your app access basic services like Datastore, PubSub, Storage, etc without any explicit setup. 

You shouldn't need to mess with access tokens at all, _unless_ you're trying to use some other API that requires user level credentials.  

I guess I'm still not sure what you're trying to do :)

**Comment by JustinBeckwith** [comment]
The original intent was to check if this works with React.js, which we're tracking in #150.  Let's use that issue to track the request!

**Comment by kgaspard** [comment]
I suggest re-opening this given GCP's solution of choice for deploying applications is now Cloud Run - this question is open and relevant. Going back to @jguo1002 's original question, we would have two Cloud Run apps - one React "client" app and a "server" app. We'd typically want to block unauthenticated invocations from the server app, so that it can only be queried by the client app.

https://cloud.google.com/run/docs/authenticating/service-to-service says that we should, in this case, query the [metadata server](https://cloud.google.com/run/docs/securing/service-identity#identity_tokens) from the React app to get a token that can be used to query the server app (i.e. it doesn't "just work" with Cloud Run, even if both services are hosted on Cloud Run in the same project). However, that internal metadata endpoint in the linked docs seems to be broken (and if it's not, it would be useful to have an external service to query for local debugging anyway).

So then, the need to use google-auth-library on the front end is still there
