### ISSUE TITLE
Error: invalid_request on oauth.fetchToken(email) inside return pify(gmail.users.watch)

### ISSUE THREAD

**Issue by lenyabloko** [googleapis/google-auth-library-nodejs#777]
- OS: Windows 10, Version 76.0.3809.100 (Official Build) (64-bit)
  - Node.js version: 8
  - npm version:
  - `google-auth-library` version: updateed gcloud SDK 

#### Steps to reproduce
  1. Following google blog https://cloud.google.com/blog/products/application-development/adding-custom-intelligence-to-gmail-with-serverless-on-gcp
  2. Calling oauth2init --> redirect to URI https://us-central1-civil-flash-250501.cloudfunctions.net/oauth2callback --> 

```js
// Retrieve the stored OAuth 2.0 access token
  return oauth.fetchToken(email)
    .then(() => {
      // Initialize a watch
      return pify(gmail.users.watch)({
        auth: oauth.client,
        userId: 'me',
        resource: {
          labelIds: ['INBOX'],
          topicName: config.TOPIC_NAME
        }
      });
    })
    .then(() => {
      // Respond with status
      res.write(`Watch initialized!`);
      res.status(200).end();
    })
    .catch((err) => {
      // Handle errors
      if (err.message === config.UNKNOWN_USER_MESSAGE) {
        res.redirect('/oauth2init');
      } else {
        console.error(err);
        res.status(500).send('Something went wrong; check the logs.');
      }
    });
};
```

Result error log-->

 Error: invalid_request
    at new RequestError (/srv/node_modules/googleapis/node_modules/google-auth-library/lib/transporters.js:34:42)
    at Request._callback (/srv/node_modules/googleapis/node_modules/google-auth-library/lib/transporters.js:92:27)
    at Request.self.callback (/srv/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/srv/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/srv/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30) code: 400 }

**Comment by JustinBeckwith** [comment]
Greetings!  Can you share the complete code sample?  There are a few things in that blog post that are dated, or a little wrong :) Not knowing how the `oauth.fetchToken` stuff works, it would likely look more like this:

```js
app.get('/some/route', async (req, res) => {
  try {
    const token = await oauth.fetchToken(email);
    const res = await gmail.users.watch({
      auth: oauth.client,
      userId: 'me',
      requestBody: {
        labelIds: ['INBOX'],
        topicName: config.TOPIC_NAME
      }
    });
    res.write(`Watch initialized!`);
    res.status(200).end();
  } catch (err) {
    if (err.message === config.UNKNOWN_USER_MESSAGE) {
      res.redirect('/oauth2init');
    } else {
      console.error(err);
      res.status(500).send('Something went wrong; check the logs.');
    }
  }
});
```

If this doesn't get you pointed in the right direction, check out the complete samples here:
https://github.com/googleapis/google-api-nodejs-client/tree/master/samples/gmail

**Comment by lenyabloko** [comment]
Thanks for the fast response! I used the exact code from the git repo linked to the blog here https://github.com/GoogleCloudPlatform/cloud-functions-gmail-nodejs

Per your suggestion I made the following modifications -->

// Retrieve the stored OAuth 2.0 access token
  return oauth.fetchToken(email)
    .then(() => {
    // Initialize a watch
    const res = await gmail.users.watch({
      auth: oauth.client,
      userId: 'me',
      requestBody: {
        labelIds: ['INBOX'],
        topicName: config.TOPIC_NAME
      }
    })
    .then(() => {
      // Respond with status
      res.write(`Watch initialized!`);
      res.status(200).end();
    })
    .catch((err) => {
      // Handle errors
      if (err.message === config.UNKNOWN_USER_MESSAGE) {
        res.redirect('/oauth2init');
      } else {
        console.error(err);
        res.status(500).send('Something went wrong; check the logs.');
      }
    });

Unfortunately, my new code does not compile-->

Deployment failure:
Function failed on loading user code. Error message: Code in file index.js can't be loaded.
Is there a syntax error in your code?
Detailed stack trace: /srv/index.js:99
    const res = await gmail.users.watch({
                ^^^^^

SyntaxError: await is only valid in async function
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at getUserFunction (/worker/worker.js:439:24)

Can you help me understand why _await_ is a problem inside _.then_?
I am not experienced in using _promises_, but isn't this asynchronous call?

**Comment by JustinBeckwith** [comment]
Can you share what version of `googleapis` you're using?  The call stack looks to include `request` which we haven't used in a _looooooong_ time.  

Also - can you share the implementatioon of `oauth.fetchToken`?

**Comment by lenyabloko** [comment]
Here is the code I used from https://github.com/GoogleCloudPlatform/cloud-functions-gmail-nodejs

```js
"dependencies": {
    "@google-cloud/datastore": "^1.4.0",
    "@google-cloud/debug-agent": "^2.3.0",
    "@google-cloud/vision": "^0.19.0",
    "axios": "^0.18.0",
    "cheerio": "^1.0.0-rc.2",
    "googleapis": "^23.0.0",
    "nconf": "^0.10.0",
    "pify": "^3.0.0",
    "supertest": "^3.0.0"
  },
  "devDependencies": {
    "@google-cloud/nodejs-repo-tools": "2.1.3",
    "ava": "0.24.0",
    "proxyquire": "1.8.0",
    "sinon": "4.1.3"
  },

exports.fetchToken = (emailAddress) => {
  return datastore.get(datastore.key(['oauth2Token', emailAddress]))
    .then((tokens) => {
      const token = tokens[0];

      // Check for new users
      if (!token) {
        throw new Error(config.UNKNOWN_USER_MESSAGE);
      }

      // Validate token
      if (!token.expiry_date || token.expiry_date < Date.now() + 60000) {
        oauth2Client.credentials.refresh_token =
          oauth2Client.credentials.refresh_token || token.refresh_token;
        return new Promise((resolve, reject) => { // Pify and oauth2client don't mix
          oauth2Client.refreshAccessToken((err, response) => {
            if (err) {
              return reject(err);
            }
            return resolve();
          });
        })
          .then(() => {
            return exports.saveToken(emailAddress);
          });
      } else {
        oauth2Client.credentials = token;
        return Promise.resolve();
      }
    });
};

**Comment by JustinBeckwith** [comment]
Yeah - sadly, that code is waaaaay out of date.  I started a conversation over in that repo to get things cleaned up.  Could I trouble you to file this issue over here?
https://github.com/GoogleCloudPlatform/cloud-functions-gmail-nodejs

I would move it if GitHub let me transfer issues between orgs :) As of now, I don't think there's a bug with the auth library, but just a really out of date set of samples.  Lets have the discussion over there where the folks who wrote it can help!
