### ISSUE TITLE
Does this library work with workload identity in GKE?

### ISSUE THREAD

**Issue by karthikprabhu** [googleapis/google-auth-library-nodejs#786]
I have a [workload identity](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity) enabled GKE cluster where I'm using [nodejs-storage](https://github.com/googleapis/nodejs-storage) library for listing files from a bucket. `nodejs-storage` seems to be using this library for authenticating with Google APIs.

On my local setup, I'm using a service account key for authentication and it seems to be working as expected. However, on my GKE cluster I'm using workload identity for authentication and it doesn't seem to be working.

Does this library support workload identity for authentication? Are there any steps that I need to take from my end to get this working with workload identity?

**Comment by karthikprabhu** [comment]
Any updates here?

**Comment by bcoe** [comment]
@karthikprabhu unfortunately, I don't know off the top of my head whether or not we do; @grayside would you happen to be able to direct me to someone who might be able to help answer this question?

**Comment by petrkohut** [comment]
Hello there,
I ended up facing the exact same problem as @karthikprabhu does.
Unfortunately even now on Feb, 2020 I couldn't find any resource showing an example or at least saying that it's possible.

@bcoe are there any updates? (Thanks in advance ;))

**Comment by n1koo** [comment]
Hi, I am very curious about this too as we are getting 

```Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information."
``` 

errors without the ENV and using WI in GKE

**Comment by tchiotludo** [comment]
I found a way to make it work on GKE with workload identity: 
```js
const bigquery = new BigQuery({
    scopes:['https://www.googleapis.com/auth/cloud-platform']
});
```

I need to add this scopes to make it work. 

By default, the node libs will call this url : 
```
curl -H "Metadata-Flavor: Google"  http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fbigquery
```
that lead to this error : 
```
Unable to generate token; IAM returned 403 Forbidden: Request had insufficient authentication scopes.

This error could be caused by a missing IAM policy binding on the target IAM service account.

You can create the necessary policy binding with:

  gcloud iam service-accounts add-iam-policy-binding \
    --role=roles/iam.workloadIdentityUser \
    --member="serviceAccount:{{GCP_PROJECT}}.svc.id.goog[{{NAMESPACE}}/{{GKE_SA}}]" \
    {{SA}}

For more information, refer to the Workload Identity documentation:

    https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity
```

The java lib is doing this curl : 
```
curl -H "Metadata-Flavor: Google"  http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token
```
Not really sure  what the general scope `https://www.googleapis.com/auth/cloud-platform` will change to this previous curl but in my case, this make all working

**Comment by macropin** [comment]
Yes it works. At least with my testing with GCS.

**Comment by fhinkel** [comment]
Greetings, we're closing this. Looks like the issue got resolved. Please let us know if the issue needs to be reopened.
