### ISSUE TITLE
Incomplete TokenInfo TS type

### ISSUE THREAD

**Issue by Slessi** [googleapis/google-auth-library-nodejs#801]
#### Environment details

  - OS: macOS Mojave 10.14.6
  - Node.js version: 12.10.0
  - npm version: 6.11.3
  - `google-auth-library` version: 5.3.0

#### Steps to reproduce

```js
const client = new google.auth.OAuth2("id", "secret");
const tokenInfo = client.getTokenInfo(token);
console.log(tokenInfo);
```

The above outputs the following

```js
{
    expiry_date: 1231231231231,
    scopes: [
        "openid",
        "https://www.googleapis.com/auth/userinfo.profile",
        "https://www.googleapis.com/auth/userinfo.email",
        "https://www.googleapis.com/auth/calendar.readonly",
    ],
    azp: "12312312312-abc123abc123abc123abc123abc123ab.apps.googleusercontent.com",
    aud: "50974679851-abc123abc123abc123abc123abc123ab.apps.googleusercontent.com",
    sub: "123123123123123123123",
    exp: "1231231233",
    email: "what@ever.com",
    email_verified: "true",
    access_type: "offline",
}
```

[getTokenInfo](https://github.com/googleapis/google-auth-library-nodejs/blob/v5.3.0/src/auth/oauth2client.ts#L976) signature specifies a return type of `TokenInfo`

```ts
async getTokenInfo(accessToken: string): Promise<TokenInfo>
```

[TokenInfo](https://github.com/googleapis/google-auth-library-nodejs/blob/v5.3.0/src/auth/oauth2client.ts#L70) interface is defined as follows (comments omitted):

```ts
export interface TokenInfo {
    aud: string;
    user_id?: string;
    scopes: string[];
    expiry_date: number;
    sub?: string;
    azp?: string;
    access_type?: string;
}
```

The type doesn't match the logged output.

I can't find the documentation for `google-auth-library-nodejs` (although I did find for [google-api-nodejs-client](https://googleapis.dev/nodejs/googleapis/latest/oauth2/interfaces/Schema$Tokeninfo-1.html))

Currently the only field I'm interested in that's missing is the `email` field, but I'm unsure if I can trust it to remain there.

**Comment by bcoe** [comment]
@Slessi the most likely issue is that our types were not comprehensive. If you would like to send a PR with the additional field `email?: string` added, I will happily land it; alternatively, we can keep this issue open, and we'll make an effort to update our types soon.

**Comment by Slessi** [comment]
@bcoe I'd happily add it, only reason I didn't is I wasnt able to find documentation to outline if it was optional or required.

If you have a link I could add other missing fields too.

**Comment by bcoe** [comment]
@Slessi see the section `Obtain user information from the ID token`: 

https://developers.google.com/identity/protocols/OpenIDConnect

The `scopes` aren't listed, but obviously are also returned, so let's leave those. As with the existing TypeScript definition, I'd make the fields optional.

**Comment by TithSambath** [comment]
Sorry, to ask. but may i know is there a way we can get UserInfo like below

`
{
  "id": "102530475701519183892",
  "email": "example@gmail.com",
  "verified_email": true,
  "name": "Example User",
  "given_name": "Example",
  "family_name": "User",
  "picture": "https://lh3.googleusercontent.com/a/ACg8ocJB6Bw-VoeUzv4PxFfKddcwescePFgxlNEXWRHMyEE18dTKww=s96-c"
}
`
