### ISSUE TITLE
P12/PEM file support

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/google-auth-library-nodejs#808]
- OS: macOS 10.14.6
  - Node.js version: 12.6.0
  - npm version: 6.9.0
  - `google-auth-library` version: 5.4.0

I'm struggling to get a client using a P12/PEM file, and I'm wondering if it's my fault!

```js
const GoogleAuth = require('google-auth-library').GoogleAuth
const auth = new GoogleAuth({ keyFilename: '/path/to/key.p12' })
await auth.getClient() // crashes with below output
```
```
 SyntaxError: Unexpected token � in JSON at position 1
    at JSON.parse (<anonymous>)
    at ReadStream.<anonymous> (/Users/stephen/dev/play/gissue-218/node_modules/google-auth-library/build/src/auth/googleauth.js:347:39)
    at ReadStream.emit (events.js:208:15)
    at ReadStream.EventEmitter.emit (domain.js:494:23)
    at endReadableNT (_stream_readable.js:1154:12)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
```

The key file is being passed around the "googleauth.js" file, and after a read stream is opened to digest the key file, it is parsed as JSON, which throws the error. The JWT file handles a key file path by checking the mime-type.

Does it look like I'm doing something wrong here?

**Comment by emilioSp** [comment]
Any news on this? @JustinBeckwith 
I've the same issue. 
Thanks!

**Comment by JustinBeckwith** [comment]
Nope

**Comment by stephenplusplus** [comment]
@bcoe @JustinBeckwith do we support this form of auth anymore? Did we lose it one day and nobody noticed?

**Comment by JustinBeckwith** [comment]
I honestly have no idea :/  I know the auth library supports it on some level

**Comment by bcoe** [comment]
@stephenplusplus we support self-signed JWTs, is that what we'd expect this key file to be used for?

**Comment by aareshchanka** [comment]
@bcoe java sdk supports P12/PEM file formats, it looks there like
`new GoogleCredential.Builder().setTransport(transport)
        .setJsonFactory(jsonFactory)
        .setServiceAccountId(serviceAccountId)
        .setServiceAccountScopes(serviceAccountScopes)
        .setServiceAccountPrivateKeyFromP12File(p12File)
        .build();`
We are trying to migrate our code to nodejs, but not able to run api requests through service account as we use p12 file

**Comment by bcoe** [comment]
@aareshchanka we have several tests related to authenticating a client with a PEM or P12 format certificate:

https://github.com/googleapis/google-auth-library-nodejs/blob/9116f247486d6376feca505bbfa42a91d5e579e2/test/test.jwt.ts#L114

Do you run into an error if you use these as an example.
