### ISSUE TITLE
LoginTicket / TokenPayload types are not exported

### ISSUE THREAD

**Issue by hjr3** [googleapis/google-auth-library-nodejs#869]
I am trying to create a function that returns the `LoginTicket` or `TokenPayload`. These types are not exported. I see that `LoginTicket` is a class and maybe there is a reason to keep that private. If I have to settle for `TokenPayload`, that will satisfy my use case.

Example:

```ts
import { OAuth2Client, LoginTicket } from 'google-auth-library';

async function verify(idToken: string): LoginTicket {
  const client = new OAuth2Client({
    clientId: CLIENT_ID,
  });

  const ticket = await client.verifyIdToken({
    idToken,
    audience: CLIENT_ID,
  });

  return ticket;
}
```

Will you accept a patch with one or both of these types exported?

**Comment by bcoe** [comment]
@hjr3 we'd happily accept a patch :+1:, seems like exporting both is reasonable? what do you think?

**Comment by hjr3** [comment]
> seems like exporting both is reasonable? what do you think?

Agreed, I will export both. CLA signed and patch is forthcoming.
