### ISSUE TITLE
What is the different between google.auth.OAuth2 and OAuth2Client?

### ISSUE THREAD

**Issue by baruchiro** [googleapis/google-auth-library-nodejs#877]
I see two different options to create a Google OAuth2 client:

```node
import { OAuth2Client } from 'google-auth-library'
const client = new OAuth2Client('ID', 'SECRET', 'Redirect')
```

And

```node
import { google } from 'googleapis'
const client = new google.auth.OAuth2('ID', 'SECRET', 'Redirect')
```

There is a difference between them, or there are the same source code?

**Comment by JustinBeckwith** [comment]
They're the same thing :) In the `google-api-nodejs-client` the name was aliased for reasons of back compat.  You can see the assignment here:
https://github.com/googleapis/nodejs-googleapis-common/blob/master/src/authplus.ts#L24

Let me know if you have any other questions!
