### ISSUE TITLE
getting bad request when calling gmail api

### ISSUE THREAD

**Issue by penzital** [googleapis/google-auth-library-nodejs#898]
Hello team.

I'm trying to connect to gmail api using service account to read emails of our gsuit users. I don't have access to my company gsuit so I created my own for testing purposes.
I created organization, project and service account with domain-wide delegation enabled. From admin console I enabled API access and gave my service account `Email (Read/Write/Send)  https://mail.google.com/
https://www.googleapis.com/auth/cloud-platform`  scopes. From the console I gave the service account **project owner** role and created a test user(**testemail@penzital.com**) that is to be accessed by the service account, added it to the project. I set the downloaded service account json key as an environment variable and here is my code:
```
const scopes = [
            // "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/gmail.labels"
        ];
        const googleAuth = new GoogleAuth({
            scopes: scopes
        });
        const client = await googleAuth.getClient();
        const gmail = google.gmail({ version: "v1", auth: client });
        const userLabels = await gmail.users.labels.list({
            userId: "testemail@penzital.com"
        });
        console.log(userLabels);
```
whenever I give my client any of the gmail scopes I'm getting **400 - Bad Request - failedPrecondition**. If I use `https://www.googleapis.com/auth/cloud-platform` (which gives full access to all APIs?) I get **Insufficient Permissions** even though both are granted to service account through admin console.
Are there any special requirements for organization/project set up? Does service account or user to be impersonated by service account need to have any specific roles? Gmail API docs only covers api authorization scopes.
Could I be having issues because I'm running it locally?
I would appreciate your help.

**Comment by bcoe** [comment]
:wave: @penzital how are you authenticating? I believe gmail expects [OAuth 2.0 authentication](https://developers.google.com/gmail/api/auth/about-auth). How our auth library supports this is documented [here](https://github.com/googleapis/google-auth-library-nodejs#oauth2).

**Comment by penzital** [comment]
I downloaded the credentials for my service account from console and set its path in `GOOGLE_APPLICATION_CREDENTIALS`. Followed [this](https://github.com/googleapis/google-auth-library-nodejs#application-default-credentials) guide

**Comment by khipkin** [comment]
Hello. I've filed a feature request with Google to improve this error message. Please star the issue here: https://issuetracker.google.com/issues/157590195.

**Comment by fhinkel** [comment]
Thanks for filing the issue on the issue tracker. Closing this.
