### ISSUE TITLE
Emulator for `@google-cloud/pubsub` results in Could not load the default credentials error

### ISSUE THREAD

**Issue by oreporan** [googleapis/google-auth-library-nodejs#923]
I'm running some tests using the google pubsub client.

My code looks like this (changed after reading issue #798 ):

```js
import {PubSub} from '@google-cloud/pubsub';

let pubsub: PubSub;

export const initPubsub = async () => {
    pubsub = new PubSub({
        projectId: 'blackbox_tests',
    });
};

```
later on I try and create topics

```js

const createTopic = async (name: string) =>   await pubsub.createTopic(name);
```

error I get: 
```
blackbox-tests_1             |     Could not load the default credentials. Browse to https://cloud.google.com/doc
s/authentication/getting-started for more information.                                                           
blackbox-tests_1             |                                                                                   
blackbox-tests_1             |       at GoogleAuth.getApplicationDefaultAsync (node_modules/google-auth-library/b
uild/src/auth/googleauth.js:160:19)                                                                              
blackbox-tests_1             |           at runMicrotasks (<anonymous>)                                          
blackbox-tests_1             |       at GoogleAuth.getClient (node_modules/google-auth-library/build/src/auth/goo
gleauth.js:502:17)                                                                                               
blackbox-tests_1             |       at GrpcClient._getCredentials (node_modules/google-gax/src/grpc.ts:136:20)  
blackbox-tests_1             |       at GrpcClient.createStub (node_modules/google-gax/src/grpc.ts:281:19)    
```

#### Environment details

  - OS: node:12
  - Node.js version: 12
  - `google-auth-library` version: 3.0.0
- `@google-cloud/pubsub` version: 0.28.1

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by bcoe** [comment]
@oreporan  if possible could you share a bit more of your code. The most important thing is that you have completed all asynchronous work before you call `res.send` in your cloud function.

**Comment by oreporan** [comment]
There is no res.send, this is a setup (thats worked in the past) for testing

I have a docker container setup that hosts the pubsub, and my code just creates some topics for it.

So this is a helper method for the tests:

```ts
export const createTopic = async (name: string) => {
   const [topic] = await getPubsub().createTopic(name);
        const [subscription] = await topic.createSubscription(name);
};
```


being used in the tests:

```ts
 beforeEach(async () => {
        await pubsub.createTopic('my-topic');
    });
```

**Comment by bcoe** [comment]
@oreporan what environment are you running this container in?

**Comment by oreporan** [comment]
I've tried:

```
node:10
node:12
node:alpine
```

**Comment by bcoe** [comment]
@oreporan gotcha, are you running on Cloud Run? If you're running in a non-GCP environment you  will want to create [service account credentials](https://cloud.google.com/docs/authentication/getting-started) which you then make available in your container.

The issue described in #798 is intermittent related to a race condition, this sounds more like the container you're running is simply failing to detect environment, or does not have credentials provided to it.

**Comment by oreporan** [comment]
According to the [docs](https://www.npmjs.com/package/@google-cloud/pubsub#using-the-client-library) it doesn't mention adding credentials.

What do you mean by failing to detect environment? Does it have to do with passing `PUBSUB_EMULATOR_HOST` ?

Do I need to pass the docker-compose host URL to the constructor?

**Comment by bcoe** [comment]
@oreporan to clarify, you are trying to run a docker container that connects to an emulator locally? This is not running in a Google Cloud environment?

**Comment by oreporan** [comment]
it connects via docker-compose

**Comment by mvergarair** [comment]
I'm getting the same problem on a cloud function
```
Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
    at GoogleAuth.getApplicationDefaultAsync (/srv/functions/node_modules/google-auth-library/build/src/auth/googleauth.js:160:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
The weird thing is that I use the exact same code for other CFs and there working perfect, it's only one.
```
export function sendDividendUserPubSub(dividendId: string, userId: string): Promise<any> {
  return publisher.topic('dividendsAssignUser').publishJSON({
    dividendId,
    userId,
  }); 
}
```

**Comment by bcoe** [comment]
@oreporan if you are connecting from a local machine, and not in a Google Cloud environment (such as Google Cloud Functions), you must provide credentials.

A good way to do this is with [service account credentials](https://cloud.google.com/docs/authentication/getting-started) which you provide via the environment variable `GOOGLE_APPLICATION_CREDENTIALS`.

_If you do not wish to connect to the actual PubSub service, and are just trying to connect to an emulator, this might be a bug specifically related to the emulator._

----

@mvergarair I believe what you are describing is a completely different issue, since you are in a Google Cloud Function environment, and it sounds like @oreporan is attempting to run the library locally in a docker-compose container.

Please feel free to open an a bug, with more context. Seeing more of your application would help debug.

**Comment by meredithslota** [comment]
FYI @feywind — I think you might have dealt with a similar issue elsewhere?

**Comment by sofisl** [comment]
Hi all, just wanting to follow up on this issue. Is the problem persisting? 

I attempted to recreate the issue, but was unable. When you spun up the emulator, did you also set up the environment variables? You can do so with `gcloud beta emulators pubsub env-init`, or manually,
```
export PUBSUB_EMULATOR_HOST=localhost:8432 
export PUBSUB_PROJECT_ID=my-project-id
```

See more info [here](https://cloud.google.com/pubsub/docs/emulator).

**Comment by sofisl** [comment]
@oreporan @mvergarair

**Comment by sofisl** [comment]
Hi @oreporan @mvergarair, I'm going to go ahead to close this issue for now since I haven't heard anything back. Feel free to reopen if you're still running into this issue. Thanks!
