### ISSUE TITLE
UserRefreshToken seems to not be typed correctly

### ISSUE THREAD

**Issue by schmidt-sebastian** [googleapis/google-auth-library-nodejs#924]
I am trying to find a way to use a UserRefrehToken in `@google-cloud/firestore`. What I have come up with is:

```
const firestore = new Firestore({
  projectId: "...",
  credentials: {
    type: "authorized_user",  // Note: Not documented
    client_id: "....apps.googleusercontent.com",
    client_secret: "...",
    refresh_token: "..."    
  } as any
});
```

As defined, the options don't seem to support this usage pattern (hence the usage of `any`). `credentials` is of type CredentialBody and only meant to contain `client_email` and `private_key`. 

`UserRefreshClientOptions` are instead meant to be put in `clientOptions`. `clientOptions` is however not used when the credentials are parsed from JSON, and hence passing in `clientOptions` does not have the desired effect:

https://github.com/googleapis/google-auth-library-nodejs/blob/f453fb7d8355e6dc74800b18d6f43c4e91d4acc9/src/auth/googleauth.ts#L423

Note that `json` here is the `credentials` object and not `clientOptions`.

Am I doing something wrong?

**Comment by sofisl** [comment]
After doing some experimentation, I've confirmed that this should work: 

```
const firestore = new Firestore({
  projectId: "...",
  clientOptions: {
    type: "authorized_user",  // Note: Not documented
    client_id: "....apps.googleusercontent.com",
    client_secret: "...",
    refresh_token: "..."    
  } as UserRefreshClientOptions
});
```

Labeling it as UserRefreshClientOptions should eventually lead you [here](https://github.com/googleapis/google-auth-library-nodejs/blob/73f0b0f99a67ec099bc5e6f74f9396dcbadb7c32/src/auth/refreshclient.ts#L85) to authenticate properly.
