### ISSUE TITLE
Redeem serverAuthCode from iOS library using nodejs server

### ISSUE THREAD

**Issue by JacobWrenn** [googleapis/google-auth-library-nodejs#949]
I am using Google Sign In on my iOS app. This provides an option for a `serverAuthCode` that allows a server to access Google APIs on behalf of the user.

The official example here <https://developers.google.com/identity/sign-in/ios/offline-access> only provides Java and Python server examples.

Does this work with the nodejs library?

If not, can I be pointed towards the documentation for how to redeem the code using normal https requests and no library.

**Comment by bcoe** [comment]
@JacobWrenn 👋 you should be able to get this working with the Node.js library. I believe the `offline` example in the README might be what you're looking for [here](https://github.com/googleapis/google-auth-library-nodejs#a-complete-oauth2-example).

**Comment by fhinkel** [comment]
Greetings, we're closing this. Looks like the issue got resolved. Please let us know if the issue needs to be reopened.
