### ISSUE TITLE
Firebase error "Could not load the default credentials" [SOLVED]

### ISSUE THREAD

**Issue by jrschumacher** [googleapis/google-auth-library-nodejs#958]
I was running into `Could not load the default credentials` error with Firebase and using Google Cloud APIs like PubSub. After much searching, I learned that it's due to having the PubSub client initialized in the global scope. 

> isolated this problem to creating a client in the global scope outside of your function see: function execution lifetime. [Issue 798](https://github.com/googleapis/google-auth-library-nodejs/issues/798#issuecomment-591622283)

**Solution**

Moved the `const pubsub = new PubSub()` out of the global scope and into an `async` function as described in the referenced issue above. 

Additionally, you should install/update `google-auth-library` to **6.0.0** with `npm i --save google-auth-library@6.0.0` (I was running 5.0.0 despite updating `@google-cloud/pubsub` to **1.7.3** which has the correct dep of `google-auth-library`)

When I redeployed functions it was successful.

---
I added this issue to reduce the effort debugging this issue. When coming from firebase it can be confusing as the documentation to use GC APIs is not clear and it isn't easily understood that Firebase functions are GC Functions until you dive deep in the GC Project. 

Areas like [Obtaining credentials on Compute Engine, Kubernetes Engine, App Engine flexible environment, and Cloud Functions](https://cloud.google.com/docs/authentication/production#obtaining_credentials_on_compute_engine_kubernetes_engine_app_engine_flexible_environment_and_cloud_functions) should include references to Firebase for clarity. 

Additionally, there should be a comment in the code snippet in the above link explaining why the client initialization is done in the async function. I interpreted it as a convention. 

#### Environment details

  - OS: Firebase functions / GC Functions
  - Node.js version: 10
  - npm version: ?
  - `google-auth-library` version: 5.5.0

**Comment by bcoe** [comment]
@jrschumacher thank you for this ticket, and for updating it with your solution 👍 

For me, it's good to have verification that the connection issues we see on startup are related to a GCF function being slept, this is a topic of much internal discussion.
