### ISSUE TITLE
method to validate the id_token from client js app, without the need for calling google servers, as in nodejs driver

### ISSUE THREAD

**Issue by rajamaniraja** [googleapis/google-auth-library-nodejs#960]
```js
const {OAuth2Client} = require('google-auth-library');
const client = new OAuth2Client(CLIENT_ID);
async function verify() {
  const ticket = await client.verifyIdToken({
      idToken: token,
      audience: CLIENT_ID,  // Specify the CLIENT_ID of the app that accesses the backend
      // Or, if multiple clients access the backend:
      //[CLIENT_ID_1, CLIENT_ID_2, CLIENT_ID_3]
  });
  const payload = ticket.getPayload();
  const userid = payload['sub'];
  // If request specified a G Suite domain:
  //const domain = payload['hd'];
}
verify().catch(console.error);

//Something similar in Nodejs
```

**Comment by JustinBeckwith** [comment]
Greetings!  The only thing in id token verification that requires network access is the download of the latest certificates from the google discovery certificates.  While these don't change terribly often, they do change over time.  I highly recommend using the `verifyIdToken` method, which will reach out to the network on the first call (it caches the cert).  

If you really need to perform idToken validate, you can download certificates from here:
https://developers.google.com/identity/protocols/oauth2/openid-connect#discovery

And then call the `verifySignedJwtWithCertsAsync` method here:
https://github.com/googleapis/google-auth-library-nodejs/blob/6a39ae8d181d65bec0d7fcf063990d530077165c/src/auth/oauth2client.ts#L1174

This doc explains step by step what's happening:
https://developers.google.com/identity/protocols/oauth2/openid-connect#validatinganidtoken

Hope this helps!

**Comment by rajamaniraja** [comment]
Thanks
