### ISSUE TITLE
google-auth-library Error: invalid_request Required parameter is missing: response_type

### ISSUE THREAD

**Issue by paulwongx** [googleapis/google-auth-library-nodejs#967]
I'm trying to programmatically get a Google access token via Google-Auth-Library. I already have a client_id, client_secret, and refresh token. I literally copied the code from Google's documentation 1 but I'm getting Error: invalid_request  Required parameter is missing: response_type

I tried adding response_type: 'code' in many places in the code but I get the same responses... Where am I supposed to put in this parameter?
```javascript
const {OAuth2Client} = require('google-auth-library');
const http = require('http');
const url = require('url');
const open = require('open');
const destroyer = require('server-destroy');

const keys = require('./oauth2.keys.json');

async function main() {
  try {
    const oAuth2Client = await getAuthenticatedClient();
    const url = 'https://accounts.google.com/o/oauth2/v2/auth';
    const res = await oAuth2Client.request({url});
    console.log(res.data);

    const tokenInfo = await oAuth2Client.getTokenInfo(
      oAuth2Client.credentials.access_token
    );
    console.log(tokenInfo);
  }
  catch (err) {
    console.log(`oauth2: ${err}`);
  }
}

function getAuthenticatedClient() {
  return new Promise((resolve, reject) => {
    const oAuth2Client = new OAuth2Client(
      keys.web.client_id,
      keys.web.client_secret,
      keys.web.redirect_uris[0]
    );

    const authorizeUrl = oAuth2Client.generateAuthUrl({
      access_type: 'offline',
      scope: 'https://www.googleapis.com/auth/youtube',
    });

    const server = http
    .createServer(async (req, res) => {
      try {
        if (req.url.indexOf('/oauth2callback') > -1) {
          // acquire the code from the querystring, and close the web server.
          const qs = new url.URL(req.url, 'http://localhost:3000')
            .searchParams;
          const code = qs.get('code');
          console.log(`Code is ${code}`);
          res.end('Authentication successful! Please return to the console.');
          server.destroy();

          const r = await oAuth2Client.getToken(code);
          // Make sure to set the credentials on the OAuth2 client.
          oAuth2Client.setCredentials(r.tokens);
          console.info('Tokens acquired.');
          resolve(oAuth2Client);
        }
      } catch (e) {
        reject(e);
      }
    })
    .listen(3000, () => {
      // open the browser to the authorize url to start the workflow
      open(authorizeUrl, {wait: false}).then(cp => cp.unref());
    });
    destroyer(server);
  });
}

main();
```
Please note the URL (oauth2) and scope URL (youtube scope) have been changed for my project purposes, compared to the documentation.

[1] https://github.com/googleapis/google-auth-library-nodejs

**Comment by bcoe** [comment]
@paulwongx did you try the [approach outlined here](https://github.com/googleapis/google-auth-library-nodejs#handling-token-events) on "Handling token events", I think you should be able to instantiate a client with `oauth2.keys.json`, and listen the `token` event.

**Comment by paulwongx** [comment]
> @paulwongx did you try the [approach outlined here](https://github.com/googleapis/google-auth-library-nodejs#handling-token-events) on "Handling token events", I think you should be able to instantiate a client with `oauth2.keys.json`, and listen the `token` event.

My apologies, I realized the issue is not with the module, but with Windows Subsystem for Linux 2 (WSL2) not being able to run code with GUI components. When the module "open" tries to open the google authenticate URL, it always comes back with the reply "response_type is missing".

This same code works on my mac, so it's a WSL2 issue.
The solution is the setup an X Display for WSL2 (of which I'm still trying to figure out).

I think this is helpful for others in the future, but the issue can be closed. Thank you.

**Comment by bcoe** [comment]
@paulwongx awesome 👍 I'm glad you're unblocked.
