### ISSUE TITLE
TypeError: oAuth2Client.getIapCerts is not a function at verify

### ISSUE THREAD

**Issue by tkatochin** [googleapis/google-auth-library-nodejs#979]
When /samples/verifyIdToken-iap.js is executed, an error will occur according to the subject.
version is 6.0.2

Searching for "getIapPublicKeys" from google-auth-library in node_modules does not find it. Isn't this sample code wrong?
Or did it exist in previous versions but is it gone now?
Please update to the correct sample code.

**Comment by sofisl** [comment]
@tkatochin, first off, I want to apologize for how long it took to respond to this! It looks like the issue resolved itself, I see it in the file now (latest version):

![Screen Shot 2020-12-01 at 11 36 02 AM](https://user-images.githubusercontent.com/55454395/100788084-720f9900-33c9-11eb-9b21-eba1e87b4c72.png)

Can you confirm that it is working now? Thanks in advance.

**Comment by sofisl** [comment]
Hi @tkatochin, friendly ping! Otherwise I will close the issue soon. Thanks!
