### ISSUE TITLE
Insufficient Permission

### ISSUE THREAD

**Issue by bolds07** [googleapis/google-auth-library-nodejs#981]
#### Environment details

  - OS: google cloud functions
  - Node.js version: 10
  - npm version: ??
  - `google-auth-library` version: 6.0.2

#### Steps to reproduce

```
const packageName = MY PACKAGE NAME";
const email = 'SOMETHING@api-A LOT OF NUMBERS.iam.gserviceaccount.com';
const key = '-----BEGIN PRIVATE KEY-----\nBLA BLA BLA BLA\n-----END PRIVATE KEY-----\n';

const client = new (require('google-auth-library')).JWT({
        email: email,
        key: key,
        scopes: ['https://www.googleapis.com/auth/cloud-platform'],
      });

client.request({url: ''https://www.googleapis.com/androidpublisher/v3/applications/' + packageName + '/inappproducts/proversion_0'', 	method: 'GET'});
```

ERROR:
```
nhandledPromiseRejectionWarning: Error: Insufficient Permission
    at Gaxios._request (/home/runner/googlepay/node_modules/gaxios/build/src/gaxios.js:85:23)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async JWT.requestAsync (/home/runner/googlepay/node_modules/google-auth-library/build/src/auth/oauth2client.js:341:18)
```

I'm trying to move from an very olddated unnoficial api to the official google api,
this very simple code works fine in the unofficial https://github.com/extrabacon/google-oauth-jwt api, but it is very deprecated and i would like to update, but when trying to i get permission error, how can i have permission erro if it was working with other api

Thanks!

**Comment by bolds07** [comment]
sorry i copied to much from google's example and just after writing this i noticed... worked normal now

**Comment by Bhargav704** [comment]
@bolds07  How it started working for you ? can you please explain how you resolved it ?

**Comment by mpacary** [comment]
@ghost, I hope that you've sorted out your issue?

For anyone passing by :

I hit the same error while migrating to version 8.6.0 of **google-auth-library**. I had to first call `client.authorize()` before querying Google APIs.

[Current doc for v108](https://www.npmjs.com/package/google-auth-library/v/8.6.0) seems inaccurate, I had to dig in [older versions of the doc](https://www.npmjs.com/package/google-auth-library/v/1.0.0#using-json-web-tokens) to get correct examples of using JWT instanciation + authentication + making requests.

Overall it looks like this:

```
const { OAuth2Client, JWT } = require('google-auth-library');
const fs = require('fs');

// ...

let content = fs.readFileSync(credentialsFilename);

let credentials = JSON.parse(content);

let client = new JWT({
        email: credentials.client_email,
        key: credentials.private_key,
        scopes: [...]
    });

client.authorize().then((result) => {
    let oauth2Client = new OAuth2Client();

    oauth2Client.setCredentials({
        access_token: result.access_token
    });

    // there, you can query Google APIs,
    // using npm library 'googleapis' and providing the oauth2client,
    // or maybe using client.request()
};
```
